package Telas;

import Cadastros.CadastroAgenciaConta;
import Cadastros.CadastroBanco;
import Cadastros.CadastroCidade;
import Cadastros.CadastroCliente;
import Cadastros.CadastroContas;
import Cadastros.CadastroContato;
import Cadastros.CadastroEndereco;
import Cadastros.CadastroEstado;
import Cadastros.CadastroFamilia;
import Cadastros.CadastroFormadePagamento;
import Cadastros.CadastroFornecedor;
import Cadastros.CadastroFuncionario;
import Cadastros.CadastroMesa;
import Cadastros.CadastroNivel;
import Cadastros.CadastroOperacao;
import Cadastros.CadastroOrigem;
import Cadastros.CadastroProduto;
import Cadastros.CadastroTipoPagamento;
import Cadastros.CadastroUsuario;
import Servicos.ExibirMesas;
import Servicos.TelaAtendimentoMesa;
import Servicos.TelaAtendimentos;
import Servicos.TelaVendaCompra;
import Validacoes.Avisos;
import Validacoes.ValidaNivelUsuario;
import java.awt.event.KeyEvent;
//import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Leonardo
 */
public class MenuPrincipal extends javax.swing.JFrame {

    public static String usuarioAtual;
    
    ValidaNivelUsuario validaUsuario = new ValidaNivelUsuario();
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        
        carregaImagem();  
        
        TelaLogin login = new TelaLogin(this, true);
        login.setVisible(true);
        
        if (usuarioAtual == null){
            System.exit(0);
        }
        validaUsuario.checarBarra(jMenuBarPrincipal, usuarioAtual);
        jLabelAtual.setText(usuarioAtual);
        
        procuraAvisos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelImagem = new javax.swing.JPanel();
        jLabelAtual = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelSair = new javax.swing.JLabel();
        jMenuBarPrincipal = new javax.swing.JMenuBar();
        jMenuCadastros = new javax.swing.JMenu();
        jMenuItemCadMesa = new javax.swing.JMenuItem();
        jMenuItemCadCliente = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemCadOrigem = new javax.swing.JMenuItem();
        jMenuItemCadFamilia = new javax.swing.JMenuItem();
        jMenuItemCadProduto = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItemCadEndereco = new javax.swing.JMenuItem();
        jMenuItemCadContato = new javax.swing.JMenuItem();
        jMenuItemCadEstado = new javax.swing.JMenuItem();
        jMenuItemCadCidade = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItemCadForma = new javax.swing.JMenuItem();
        jMenuItemCadTipo = new javax.swing.JMenuItem();
        jMenuItemCadOperacao = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItemCadFornecedor = new javax.swing.JMenuItem();
        jMenuItemCadFuncionario = new javax.swing.JMenuItem();
        jMenuServicos = new javax.swing.JMenu();
        jMenuItemAtendimento = new javax.swing.JMenuItem();
        jMenuItemVenda = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItemExibirAtendimentos = new javax.swing.JMenuItem();
        jMenuItemExibirMesas = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jMenuItemSaldoProdutos = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        jMenuItemExibirMovEstoque = new javax.swing.JMenuItem();
        jMenuFinanceiro = new javax.swing.JMenu();
        jMenuItemBancos = new javax.swing.JMenuItem();
        jMenuItemAgencia = new javax.swing.JMenuItem();
        jMenuItemContas = new javax.swing.JMenuItem();
        jMenuItemPagamento = new javax.swing.JMenuItem();
        jMenuItemTransferencia = new javax.swing.JMenuItem();
        jMenuItemGerenciarCheques = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMenuItemMovCaixa = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        jMenuItemFaturamento = new javax.swing.JMenuItem();
        jMenuUsuarios = new javax.swing.JMenu();
        jMenuItemGerenciarUsuarios = new javax.swing.JMenuItem();
        jMenuItemGerenciarNiveis = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Al Tálio Sistema");
        setIconImages(null);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        javax.swing.GroupLayout jPanelImagemLayout = new javax.swing.GroupLayout(jPanelImagem);
        jPanelImagem.setLayout(jPanelImagemLayout);
        jPanelImagemLayout.setHorizontalGroup(
            jPanelImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1100, Short.MAX_VALUE)
        );
        jPanelImagemLayout.setVerticalGroup(
            jPanelImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 618, Short.MAX_VALUE)
        );

        jLabelAtual.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelAtual.setForeground(new java.awt.Color(0, 51, 255));
        jLabelAtual.setText("User");

        jLabel1.setText("Logado como :");

        jLabelSair.setForeground(new java.awt.Color(255, 0, 0));
        jLabelSair.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSair.setText("Sair");
        jLabelSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSairMouseClicked(evt);
            }
        });

        jMenuCadastros.setMnemonic(KeyEvent.VK_C);
        jMenuCadastros.setText("Cadastros");
        jMenuCadastros.setMargin(new java.awt.Insets(0, 0, 0, 5));
        jMenuCadastros.setName("MENU CADASTROS"); // NOI18N

        jMenuItemCadMesa.setText("Cadastrar Mesa");
        jMenuItemCadMesa.setName("CADASTRAR MESA"); // NOI18N
        jMenuItemCadMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadMesaActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemCadMesa);

        jMenuItemCadCliente.setText("Cadastrar Cliente");
        jMenuItemCadCliente.setName("CADASTRAR CLIENTES"); // NOI18N
        jMenuItemCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadClienteActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemCadCliente);
        jMenuCadastros.add(jSeparator1);

        jMenuItemCadOrigem.setText("Cadastrar Origem de Produtos");
        jMenuItemCadOrigem.setName("CADASTRAR ORIGEM"); // NOI18N
        jMenuItemCadOrigem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadOrigemActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemCadOrigem);

        jMenuItemCadFamilia.setText("Cadastrar Família de Produtos");
        jMenuItemCadFamilia.setName("CADASTRAR FAMÍLIA DE PRODUTOS"); // NOI18N
        jMenuItemCadFamilia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadFamiliaActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemCadFamilia);

        jMenuItemCadProduto.setText("Cadastrar Produtos");
        jMenuItemCadProduto.setName("CADASTRAR PRODUTOS"); // NOI18N
        jMenuItemCadProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadProdutoActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemCadProduto);
        jMenuCadastros.add(jSeparator2);

        jMenuItemCadEndereco.setText("Cadastrar Endereços");
        jMenuItemCadEndereco.setName("CADASTRAR ENDEREÇO"); // NOI18N
        jMenuItemCadEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadEnderecoActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemCadEndereco);

        jMenuItemCadContato.setText("Cadastrar Contatos");
        jMenuItemCadContato.setName("CADASTRAR CONTATO"); // NOI18N
        jMenuItemCadContato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadContatoActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemCadContato);

        jMenuItemCadEstado.setText("Cadastrar Estados");
        jMenuItemCadEstado.setName("CADASTRAR ESTADO"); // NOI18N
        jMenuItemCadEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadEstadoActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemCadEstado);

        jMenuItemCadCidade.setText("Cadastrar Cidades");
        jMenuItemCadCidade.setName("CADASTRAR CIDADE"); // NOI18N
        jMenuItemCadCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadCidadeActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemCadCidade);
        jMenuCadastros.add(jSeparator3);

        jMenuItemCadForma.setText("Cadastrar Formas de Pagamento");
        jMenuItemCadForma.setName("CADASTRAR FORMA DE PAGAMENTO"); // NOI18N
        jMenuItemCadForma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadFormaActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemCadForma);

        jMenuItemCadTipo.setText("Cadastrar Tipos de Pagamento");
        jMenuItemCadTipo.setName("CADASTRAR TIPO DE PAGAMENTO"); // NOI18N
        jMenuItemCadTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadTipoActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemCadTipo);

        jMenuItemCadOperacao.setText("Cadastrar Operação");
        jMenuItemCadOperacao.setName("CADASTRAR OPERAÇÃO"); // NOI18N
        jMenuItemCadOperacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadOperacaoActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemCadOperacao);
        jMenuCadastros.add(jSeparator4);

        jMenuItemCadFornecedor.setText("Cadastrar Fornecedores");
        jMenuItemCadFornecedor.setName("CADASTRAR FORNECEDORES"); // NOI18N
        jMenuItemCadFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadFornecedorActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemCadFornecedor);

        jMenuItemCadFuncionario.setText("Cadastrar Funcionários");
        jMenuItemCadFuncionario.setName("CADASTRAR FUNCIONÁRIOS"); // NOI18N
        jMenuItemCadFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadFuncionarioActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemCadFuncionario);

        jMenuBarPrincipal.add(jMenuCadastros);

        jMenuServicos.setMnemonic(KeyEvent.VK_S);
        jMenuServicos.setText("Serviços");
        jMenuServicos.setMargin(new java.awt.Insets(0, 0, 0, 5));
        jMenuServicos.setName("MENU SERVIÇOS"); // NOI18N

        jMenuItemAtendimento.setText("Realizar Atendimento");
        jMenuItemAtendimento.setName("REALIZAR ATENDIMENTO MESA"); // NOI18N
        jMenuItemAtendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAtendimentoActionPerformed(evt);
            }
        });
        jMenuServicos.add(jMenuItemAtendimento);

        jMenuItemVenda.setText("Realizar Venda/Compra");
        jMenuItemVenda.setName("REALIZAR VENDA/COMPRA"); // NOI18N
        jMenuItemVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVendaActionPerformed(evt);
            }
        });
        jMenuServicos.add(jMenuItemVenda);
        jMenuServicos.add(jSeparator5);

        jMenuItemExibirAtendimentos.setText("Exibir Atendimentos");
        jMenuItemExibirAtendimentos.setName("CONSULTAR ATENDIMENTOS"); // NOI18N
        jMenuItemExibirAtendimentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExibirAtendimentosActionPerformed(evt);
            }
        });
        jMenuServicos.add(jMenuItemExibirAtendimentos);

        jMenuItemExibirMesas.setText("Exibir Mesas");
        jMenuItemExibirMesas.setName("EXIBIR MESAS"); // NOI18N
        jMenuItemExibirMesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExibirMesasActionPerformed(evt);
            }
        });
        jMenuServicos.add(jMenuItemExibirMesas);
        jMenuServicos.add(jSeparator7);

        jMenuItemSaldoProdutos.setText("Exibir Saldo dos Produtos");
        jMenuItemSaldoProdutos.setName("CONSULTAR SALDO PRODUTOS"); // NOI18N
        jMenuItemSaldoProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSaldoProdutosActionPerformed(evt);
            }
        });
        jMenuServicos.add(jMenuItemSaldoProdutos);
        jMenuServicos.add(jSeparator9);

        jMenuItemExibirMovEstoque.setText("Exibir Movimentação de Estoque");
        jMenuItemExibirMovEstoque.setName("MOVIMENTAÇÃO DE ESTOQUE"); // NOI18N
        jMenuItemExibirMovEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExibirMovEstoqueActionPerformed(evt);
            }
        });
        jMenuServicos.add(jMenuItemExibirMovEstoque);

        jMenuBarPrincipal.add(jMenuServicos);

        jMenuFinanceiro.setMnemonic(KeyEvent.VK_F);
        jMenuFinanceiro.setText("Financeiro");
        jMenuFinanceiro.setMargin(new java.awt.Insets(0, 0, 0, 5));
        jMenuFinanceiro.setName("MENU FINANCEIRO"); // NOI18N

        jMenuItemBancos.setText("Bancos");
        jMenuItemBancos.setName("CADASTRAR BANCO"); // NOI18N
        jMenuItemBancos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBancosActionPerformed(evt);
            }
        });
        jMenuFinanceiro.add(jMenuItemBancos);

        jMenuItemAgencia.setText("Agência");
        jMenuItemAgencia.setName("CADASTRAR AGÊNCIA CONTA"); // NOI18N
        jMenuItemAgencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAgenciaActionPerformed(evt);
            }
        });
        jMenuFinanceiro.add(jMenuItemAgencia);

        jMenuItemContas.setText("Gerenciar Contas");
        jMenuItemContas.setName("CADASTRAR CONTAS PAGAR/RECEBER"); // NOI18N
        jMenuItemContas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemContasActionPerformed(evt);
            }
        });
        jMenuFinanceiro.add(jMenuItemContas);

        jMenuItemPagamento.setText("Realizar Pagamentos");
        jMenuItemPagamento.setName("REALIZAR PAGAMENTO"); // NOI18N
        jMenuItemPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPagamentoActionPerformed(evt);
            }
        });
        jMenuFinanceiro.add(jMenuItemPagamento);

        jMenuItemTransferencia.setText("Realizar Transferência entre Contas");
        jMenuItemTransferencia.setName("REALIZAR TRANSFERÊNCIA"); // NOI18N
        jMenuItemTransferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTransferenciaActionPerformed(evt);
            }
        });
        jMenuFinanceiro.add(jMenuItemTransferencia);

        jMenuItemGerenciarCheques.setText("Conciliação Bancária");
        jMenuItemGerenciarCheques.setName("CONCILIAÇÃO BANCÁRIA"); // NOI18N
        jMenuItemGerenciarCheques.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGerenciarChequesActionPerformed(evt);
            }
        });
        jMenuFinanceiro.add(jMenuItemGerenciarCheques);
        jMenuFinanceiro.add(jSeparator6);

        jMenuItemMovCaixa.setText("Consultar Movimentação de Caixa");
        jMenuItemMovCaixa.setName("MOVIMENTAÇÃO DE CAIXA"); // NOI18N
        jMenuItemMovCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMovCaixaActionPerformed(evt);
            }
        });
        jMenuFinanceiro.add(jMenuItemMovCaixa);
        jMenuFinanceiro.add(jSeparator8);

        jMenuItemFaturamento.setText("Consultar Faturamento");
        jMenuItemFaturamento.setName("CONSULTAR FATURAMENTO"); // NOI18N
        jMenuItemFaturamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFaturamentoActionPerformed(evt);
            }
        });
        jMenuFinanceiro.add(jMenuItemFaturamento);

        jMenuBarPrincipal.add(jMenuFinanceiro);

        jMenuUsuarios.setText("Configurações");
        jMenuUsuarios.setName("MENU CONFIGURAÇÕES"); // NOI18N

        jMenuItemGerenciarUsuarios.setText("Gerenciar Usuários");
        jMenuItemGerenciarUsuarios.setName("CADASTRAR USUÁRIOS"); // NOI18N
        jMenuItemGerenciarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGerenciarUsuariosActionPerformed(evt);
            }
        });
        jMenuUsuarios.add(jMenuItemGerenciarUsuarios);

        jMenuItemGerenciarNiveis.setText("Gerenciar Níveis de Acesso");
        jMenuItemGerenciarNiveis.setName("CADASTRAR NÍVEIS DE ACESSO"); // NOI18N
        jMenuItemGerenciarNiveis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGerenciarNiveisActionPerformed(evt);
            }
        });
        jMenuUsuarios.add(jMenuItemGerenciarNiveis);

        jMenuBarPrincipal.add(jMenuUsuarios);

        setJMenuBar(jMenuBarPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelImagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelSair, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                    .addComponent(jLabelAtual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelImagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCadMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadMesaActionPerformed
        new CadastroMesa().setVisible(true);
    }//GEN-LAST:event_jMenuItemCadMesaActionPerformed

    private void jMenuItemCadFamiliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadFamiliaActionPerformed
        new CadastroFamilia().setVisible(true);
    }//GEN-LAST:event_jMenuItemCadFamiliaActionPerformed

    private void jMenuItemBancosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBancosActionPerformed
        new CadastroBanco().setVisible(true);
    }//GEN-LAST:event_jMenuItemBancosActionPerformed

    private void jMenuItemAgenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAgenciaActionPerformed
        new CadastroAgenciaConta().setVisible(true);
    }//GEN-LAST:event_jMenuItemAgenciaActionPerformed

    private void jMenuItemCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadClienteActionPerformed
        new CadastroCliente().setVisible(true);
    }//GEN-LAST:event_jMenuItemCadClienteActionPerformed

    private void jMenuItemCadOrigemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadOrigemActionPerformed
        new CadastroOrigem().setVisible(true);
    }//GEN-LAST:event_jMenuItemCadOrigemActionPerformed

    private void jMenuItemCadProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadProdutoActionPerformed
        new CadastroProduto().setVisible(true);
    }//GEN-LAST:event_jMenuItemCadProdutoActionPerformed

    private void jMenuItemCadContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadContatoActionPerformed
        new CadastroContato().setVisible(true);
    }//GEN-LAST:event_jMenuItemCadContatoActionPerformed

    private void jMenuItemCadEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadEstadoActionPerformed
        new CadastroEstado().setVisible(true);
    }//GEN-LAST:event_jMenuItemCadEstadoActionPerformed

    private void jMenuItemCadCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadCidadeActionPerformed
        new CadastroCidade().setVisible(true);
    }//GEN-LAST:event_jMenuItemCadCidadeActionPerformed

    private void jMenuItemCadFormaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadFormaActionPerformed
        new CadastroFormadePagamento().setVisible(true);
    }//GEN-LAST:event_jMenuItemCadFormaActionPerformed

    private void jMenuItemCadTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadTipoActionPerformed
        new CadastroTipoPagamento().setVisible(true);
    }//GEN-LAST:event_jMenuItemCadTipoActionPerformed

    private void jMenuItemCadFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadFornecedorActionPerformed
        new CadastroFornecedor().setVisible(true);
    }//GEN-LAST:event_jMenuItemCadFornecedorActionPerformed

    private void jMenuItemCadFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadFuncionarioActionPerformed
        new CadastroFuncionario().setVisible(true);
    }//GEN-LAST:event_jMenuItemCadFuncionarioActionPerformed

    private void jMenuItemAtendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAtendimentoActionPerformed
        new TelaAtendimentoMesa().setVisible(true);
    }//GEN-LAST:event_jMenuItemAtendimentoActionPerformed

    private void jMenuItemContasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemContasActionPerformed
        new CadastroContas().setVisible(true);
    }//GEN-LAST:event_jMenuItemContasActionPerformed

    private void jMenuItemExibirAtendimentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExibirAtendimentosActionPerformed
        new TelaAtendimentos().setVisible(true);
    }//GEN-LAST:event_jMenuItemExibirAtendimentosActionPerformed

    private void jMenuItemPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPagamentoActionPerformed
        new TelaPagamento().setVisible(true);
    }//GEN-LAST:event_jMenuItemPagamentoActionPerformed

    private void jMenuItemMovCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMovCaixaActionPerformed
       new TelaMovCaixa().setVisible(true);
    }//GEN-LAST:event_jMenuItemMovCaixaActionPerformed

    private void jMenuItemFaturamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFaturamentoActionPerformed
        new Faturamento().setVisible(true);
    }//GEN-LAST:event_jMenuItemFaturamentoActionPerformed

    private void jMenuItemVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVendaActionPerformed
        new TelaVendaCompra().setVisible(true);
    }//GEN-LAST:event_jMenuItemVendaActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        new Avisos().removerAviso();
    }//GEN-LAST:event_formWindowClosing

    private void jMenuItemCadEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadEnderecoActionPerformed
        new CadastroEndereco().setVisible(true);
    }//GEN-LAST:event_jMenuItemCadEnderecoActionPerformed

    private void jMenuItemExibirMovEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExibirMovEstoqueActionPerformed
        new TelaMovEstoque().setVisible(true);
    }//GEN-LAST:event_jMenuItemExibirMovEstoqueActionPerformed

    private void jMenuItemTransferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTransferenciaActionPerformed
        new TelaTransferenciaContas().setVisible(true);
    }//GEN-LAST:event_jMenuItemTransferenciaActionPerformed

    private void jMenuItemExibirMesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExibirMesasActionPerformed
        new ExibirMesas().setVisible(true);
    }//GEN-LAST:event_jMenuItemExibirMesasActionPerformed

    private void jMenuItemSaldoProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSaldoProdutosActionPerformed
        new SaldoProdutos().setVisible(true);
    }//GEN-LAST:event_jMenuItemSaldoProdutosActionPerformed

    private void jMenuItemGerenciarChequesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGerenciarChequesActionPerformed
        new TelaConciliacaoBancaria().setVisible(true);
    }//GEN-LAST:event_jMenuItemGerenciarChequesActionPerformed

    private void jMenuItemGerenciarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGerenciarUsuariosActionPerformed
        new CadastroUsuario().setVisible(true);
    }//GEN-LAST:event_jMenuItemGerenciarUsuariosActionPerformed

    private void jMenuItemGerenciarNiveisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGerenciarNiveisActionPerformed
        new CadastroNivel().setVisible(true);
    }//GEN-LAST:event_jMenuItemGerenciarNiveisActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        validaUsuario.checarBarra(jMenuBarPrincipal, usuarioAtual);
        jLabelAtual.setText(usuarioAtual);
    }//GEN-LAST:event_formWindowActivated

    private void jLabelSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSairMouseClicked
        TelaLogin login = new TelaLogin(this, true);
        login.setVisible(true);
    }//GEN-LAST:event_jLabelSairMouseClicked

    private void jMenuItemCadOperacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadOperacaoActionPerformed
        new CadastroOperacao().setVisible(true);
    }//GEN-LAST:event_jMenuItemCadOperacaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAtual;
    private javax.swing.JLabel jLabelSair;
    private javax.swing.JMenuBar jMenuBarPrincipal;
    private javax.swing.JMenu jMenuCadastros;
    private javax.swing.JMenu jMenuFinanceiro;
    private javax.swing.JMenuItem jMenuItemAgencia;
    private javax.swing.JMenuItem jMenuItemAtendimento;
    private javax.swing.JMenuItem jMenuItemBancos;
    private javax.swing.JMenuItem jMenuItemCadCidade;
    private javax.swing.JMenuItem jMenuItemCadCliente;
    private javax.swing.JMenuItem jMenuItemCadContato;
    private javax.swing.JMenuItem jMenuItemCadEndereco;
    private javax.swing.JMenuItem jMenuItemCadEstado;
    private javax.swing.JMenuItem jMenuItemCadFamilia;
    private javax.swing.JMenuItem jMenuItemCadForma;
    private javax.swing.JMenuItem jMenuItemCadFornecedor;
    private javax.swing.JMenuItem jMenuItemCadFuncionario;
    private javax.swing.JMenuItem jMenuItemCadMesa;
    private javax.swing.JMenuItem jMenuItemCadOperacao;
    private javax.swing.JMenuItem jMenuItemCadOrigem;
    private javax.swing.JMenuItem jMenuItemCadProduto;
    private javax.swing.JMenuItem jMenuItemCadTipo;
    private javax.swing.JMenuItem jMenuItemContas;
    private javax.swing.JMenuItem jMenuItemExibirAtendimentos;
    private javax.swing.JMenuItem jMenuItemExibirMesas;
    private javax.swing.JMenuItem jMenuItemExibirMovEstoque;
    private javax.swing.JMenuItem jMenuItemFaturamento;
    private javax.swing.JMenuItem jMenuItemGerenciarCheques;
    private javax.swing.JMenuItem jMenuItemGerenciarNiveis;
    private javax.swing.JMenuItem jMenuItemGerenciarUsuarios;
    private javax.swing.JMenuItem jMenuItemMovCaixa;
    private javax.swing.JMenuItem jMenuItemPagamento;
    private javax.swing.JMenuItem jMenuItemSaldoProdutos;
    private javax.swing.JMenuItem jMenuItemTransferencia;
    private javax.swing.JMenuItem jMenuItemVenda;
    private javax.swing.JMenu jMenuServicos;
    private javax.swing.JMenu jMenuUsuarios;
    private javax.swing.JPanel jPanelImagem;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    // End of variables declaration//GEN-END:variables

    private void carregaImagem() {
        //Random aleatorio = new Random();
        String caminho = "Extras\\Imagens\\";
        //int nr = aleatorio.nextInt(4);
        ImageIcon img = new ImageIcon(caminho + 0 + ".jpg");
        
        int largura = img.getIconWidth();
        int altura = img.getIconHeight();

        JLabel labelimg = new JLabel(img);
        labelimg.setSize(largura, altura);
        
        jPanelImagem.add(labelimg, RIGHT_ALIGNMENT);
    }
    
    private void procuraAvisos(){
        new Avisos().verificaAvisos();
    }
}
