
package Consultas;

import Classes.Parcelas;
import Validacoes.MostrarDialogo;
import Validacoes.PreencherTabela;
import javax.swing.JOptionPane;

/**
 *
 * @author Leonardo
 */
public class ConsultaParcelas extends javax.swing.JFrame {

    
    Parcelas parcelas = new Parcelas();
    /**
     * Creates new form ConsultaParcelas
     */
    public ConsultaParcelas() {
        initComponents();
        parcelas.getContas().setCdConta(1);
        exibirParcelas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenuPagaParcela = new javax.swing.JPopupMenu();
        jMenuItemPagarParcela = new javax.swing.JMenuItem();
        jLabelTopo = new javax.swing.JLabel();
        jBtConfirmar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableParcelas = new javax.swing.JTable();
        jBtCancelar = new javax.swing.JButton();

        jMenuItemPagarParcela.setText("Pagar Parcela");
        jMenuItemPagarParcela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPagarParcelaActionPerformed(evt);
            }
        });
        jPopupMenuPagaParcela.add(jMenuItemPagarParcela);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Parcelas Geradas");
        setResizable(false);

        jLabelTopo.setText("          ");

        jBtConfirmar.setText("Confirmar ");
        jBtConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtConfirmarActionPerformed(evt);
            }
        });

        jTableParcelas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Conta", "Nr Parcela", "Valor", "Data Vencimento", "Valor Pago", "Data Pagamento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableParcelas.setComponentPopupMenu(jPopupMenuPagaParcela);
        jTableParcelas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableParcelasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableParcelas);

        jBtCancelar.setText("Cancelar");
        jBtCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelTopo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBtConfirmar)
                        .addGap(18, 18, 18)
                        .addComponent(jBtCancelar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTopo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtConfirmar)
                    .addComponent(jBtCancelar))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtConfirmarActionPerformed
        int opcao = JOptionPane.showConfirmDialog(null, "Deseja confirmar estas parcelas ?",
                "Confirmar Parcelas", JOptionPane.YES_NO_OPTION);
        if (opcao == JOptionPane.YES_OPTION){
            // altera as parcelas
            dispose();
        }
    }//GEN-LAST:event_jBtConfirmarActionPerformed

    private void jBtCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtCancelarActionPerformed
        int opcao = JOptionPane.showConfirmDialog(null, "Deseja voltar as parcelas para o estado anterior ?",
                "Voltar Parcelas", JOptionPane.YES_NO_OPTION);
        if (opcao == JOptionPane.YES_OPTION){
            exibirParcelas();
        }
    }//GEN-LAST:event_jBtCancelarActionPerformed

    private void jTableParcelasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableParcelasMouseClicked
        int linha = jTableParcelas.getSelectedRow();
        int coluna = jTableParcelas.getSelectedColumn();
        if (coluna == 3){
            String data = jTableParcelas.getValueAt(linha, coluna).toString();
            MostrarDialogo dialogo = new MostrarDialogo();
            String valor = dialogo.dialogoData(data);
            jTableParcelas.setValueAt(valor, linha, coluna);
        }
    }//GEN-LAST:event_jTableParcelasMouseClicked

    private void jMenuItemPagarParcelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPagarParcelaActionPerformed
        int linha = jTableParcelas.getSelectedRow();
        
    }//GEN-LAST:event_jMenuItemPagarParcelaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaParcelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaParcelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaParcelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaParcelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaParcelas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtCancelar;
    private javax.swing.JButton jBtConfirmar;
    private javax.swing.JLabel jLabelTopo;
    private javax.swing.JMenuItem jMenuItemPagarParcela;
    private javax.swing.JPopupMenu jPopupMenuPagaParcela;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableParcelas;
    // End of variables declaration//GEN-END:variables

    public void exibirParcelas(){
        PreencherTabela preencher = new PreencherTabela();
        preencher.FormatarJtable(jTableParcelas, new int[] {90,90,90,90,90,90});
        preencher.PreencherJtableGenerico(jTableParcelas, parcelas.consultarCdConta(parcelas.getContas()));
        
        jLabelTopo.setText("Parcelas da Conta "+parcelas.getContas().getCdConta()+": "+parcelas.getContas().getDsConta());
    }

}
