package Cadastros;

import Classes.Cliente;
import Consultas.ConsultaParcelas;
import Relatorios.Relatorios;
import Validacoes.LimparCampos;
import Validacoes.PreencherTabela;
import Validacoes.RetornaData;
import Validacoes.Rotinas;
import Validacoes.TeclasdeAtalho;
import Validacoes.ValidaBotoes;
import Validacoes.ValidaCampos;
import Validacoes.ValidaDocumentos;
import Validacoes.ValidaNivelUsuario;
import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Leonardo
 */
public class CadastroCliente extends javax.swing.JFrame {

    Cliente cliente = new Cliente();
    ValidaNivelUsuario valida = new ValidaNivelUsuario();
    Relatorios report = new Relatorios();

    LimparCampos limpar = new LimparCampos();
    ValidaBotoes botoes = new ValidaBotoes();
    ValidaCampos campos = new ValidaCampos();
    RetornaData dataAtual = new RetornaData();
    int rotina;

    ValidaDocumentos doc = new ValidaDocumentos();
    MaskFormatter data;
    MaskFormatter cep;
    MaskFormatter fone;

    TeclasdeAtalho atalho = new TeclasdeAtalho();
    /**
     * Creates new form CadastroCliente
     */
    public CadastroCliente() {
        initComponents();
        rotina = Rotinas.padrao;
        botoes.validaBotoes(jPanelBotoes, rotina);
        carregarUsuario();
        jRadioButtonFisicaActionPerformed(null);

        cliente.getPessoa().getEndereco().retornaComboCidade(jComboBoxCidade);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTipoPessoa = new javax.swing.ButtonGroup();
        jPopupMenuCliente = new javax.swing.JPopupMenu();
        jMenuItemCarregarDados = new javax.swing.JMenuItem();
        jMenuItemContatos = new javax.swing.JMenuItem();
        jMenuItemEndereco = new javax.swing.JMenuItem();
        jMenuItemParcelas = new javax.swing.JMenuItem();
        jTabbedPaneCliente = new javax.swing.JTabbedPane();
        atalho.adicionarAtalho(jTabbedPaneCliente);
        jPanelCadastro = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCdCliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jRadioButtonFisica = new javax.swing.JRadioButton();
        atalho.adicionarAtalho(jRadioButtonFisica, KeyEvent.VK_F, InputEvent.CTRL_DOWN_MASK);
        jRadioButtonJuridica = new javax.swing.JRadioButton();
        atalho.adicionarAtalho(jRadioButtonJuridica, KeyEvent.VK_J, InputEvent.CTRL_DOWN_MASK);
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldRG = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldRazao = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        try{       data = new MaskFormatter("##/##/####");   }   catch(Exception erro)   {   JOptionPane.showMessageDialog(null, "Não foi possivel localizar");   }
        jFormattedTextFieldData = new JFormattedTextField(data);
        jLabel9 = new javax.swing.JLabel();
        jTextFieldRua = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jComboBoxCidade = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldNrEndereco = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldBairro = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldComplemento = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jComboBoxSexo = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        jPanelBotoes = new javax.swing.JPanel();
        jBtIncluir = new javax.swing.JButton();
        atalho.adicionarAtalho(jBtIncluir, KeyEvent.VK_F1, 0);
        jBtAlterar = new javax.swing.JButton();
        atalho.adicionarAtalho(jBtAlterar, KeyEvent.VK_F2, 0);
        jBtExcluir = new javax.swing.JButton();
        atalho.adicionarAtalho(jBtExcluir, KeyEvent.VK_F3,0);
        jBtGravar = new javax.swing.JButton();
        atalho.adicionarAtalho(jBtGravar, KeyEvent.VK_ENTER, InputEvent.CTRL_DOWN_MASK);
        jBtCancelar = new javax.swing.JButton();
        atalho.adicionarAtalho(jBtCancelar, KeyEvent.VK_ESCAPE, 0);
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jComboBoxSituacao = new javax.swing.JComboBox();
        jBtCidade = new javax.swing.JButton();
        atalho.adicionarAtalho(jBtCidade, KeyEvent.VK_F4, 0);
        jBtContatos = new javax.swing.JButton();
        atalho.adicionarAtalho(jBtContatos, KeyEvent.VK_F7, 0);
        jBtEndereco = new javax.swing.JButton();
        atalho.adicionarAtalho(jBtEndereco, KeyEvent.VK_F8, 0);
        jFormattedTextFieldCpfCNPJ = new javax.swing.JFormattedTextField();
        try{       fone = new MaskFormatter("(##)-####-####");   }   catch(Exception erro)   {   JOptionPane.showMessageDialog(null, "Não foi possivel localizar");   }
        jFtextFieldFoneRes = new JFormattedTextField(fone);
        try{       fone = new MaskFormatter("(##)-####-####");   }   catch(Exception erro)   {   JOptionPane.showMessageDialog(null, "Não foi possivel localizar");   }
        jFTextFieldFoneCom = new JFormattedTextField(fone);
        try{       fone = new MaskFormatter("(##)-####-####");   }   catch(Exception erro)   {   JOptionPane.showMessageDialog(null, "Não foi possivel localizar");   }
        jFTextFieldFoneCel = new JFormattedTextField(fone);
        try{       cep = new MaskFormatter("#####-###");   }   catch(Exception erro)   {   JOptionPane.showMessageDialog(null, "Não foi possivel localizar");   }
        jFTextFieldCEP = new JFormattedTextField(cep);
        jPanelConsulta = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableConsulta = new javax.swing.JTable();
        jTableConsulta.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jLabel1 = new javax.swing.JLabel();
        jComboBoxConsulta = new javax.swing.JComboBox();
        jBtPesquisar = new javax.swing.JButton();
        atalho.adicionarAtalho(jBtPesquisar,
            KeyEvent.VK_F5, 0);
        jTextFieldConsulta = new javax.swing.JTextField();
        jBtRelatorio = new javax.swing.JButton();
        atalho.adicionarAtalho(jBtRelatorio, KeyEvent.VK_F6, 0);

        jPopupMenuCliente.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                jPopupMenuClientePopupMenuWillBecomeVisible(evt);
            }
        });

        jMenuItemCarregarDados.setText("Carregar Dados");
        jMenuItemCarregarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCarregarDadosActionPerformed(evt);
            }
        });
        jPopupMenuCliente.add(jMenuItemCarregarDados);

        jMenuItemContatos.setText("Exibir Contatos ...");
        jMenuItemContatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemContatosActionPerformed(evt);
            }
        });
        jPopupMenuCliente.add(jMenuItemContatos);

        jMenuItemEndereco.setText("Exibir Endereços ...");
        jMenuItemEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEnderecoActionPerformed(evt);
            }
        });
        jPopupMenuCliente.add(jMenuItemEndereco);

        jMenuItemParcelas.setText("Verificar Parcelas");
        jMenuItemParcelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemParcelasActionPerformed(evt);
            }
        });
        jPopupMenuCliente.add(jMenuItemParcelas);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Clientes");
        setName("CADASTRAR CLIENTES"); // NOI18N
        setResizable(false);

        jLabel2.setText("Código do Cliente");

        jTextFieldCdCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldCdClienteFocusLost(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(0, 102, 204));
        jLabel3.setText("Nome");

        jTextFieldNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNomeKeyTyped(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(0, 102, 204));
        jLabel4.setText("Tipo de Pessoa");

        buttonGroupTipoPessoa.add(jRadioButtonFisica);
        jRadioButtonFisica.setSelected(true);
        jRadioButtonFisica.setText("Pessoa Física");
        jRadioButtonFisica.setToolTipText("Pessoa Física (Ctrl + F)");
        jRadioButtonFisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonFisicaActionPerformed(evt);
            }
        });

        buttonGroupTipoPessoa.add(jRadioButtonJuridica);
        jRadioButtonJuridica.setText("Pessoa Jurídica");
        jRadioButtonJuridica.setToolTipText("Pessoa Jurídica (Ctrl + J)");
        jRadioButtonJuridica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonJuridicaActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(0, 102, 204));
        jLabel5.setText("CPF/CNPJ");

        jLabel6.setText("RG");

        jTextFieldRG.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldRGKeyTyped(evt);
            }
        });

        jLabel7.setText("Razão Social");

        jTextFieldRazao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldRazaoKeyTyped(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(0, 102, 204));
        jLabel8.setText("Data de Cadastro");

        jFormattedTextFieldData.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);

        jLabel9.setText("Rua Avenida");

        jTextFieldRua.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldRuaKeyTyped(evt);
            }
        });

        jLabel10.setText("CEP");

        jComboBoxCidade.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        jLabel11.setText("Cidade");

        jLabel12.setText("Nr Endereço");

        jTextFieldNrEndereco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNrEnderecoKeyTyped(evt);
            }
        });

        jLabel13.setText("Bairro");

        jTextFieldBairro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldBairroFocusLost(evt);
            }
        });
        jTextFieldBairro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldBairroKeyTyped(evt);
            }
        });

        jLabel14.setText("Complemento");

        jTextFieldComplemento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldComplementoKeyTyped(evt);
            }
        });

        jLabel15.setText("Email");

        jTextFieldEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldEmailKeyTyped(evt);
            }
        });

        jLabel16.setText("Fone Residencial");

        jLabel17.setText("Fone Celular");

        jLabel18.setText("Fone Comercial");

        jComboBoxSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MASCULINO", "FEMININO" }));

        jLabel19.setText("Sexo");

        jBtIncluir.setText("Incluir");
        jBtIncluir.setToolTipText("Incluir (F1)");
        jBtIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtIncluirActionPerformed(evt);
            }
        });

        jBtAlterar.setText("Alterar");
        jBtAlterar.setToolTipText("Alterar (F2)");
        jBtAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtAlterarActionPerformed(evt);
            }
        });

        jBtExcluir.setText("Excluir");
        jBtExcluir.setToolTipText("Excluir (F3)");
        jBtExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtExcluirActionPerformed(evt);
            }
        });

        jBtGravar.setText("Gravar");
        jBtGravar.setToolTipText("Gravar (Ctrl + Enter)");
        jBtGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtGravarActionPerformed(evt);
            }
        });

        jBtCancelar.setText("Cancelar");
        jBtCancelar.setToolTipText("Cancelar (Esc)");
        jBtCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtCancelarActionPerformed(evt);
            }
        });

        jLabel21.setForeground(new java.awt.Color(0, 102, 204));
        jLabel21.setText("- Campos Obrigatórios");

        javax.swing.GroupLayout jPanelBotoesLayout = new javax.swing.GroupLayout(jPanelBotoes);
        jPanelBotoes.setLayout(jPanelBotoesLayout);
        jPanelBotoesLayout.setHorizontalGroup(
            jPanelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel21)
                .addGap(40, 40, 40))
        );
        jPanelBotoesLayout.setVerticalGroup(
            jPanelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBotoesLayout.createSequentialGroup()
                .addGap(0, 27, Short.MAX_VALUE)
                .addGroup(jPanelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtIncluir)
                    .addComponent(jBtAlterar)
                    .addComponent(jBtExcluir)
                    .addComponent(jBtGravar)
                    .addComponent(jBtCancelar)
                    .addComponent(jLabel21)))
        );

        jLabel20.setForeground(new java.awt.Color(0, 102, 204));
        jLabel20.setText("Situação");

        jComboBoxSituacao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ATIVO", "INATIVO" }));

        jBtCidade.setText("Cidades...");
        jBtCidade.setToolTipText("Cidades (F4)");
        jBtCidade.setName("CADASTRAR CIDADE"); // NOI18N
        jBtCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtCidadeActionPerformed(evt);
            }
        });

        jBtContatos.setText("Contatos...");
        jBtContatos.setToolTipText("Contatos (F7)");
        jBtContatos.setName("CADASTRAR CONTATO"); // NOI18N
        jBtContatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtContatosActionPerformed(evt);
            }
        });

        jBtEndereco.setText("Endereço...");
        jBtEndereco.setToolTipText("Endereço (F8)");
        jBtEndereco.setName("CADASTRAR ENDEREÇO"); // NOI18N
        jBtEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtEnderecoActionPerformed(evt);
            }
        });

        jFormattedTextFieldCpfCNPJ.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);

        jFtextFieldFoneRes.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);

        jFTextFieldFoneCom.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);

        jFTextFieldFoneCel.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);

        jFTextFieldCEP.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);

        javax.swing.GroupLayout jPanelCadastroLayout = new javax.swing.GroupLayout(jPanelCadastro);
        jPanelCadastro.setLayout(jPanelCadastroLayout);
        jPanelCadastroLayout.setHorizontalGroup(
            jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelCadastroLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextFieldNrEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldRua, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jTextFieldBairro))
                    .addGroup(jPanelCadastroLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(29, 29, 29)
                                .addComponent(jLabel9))
                            .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelCadastroLayout.createSequentialGroup()
                                    .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelCadastroLayout.createSequentialGroup()
                                            .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jTextFieldComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel14))
                                            .addGap(33, 33, 33))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadastroLayout.createSequentialGroup()
                                            .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel16)
                                                .addComponent(jFtextFieldFoneRes, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(28, 28, 28)
                                            .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel18)
                                                .addComponent(jFTextFieldFoneCom, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(28, 28, 28)
                                            .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                                .addComponent(jFTextFieldFoneCel))
                                            .addGap(114, 114, 114)))
                                    .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldEmail)
                                        .addGroup(jPanelCadastroLayout.createSequentialGroup()
                                            .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel20)
                                                .addComponent(jLabel15)
                                                .addComponent(jLabel13)
                                                .addGroup(jPanelCadastroLayout.createSequentialGroup()
                                                    .addComponent(jComboBoxSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jBtContatos)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jBtEndereco)))
                                            .addGap(0, 1, Short.MAX_VALUE))))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelCadastroLayout.createSequentialGroup()
                                    .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jTextFieldNome, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanelCadastroLayout.createSequentialGroup()
                                                    .addComponent(jLabel2)
                                                    .addGap(87, 87, 87)
                                                    .addComponent(jLabel4))
                                                .addGroup(jPanelCadastroLayout.createSequentialGroup()
                                                    .addComponent(jTextFieldCdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(101, 101, 101)
                                                    .addComponent(jRadioButtonFisica)
                                                    .addGap(2, 2, 2)
                                                    .addComponent(jRadioButtonJuridica))
                                                .addGroup(jPanelCadastroLayout.createSequentialGroup()
                                                    .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel5)
                                                        .addComponent(jFormattedTextFieldCpfCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGap(27, 27, 27)
                                                    .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jTextFieldRG, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                    .addGap(33, 33, 33)
                                    .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelCadastroLayout.createSequentialGroup()
                                            .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel19)
                                                .addComponent(jComboBoxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel8)
                                                .addComponent(jFormattedTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(jTextFieldRazao)
                                        .addGroup(jPanelCadastroLayout.createSequentialGroup()
                                            .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanelCadastroLayout.createSequentialGroup()
                                                    .addComponent(jLabel11)
                                                    .addGap(127, 127, 127))
                                                .addGroup(jPanelCadastroLayout.createSequentialGroup()
                                                    .addComponent(jComboBoxCidade, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jBtCidade)
                                                    .addGap(18, 18, 18)))
                                            .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel10)
                                                .addComponent(jFTextFieldCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(jLabel7)))))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanelCadastroLayout.setVerticalGroup(
            jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastroLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel4)))
                        .addGap(3, 3, 3)
                        .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jTextFieldCdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jRadioButtonFisica)
                            .addComponent(jRadioButtonJuridica)))
                    .addGroup(jPanelCadastroLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)
                        .addGap(5, 5, 5)
                        .addComponent(jFormattedTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCadastroLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel19)
                        .addGap(6, 6, 6)
                        .addComponent(jComboBoxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastroLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jTextFieldRazao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanelCadastroLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)))
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastroLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)))
                    .addGroup(jPanelCadastroLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtCidade)
                    .addComponent(jFormattedTextFieldCpfCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFTextFieldCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(jLabel13)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNrEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addGap(6, 6, 6)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel18)
                    .addComponent(jLabel17)
                    .addComponent(jLabel20))
                .addGap(5, 5, 5)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFtextFieldFoneRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jFTextFieldFoneCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jFTextFieldFoneCel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtContatos)
                        .addComponent(jBtEndereco))
                    .addComponent(jComboBoxSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jPanelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPaneCliente.addTab("Cadastro", jPanelCadastro);

        jTableConsulta.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jTableConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Pessoa", "CPF/CNPJ", "Cidade", "Email", "Cadastro", "Situação"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableConsulta.setComponentPopupMenu(jPopupMenuCliente);
        jTableConsulta.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableConsulta);

        jLabel1.setText("Filtro da Consulta");

        jComboBoxConsulta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Geral", "Código", "Nome" }));
        jComboBoxConsulta.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBoxConsultaPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jBtPesquisar.setText("Pesquisar");
        jBtPesquisar.setToolTipText("Pesquisar (F5)");
        jBtPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtPesquisarActionPerformed(evt);
            }
        });

        jTextFieldConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldConsultaActionPerformed(evt);
            }
        });

        jBtRelatorio.setText("Relatório");
        jBtRelatorio.setToolTipText("Relatório (F6)");
        jBtRelatorio.setEnabled(false);
        jBtRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtRelatorioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelConsultaLayout = new javax.swing.GroupLayout(jPanelConsulta);
        jPanelConsulta.setLayout(jPanelConsultaLayout);
        jPanelConsultaLayout.setHorizontalGroup(
            jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 825, Short.MAX_VALUE)
                    .addGroup(jPanelConsultaLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelConsultaLayout.createSequentialGroup()
                        .addComponent(jComboBoxConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldConsulta)
                        .addGap(18, 18, 18)
                        .addComponent(jBtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBtRelatorio)))
                .addContainerGap())
        );
        jPanelConsultaLayout.setVerticalGroup(
            jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(8, 8, 8)
                .addGroup(jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtPesquisar)
                    .addComponent(jBtRelatorio))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPaneCliente.addTab("Consulta", jPanelConsulta);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jTabbedPaneCliente, javax.swing.GroupLayout.Alignment.TRAILING))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 454, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jTabbedPaneCliente, javax.swing.GroupLayout.Alignment.TRAILING))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtIncluirActionPerformed
        limpar.limparCampos(jPanelCadastro);
        jTextFieldNome.grabFocus();
        rotina = Rotinas.incluir;
        botoes.validaBotoes(jPanelBotoes, rotina);
        carregarUsuario();
        jFormattedTextFieldData.setText(dataAtual.retornaDataAtual());
        jRadioButtonFisica.setSelected(true);
        jRadioButtonFisicaActionPerformed(null);
    }//GEN-LAST:event_jBtIncluirActionPerformed

    private void jBtAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtAlterarActionPerformed
        rotina = Rotinas.alterar;
        jTextFieldNome.grabFocus();
        botoes.validaBotoes(jPanelBotoes, rotina);
        carregarUsuario();
    }//GEN-LAST:event_jBtAlterarActionPerformed

    private void jBtExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtExcluirActionPerformed
        if (jTextFieldCdCliente.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "É preciso informar o código do cliente que deseja excluir!");
            jTextFieldCdCliente.grabFocus();
        } else {
            try {
                cliente.setCdCliente(Integer.parseInt(jTextFieldCdCliente.getText()));
                cliente.retornaCliente(cliente);
                if (cliente.getInAtivo().equals("INATIVO")){
                    JOptionPane.showMessageDialog(null, "Este cliente já está inativo!");
                }
                else if (cliente.parcelasAPagar(cliente)){
                    JOptionPane.showMessageDialog(null, "Este cliente possui parcelas a serem pagas, não pode ser inativado!");
                }
                else{
                    int delete = JOptionPane.showConfirmDialog(null, "Deseja realmente inativar este cliente ?",
                        "Inativar Cliente", JOptionPane.YES_OPTION);
                    if (delete == JOptionPane.YES_OPTION) {
                        cliente.excluir(cliente);
                        //JOptionPane.showMessageDialog(null, "Cliente inativado com sucesso!");
                        limpar.limparCampos(jPanelCadastro);
                    }
                }
            } 
            catch (NumberFormatException ex) {
            
            }
        }
        rotina = Rotinas.excluir;
        botoes.validaBotoes(jPanelBotoes, rotina);
        carregarUsuario();
    }//GEN-LAST:event_jBtExcluirActionPerformed

    private void jBtGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtGravarActionPerformed
        if (jTextFieldNome.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "O nome do cliente é obrigatório!");
            jTextFieldNome.grabFocus();
        } 
        
        else if (jFormattedTextFieldCpfCNPJ.getText().equals("   .   .   -  ")
                || jFormattedTextFieldCpfCNPJ.getText().equals("  .   .   /    -  ")) {
            JOptionPane.showMessageDialog(null, "O CPF/CNPJ do cliente é obrigatório!");
            jFormattedTextFieldCpfCNPJ.grabFocus();
        } 
        
        else if (rotina == Rotinas.incluir && !doc.validaCPFCNPJ(jFormattedTextFieldCpfCNPJ.getText())) {
            JOptionPane.showMessageDialog(null, "CPF/CNPJ inválido!");
            jFormattedTextFieldCpfCNPJ.grabFocus();
        } 
        
        else if (rotina == Rotinas.alterar && jRadioButtonFisica.isSelected()
                && !doc.validaCPF(doc.removeMascara(jFormattedTextFieldCpfCNPJ.getText()))) {
            JOptionPane.showMessageDialog(null, "CPF inválido!");
            jFormattedTextFieldCpfCNPJ.grabFocus();
        } 
        
        else if (rotina == Rotinas.alterar && jRadioButtonJuridica.isSelected()
                && !doc.validaCNPJ(doc.removeMascara(jFormattedTextFieldCpfCNPJ.getText()))) {
            JOptionPane.showMessageDialog(null, "CNPJ inválido!");
            jFormattedTextFieldCpfCNPJ.grabFocus();
        } 
        
        else if ((dataAtual.comparaData(jFormattedTextFieldData.getText()) > 0) 
            ||!dataAtual.dataExiste(jFormattedTextFieldData.getText())){
            JOptionPane.showMessageDialog(null, "Por favor informe uma data válida!");
        }
        
        else if (!campos.CEPValido(jFTextFieldCEP)){
            JOptionPane.showMessageDialog(null, "Por favor preencha completamente o CEP ou mantenha-o vazio!");
        }
        
        else if (!campos.fonesValidos(jFtextFieldFoneRes, jFTextFieldFoneCom, jFTextFieldFoneCel)){
            JOptionPane.showMessageDialog(null, "Por favor preencha completamente o(s) telefone(s)"
                    + " ou mantenha-o(s) vazio(s)!");
        }
        
        else {
            gravarCliente();
            gravarEndereco();
            gravarContato();

            if (rotina == Rotinas.incluir) {
                cliente.incluir(cliente);
                //JOptionPane.showMessageDialog(null, "Cliente gravado com sucesso!");
                jTextFieldCdCliente.setText(cliente.getPessoa().getCdPessoa().toString());
            } else if (rotina == Rotinas.alterar) {
                if (jTextFieldCdCliente.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "É preciso informar o código do cliente que deseja alterar!");
                    jTextFieldCdCliente.grabFocus();
                } else {
                    try {
                        cliente.setCdCliente(Integer.parseInt(jTextFieldCdCliente.getText()));
                        cliente.alterar(cliente);
                        //JOptionPane.showMessageDialog(null, "Cliente alterado com sucesso!");
                    } catch (NumberFormatException ex) {
                    }
                }
            }
            rotina = Rotinas.padrao;
            botoes.validaBotoes(jPanelBotoes, rotina);
            carregarUsuario();
        }
    }//GEN-LAST:event_jBtGravarActionPerformed

    private void jBtPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtPesquisarActionPerformed
        PreencherTabela preencher = new PreencherTabela();
        preencher.FormatarJtable(jTableConsulta, new int[]{40, 180, 45, 100, 120, 180, 60, 40});

        switch (jComboBoxConsulta.getSelectedIndex()) {
            case 0:
                preencher.PreencherJtableGenerico(jTableConsulta, cliente.consultarGeral(true));
                report.setConsulta(preencher.getConsulta());
                editaBotao(preencher.Vazia());
            break;

            case 1:
                try {
                    cliente.setCdCliente(Integer.parseInt(jTextFieldConsulta.getText()));
                    preencher.PreencherJtableGenerico(jTableConsulta, cliente.consultarCdCliente(cliente, true));
                    report.setConsulta(preencher.getConsulta());
                    editaBotao(preencher.Vazia());
                } 
                catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(null, "Por favor informe um código para pesquisar!");
                    editaBotao(true);
                }
            break;

            default:
                cliente.getPessoa().setNome(jTextFieldConsulta.getText().toUpperCase());
                preencher.PreencherJtableGenerico(jTableConsulta, cliente.consultarNomeCliente(cliente, true));
                report.setConsulta(preencher.getConsulta());
                editaBotao(preencher.Vazia());
            break;
        }
    }//GEN-LAST:event_jBtPesquisarActionPerformed

    private void jRadioButtonFisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonFisicaActionPerformed
        jComboBoxSexo.setEnabled(true);
        jTextFieldRG.setEnabled(true);
        jTextFieldRazao.setEnabled(false);

        jFormattedTextFieldCpfCNPJ.setFormatterFactory(null);
        MaskFormatter formato = null;
        try {
            formato = new MaskFormatter("###.###.###-##");
        } catch (ParseException ex) {
            Logger.getLogger(CadastroCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        jFormattedTextFieldCpfCNPJ.setFormatterFactory(new DefaultFormatterFactory(formato));
        jFormattedTextFieldCpfCNPJ.setValue(null);
    }//GEN-LAST:event_jRadioButtonFisicaActionPerformed

    private void jRadioButtonJuridicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonJuridicaActionPerformed
        jComboBoxSexo.setEnabled(false);
        jTextFieldRG.setEnabled(false);
        jTextFieldRazao.setEnabled(true);

        jFormattedTextFieldCpfCNPJ.setFormatterFactory(null);
        MaskFormatter formato = null;
        try {
            formato = new MaskFormatter("##.###.###/####-##");
        } catch (ParseException ex) {
            Logger.getLogger(CadastroCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        jFormattedTextFieldCpfCNPJ.setFormatterFactory(new DefaultFormatterFactory(formato));
        jFormattedTextFieldCpfCNPJ.setValue(null);
    }//GEN-LAST:event_jRadioButtonJuridicaActionPerformed

    private void jTextFieldNrEnderecoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNrEnderecoKeyTyped
        campos.validaCamposLimite(evt, jTextFieldNrEndereco, 6);
    }//GEN-LAST:event_jTextFieldNrEnderecoKeyTyped

    private void jBtCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtCancelarActionPerformed
        rotina = Rotinas.padrao;
        botoes.validaBotoes(jPanelBotoes, rotina);
        carregarUsuario();
        limpar.limparCampos(jPanelCadastro);
        jTextFieldCdCliente.grabFocus();
        jRadioButtonFisica.setSelected(true);
        jRadioButtonFisicaActionPerformed(null);
    }//GEN-LAST:event_jBtCancelarActionPerformed

    private void jBtCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtCidadeActionPerformed
        CadastroCidade cadCidade = new CadastroCidade();
        cadCidade.setVisible(true);

        cadCidade.addWindowListener(new WindowAdapter() {
            public void windowClosed(WindowEvent evento) {
                cliente.getPessoa().getEndereco().retornaComboCidade(jComboBoxCidade);
            }
        });
    }//GEN-LAST:event_jBtCidadeActionPerformed

    private void jTextFieldCdClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCdClienteFocusLost
        if (!jTextFieldCdCliente.getText().equals("")) {
            try {
                cliente.setCdCliente(Integer.parseInt(jTextFieldCdCliente.getText()));
                cliente.retornaCliente(cliente);

                if (cliente.getPessoa().getNome().equals("")) {
                    jBtCancelarActionPerformed(null);
                } else {
                    preencherCampos();
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Por favor informe um código!");
                jBtCancelarActionPerformed(null);
            }
        }
    }//GEN-LAST:event_jTextFieldCdClienteFocusLost

    private void jMenuItemCarregarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCarregarDadosActionPerformed
        int linha = jTableConsulta.getSelectedRow();

        if (linha >= 0) {
            int cd = Integer.parseInt(jTableConsulta.getValueAt(linha, 0).toString());
            cliente.setCdCliente(cd);
            cliente.retornaCliente(cliente);

            limpar.limparCampos(jPanelCadastro);
            preencherCampos();
            jTabbedPaneCliente.setSelectedIndex(0);

            rotina = Rotinas.padrao;
            botoes.validaBotoes(jPanelBotoes, rotina);
            carregarUsuario();
        }
    }//GEN-LAST:event_jMenuItemCarregarDadosActionPerformed

    private void jTextFieldNomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNomeKeyTyped
        campos.validaCamposLimite(evt, jTextFieldNome, 60);
    }//GEN-LAST:event_jTextFieldNomeKeyTyped

    private void jTextFieldRazaoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldRazaoKeyTyped
        campos.validaCamposLimite(evt, jTextFieldRazao, 60);
    }//GEN-LAST:event_jTextFieldRazaoKeyTyped

    private void jTextFieldRuaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldRuaKeyTyped
        campos.validaCamposLimite(evt, jTextFieldRua, 50);
    }//GEN-LAST:event_jTextFieldRuaKeyTyped

    private void jTextFieldBairroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldBairroFocusLost

    }//GEN-LAST:event_jTextFieldBairroFocusLost

    private void jTextFieldBairroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBairroKeyTyped
        campos.validaCamposLimite(evt, jTextFieldBairro, 50);
    }//GEN-LAST:event_jTextFieldBairroKeyTyped

    private void jTextFieldComplementoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldComplementoKeyTyped
        campos.validaCamposLimite(evt, jTextFieldComplemento, 50);
    }//GEN-LAST:event_jTextFieldComplementoKeyTyped

    private void jTextFieldEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEmailKeyTyped
        campos.validaCamposLimite(evt, jTextFieldEmail, 40);
    }//GEN-LAST:event_jTextFieldEmailKeyTyped

    private void jTextFieldConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldConsultaActionPerformed

    private void jBtContatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtContatosActionPerformed
        CadastroContato cadContato = new CadastroContato();
        cadContato.setVisible(true);
        try {
            cliente.getPessoa().setCdPessoa(Integer.parseInt(jTextFieldCdCliente.getText()));
            cadContato.getValores();
        } catch (NumberFormatException ex) {

        }
    }//GEN-LAST:event_jBtContatosActionPerformed

    private void jBtEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtEnderecoActionPerformed
        CadastroEndereco cadEndereco = new CadastroEndereco();
        cadEndereco.setVisible(true);
        try {
            cliente.getPessoa().setCdPessoa(Integer.parseInt(jTextFieldCdCliente.getText()));
            cadEndereco.getValores();
        } catch (NumberFormatException ex) {

        }
    }//GEN-LAST:event_jBtEnderecoActionPerformed

    private void jMenuItemContatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemContatosActionPerformed
        int linha = jTableConsulta.getSelectedRow();
        if (linha >= 0) {

            int cd = Integer.parseInt(jTableConsulta.getValueAt(linha, 0).toString());
            cliente.getPessoa().setCdPessoa(cd);
            CadastroContato cadContato = new CadastroContato();
            cadContato.setVisible(true);

            cadContato.chamaConsulta();
        }
    }//GEN-LAST:event_jMenuItemContatosActionPerformed

    private void jMenuItemEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEnderecoActionPerformed
        int linha = jTableConsulta.getSelectedRow();
        if (linha >= 0) {

            int cd = Integer.parseInt(jTableConsulta.getValueAt(linha, 0).toString());
            cliente.getPessoa().setCdPessoa(cd);
            CadastroEndereco cadEndereco = new CadastroEndereco();
            cadEndereco.setVisible(true);

            cadEndereco.chamaConsulta();
        }
    }//GEN-LAST:event_jMenuItemEnderecoActionPerformed

    private void jMenuItemParcelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemParcelasActionPerformed
        int linha = jTableConsulta.getSelectedRow();
        if (linha >= 0){
            int cd = Integer.parseInt(jTableConsulta.getValueAt(linha, 0).toString());
            String nome = jTableConsulta.getValueAt(linha, 1).toString();
            ConsultaParcelas consulta = new ConsultaParcelas();
            consulta.setVisible(true);
            consulta.exibirParcelasPessoa(cd, nome);
        }
    }//GEN-LAST:event_jMenuItemParcelasActionPerformed

    private void jBtRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtRelatorioActionPerformed
        jBtPesquisarActionPerformed(null);
        report.setSubreport(true);
        report.setTabela("CLIENTE");
        report.iniciarSplash(report);
    }//GEN-LAST:event_jBtRelatorioActionPerformed

    private void jTextFieldRGKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldRGKeyTyped
        campos.validaCamposLimite(evt, jTextFieldRG, 12);
    }//GEN-LAST:event_jTextFieldRGKeyTyped

    private void jComboBoxConsultaPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBoxConsultaPopupMenuWillBecomeInvisible
        switch (jComboBoxConsulta.getSelectedIndex()) {
            case 0:
                jTextFieldConsulta.setText("");
                jTextFieldConsulta.setEnabled(false);
            break;

            default:
                jTextFieldConsulta.setEnabled(true);
                jTextFieldConsulta.setText("");
                jTextFieldConsulta.grabFocus();
            break;
        }
    }//GEN-LAST:event_jComboBoxConsultaPopupMenuWillBecomeInvisible

    private void jPopupMenuClientePopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jPopupMenuClientePopupMenuWillBecomeVisible
        jMenuItemContatos.setEnabled(valida.validaBotaoCadastro("CADASTRAR CONTATO"));
        jMenuItemEndereco.setEnabled(valida.validaBotaoCadastro("CADASTRAR ENDEREÇO"));
    }//GEN-LAST:event_jPopupMenuClientePopupMenuWillBecomeVisible

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupTipoPessoa;
    private javax.swing.JButton jBtAlterar;
    private javax.swing.JButton jBtCancelar;
    private javax.swing.JButton jBtCidade;
    private javax.swing.JButton jBtContatos;
    private javax.swing.JButton jBtEndereco;
    private javax.swing.JButton jBtExcluir;
    private javax.swing.JButton jBtGravar;
    private javax.swing.JButton jBtIncluir;
    private javax.swing.JButton jBtPesquisar;
    private javax.swing.JButton jBtRelatorio;
    private javax.swing.JComboBox jComboBoxCidade;
    private javax.swing.JComboBox jComboBoxConsulta;
    private javax.swing.JComboBox jComboBoxSexo;
    private javax.swing.JComboBox jComboBoxSituacao;
    private javax.swing.JFormattedTextField jFTextFieldCEP;
    private javax.swing.JFormattedTextField jFTextFieldFoneCel;
    private javax.swing.JFormattedTextField jFTextFieldFoneCom;
    private javax.swing.JFormattedTextField jFormattedTextFieldCpfCNPJ;
    private javax.swing.JFormattedTextField jFormattedTextFieldData;
    private javax.swing.JFormattedTextField jFtextFieldFoneRes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItemCarregarDados;
    private javax.swing.JMenuItem jMenuItemContatos;
    private javax.swing.JMenuItem jMenuItemEndereco;
    private javax.swing.JMenuItem jMenuItemParcelas;
    private javax.swing.JPanel jPanelBotoes;
    private javax.swing.JPanel jPanelCadastro;
    private javax.swing.JPanel jPanelConsulta;
    private javax.swing.JPopupMenu jPopupMenuCliente;
    private javax.swing.JRadioButton jRadioButtonFisica;
    private javax.swing.JRadioButton jRadioButtonJuridica;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPaneCliente;
    private javax.swing.JTable jTableConsulta;
    private javax.swing.JTextField jTextFieldBairro;
    private javax.swing.JTextField jTextFieldCdCliente;
    private javax.swing.JTextField jTextFieldComplemento;
    private javax.swing.JTextField jTextFieldConsulta;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldNrEndereco;
    private javax.swing.JTextField jTextFieldRG;
    private javax.swing.JTextField jTextFieldRazao;
    private javax.swing.JTextField jTextFieldRua;
    // End of variables declaration//GEN-END:variables

    private void gravarCliente() {
        cliente.getPessoa().setNome(jTextFieldNome.getText().toUpperCase());

        cliente.setDtCadastro(jFormattedTextFieldData.getText());
        if (jComboBoxSituacao.getSelectedIndex() == 0) {
            cliente.setInAtivo("A");
        } else {
            cliente.setInAtivo("I");
        }
        if (jRadioButtonFisica.isSelected()) {
            gravarClienteFisico();
        } else {
            gravarClienteJuridico();
        }
        cliente.getPessoa().setDtCadastro(cliente.getDtCadastro());
        cliente.getPessoa().setInAtivo(cliente.getInAtivo());
    }

    private void gravarClienteFisico() {
        cliente.getPessoa().setTpPessoa("F");
        cliente.getPessoa().getPfisica().setCPF(jFormattedTextFieldCpfCNPJ.getText());
        cliente.getPessoa().getPfisica().setRG(jTextFieldRG.getText());

        if (jComboBoxSexo.getSelectedIndex() == 0) {
            cliente.getPessoa().getPfisica().setSexo("M");
        } else {
            cliente.getPessoa().getPfisica().setSexo("F");
        }
    }

    private void gravarClienteJuridico() {
        cliente.getPessoa().setTpPessoa("J");
        cliente.getPessoa().getPjuridica().setCNPJ(jFormattedTextFieldCpfCNPJ.getText());
        cliente.getPessoa().getPjuridica().setRazao(jTextFieldRazao.getText());
    }

    private void gravarEndereco() {
        cliente.getPessoa().getEndereco().getCidade().setCdCidade(jComboBoxCidade.getSelectedIndex());
        cliente.getPessoa().getEndereco().setRuaAv(jTextFieldRua.getText().toUpperCase());
        cliente.getPessoa().getEndereco().setNrEndereco(jTextFieldNrEndereco.getText());
        cliente.getPessoa().getEndereco().setNrSequencia(1);
        cliente.getPessoa().getEndereco().setCEP(jFTextFieldCEP.getText());
        cliente.getPessoa().getEndereco().setBairro(jTextFieldBairro.getText().toUpperCase());
        cliente.getPessoa().getEndereco().setComplemento(jTextFieldComplemento.getText().toUpperCase());
    }

    private void gravarContato() {
        cliente.getPessoa().getContato().setEmail(jTextFieldEmail.getText().toUpperCase());
        cliente.getPessoa().getContato().setNrSeq(1);
        cliente.getPessoa().getContato().setNomeContato(jTextFieldNome.getText().toUpperCase());
        preencheFones();
    }

    private void preencherCampos() {
        jTextFieldCdCliente.setText(cliente.getPessoa().getCdPessoa().toString());
        jTextFieldNome.setText(cliente.getPessoa().getNome());
        jFormattedTextFieldData.setText(cliente.getDtCadastro());
        jComboBoxSituacao.setSelectedItem(cliente.getInAtivo());

        jComboBoxCidade.setSelectedItem(cliente.getPessoa().getEndereco().getCidade().getDsCidade());

        jFTextFieldCEP.setText(cliente.getPessoa().getEndereco().getCEP());
        jTextFieldNrEndereco.setText(cliente.getPessoa().getEndereco().getNrEndereco());
        jTextFieldRua.setText(cliente.getPessoa().getEndereco().getRuaAv());
        jTextFieldBairro.setText(cliente.getPessoa().getEndereco().getBairro());
        jTextFieldComplemento.setText(cliente.getPessoa().getEndereco().getComplemento());

        jTextFieldEmail.setText(cliente.getPessoa().getContato().getEmail());
        jFtextFieldFoneRes.setText(cliente.getPessoa().getContato().getFoneRes());
        jFTextFieldFoneCom.setText(cliente.getPessoa().getContato().getFoneCom());
        jFTextFieldFoneCel.setText(cliente.getPessoa().getContato().getFoneCel());

        if (cliente.getPessoa().getTpPessoa().equals("F")) {
            jRadioButtonFisica.setSelected(true);
            jRadioButtonFisicaActionPerformed(null);
            jComboBoxSexo.setSelectedItem(cliente.getPessoa().getPfisica().getSexo());
            jFormattedTextFieldCpfCNPJ.setText(cliente.getPessoa().getPfisica().getCPF());
            jTextFieldRG.setText(cliente.getPessoa().getPfisica().getRG());
        } else {
            jRadioButtonJuridica.setSelected(true);
            jRadioButtonJuridicaActionPerformed(null);
            jFormattedTextFieldCpfCNPJ.setText(cliente.getPessoa().getPjuridica().getCNPJ());
            jTextFieldRazao.setText(cliente.getPessoa().getPjuridica().getRazao());
        }
    }

    private void preencheFones() {
        if (jFtextFieldFoneRes.getText().equals("(  )-    -    ")) {
            cliente.getPessoa().getContato().setFoneRes("");
        } else {
            cliente.getPessoa().getContato().setFoneRes(jFtextFieldFoneRes.getText());
        }

        if (jFTextFieldFoneCom.getText().equals("(  )-    -    ")) {
            cliente.getPessoa().getContato().setFoneCom("");
        } else {
            cliente.getPessoa().getContato().setFoneCom(jFTextFieldFoneCom.getText());
        }

        if (jFTextFieldFoneCel.getText().equals("(  )-    -    ")) {
            cliente.getPessoa().getContato().setFoneCel("");
        } else {
            cliente.getPessoa().getContato().setFoneCel(jFTextFieldFoneCel.getText());
        }
    }
    
    private void editaBotao(boolean vazia) {
        if (vazia) {
            JOptionPane.showMessageDialog(null, "A consulta não encontrou resultados!");
            jBtRelatorio.setEnabled(false);
            jTextFieldConsulta.setText("");
            jTextFieldConsulta.grabFocus();
        } else {
            jBtRelatorio.setEnabled(valida.pRelatorio.equals("S"));
        }
    }
    
    private void carregarUsuario(){
        valida.validaNivel(this.getName());
        valida.validaBotoesUsuario(jPanelBotoes);
        jBtCidade.setEnabled(valida.validaBotaoCadastro("CADASTRAR CIDADE"));
        jBtEndereco.setEnabled(valida.validaBotaoCadastro("CADASTRAR ENDEREÇO"));
        jBtContatos.setEnabled(valida.validaBotaoCadastro("CADASTRAR CONTATO"));
    }
}
