package Cadastros;

import Classes.Fornecedor;
import Relatorios.Relatorios;
import Validacoes.LimparCampos;
import Validacoes.PreencherTabela;
import Validacoes.RetornaData;
import Validacoes.Rotinas;
import Validacoes.TeclasdeAtalho;
import Validacoes.ValidaBotoes;
import Validacoes.ValidaCampos;
import Validacoes.ValidaDocumentos;
import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Leonardo
 */
public class CadastroFornecedor extends javax.swing.JFrame {

    Fornecedor fornecedor = new Fornecedor();
    Relatorios report = new Relatorios();

    LimparCampos limpar = new LimparCampos();
    ValidaBotoes botoes = new ValidaBotoes();
    ValidaCampos campos = new ValidaCampos();
    RetornaData dataAtual = new RetornaData();
    int rotina;

    ValidaDocumentos doc = new ValidaDocumentos();
    MaskFormatter data;
    MaskFormatter cep;
    MaskFormatter fone;
    MaskFormatter cpfCnpj;
    TeclasdeAtalho atalho = new TeclasdeAtalho();

    /**
     * Creates new form CadastroFornecedor
     */
    public CadastroFornecedor() {
        initComponents();

        rotina = Rotinas.padrao;
        botoes.validaBotoes(jPanelBotoes, rotina);

        jRadioButtonPfisicaActionPerformed(null);

        fornecedor.getPessoa().getEndereco().retornaComboCidade(jComboBoxCidade);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTipoPessoa = new javax.swing.ButtonGroup();
        jPopupMenuFornecedor = new javax.swing.JPopupMenu();
        jMenuItemCarregaDados = new javax.swing.JMenuItem();
        jMenuItemContatos = new javax.swing.JMenuItem();
        jMenuItemEndereco = new javax.swing.JMenuItem();
        jTabbedPaneFornecedor = new javax.swing.JTabbedPane();
        atalho.adicionarAtalho(jTabbedPaneFornecedor);
        jPanelCadastro = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCdFornecedor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jRadioButtonPfisica = new javax.swing.JRadioButton();
        atalho.adicionarAtalho(jRadioButtonPfisica, 
            KeyEvent.VK_F, InputEvent.CTRL_DOWN_MASK);
        jRadioButtonPJuridica = new javax.swing.JRadioButton();
        atalho.adicionarAtalho(jRadioButtonPJuridica,
            KeyEvent.VK_J, InputEvent.CTRL_DOWN_MASK);
        jLabel6 = new javax.swing.JLabel();
        jComboBoxSexo = new javax.swing.JComboBox();
        try{       data = new MaskFormatter("##/##/####");   }   catch(Exception erro)   {   JOptionPane.showMessageDialog(null, "Não foi possivel localizar");   }
        jFormattedTextFieldDataCadastro = new JFormattedTextField(data);
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldRazao = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldRG = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jComboBoxCidade = new javax.swing.JComboBox();
        jBtCidades = new javax.swing.JButton();
        atalho.adicionarAtalho(jBtCidades, KeyEvent.VK_F4, 0);
        try{       cep = new MaskFormatter("#####-###");   }   catch(Exception erro)   {   JOptionPane.showMessageDialog(null, "Não foi possivel localizar");   }
        jTextFieldCEP = new JFormattedTextField(cep);
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldNrEndereco = new javax.swing.JTextField();
        jTextFieldRua = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldBairro = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldComplemento = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        try{       fone = new MaskFormatter("(##)-####-####");   }   catch(Exception erro)   {   JOptionPane.showMessageDialog(null, "Não foi possivel localizar");   }
        jTextFieldFoneRes = new JFormattedTextField(fone);
        try{       fone = new MaskFormatter("(##)-####-####");   }   catch(Exception erro)   {   JOptionPane.showMessageDialog(null, "Não foi possivel localizar");   }
        jTextFieldFoneCom = new JFormattedTextField(fone);
        try{       fone = new MaskFormatter("(##)-####-####");   }   catch(Exception erro)   {   JOptionPane.showMessageDialog(null, "Não foi possivel localizar");   }
        jTextFieldFoneCel = new JFormattedTextField(fone);
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jComboBoxSituacao = new javax.swing.JComboBox();
        jLabel20 = new javax.swing.JLabel();
        jPanelBotoes = new javax.swing.JPanel();
        jBtIncluir = new javax.swing.JButton();
        atalho.adicionarAtalho(jBtIncluir, KeyEvent.VK_F1, 0);
        jBtExcluir = new javax.swing.JButton();
        atalho. adicionarAtalho(jBtExcluir, KeyEvent.VK_F3, 0);
        jBtAlterar = new javax.swing.JButton();
        atalho.adicionarAtalho(jBtAlterar, KeyEvent.VK_F2, 0);
        jBtGravar = new javax.swing.JButton();
        atalho.adicionarAtalho(jBtGravar, KeyEvent.VK_ENTER, 0);
        jBtCancelar = new javax.swing.JButton();
        atalho.adicionarAtalho(jBtCancelar, KeyEvent.VK_ESCAPE, 0);
        jBtContatos = new javax.swing.JButton();
        atalho.adicionarAtalho(jBtContatos, KeyEvent.VK_F7, 0);
        jBtEndereco = new javax.swing.JButton();
        jFormattedTextFieldCpfCnpj = new javax.swing.JFormattedTextField();
        jPanelConsulta = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableConsulta = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxConsulta = new javax.swing.JComboBox();
        jBtPesquisar = new javax.swing.JButton();
        atalho.adicionarAtalho(jBtPesquisar, KeyEvent.VK_F5, 0);
        jTextFieldConsulta = new javax.swing.JTextField();
        jBtRelatorio = new javax.swing.JButton();
        atalho.adicionarAtalho(jBtRelatorio,   KeyEvent.VK_F6, 0);

        jMenuItemCarregaDados.setText("CarregarDados");
        jMenuItemCarregaDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCarregaDadosActionPerformed(evt);
            }
        });
        jPopupMenuFornecedor.add(jMenuItemCarregaDados);

        jMenuItemContatos.setText("Exibir Contatos ...");
        jMenuItemContatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemContatosActionPerformed(evt);
            }
        });
        jPopupMenuFornecedor.add(jMenuItemContatos);

        jMenuItemEndereco.setText("Exibir Endereços ...");
        jMenuItemEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEnderecoActionPerformed(evt);
            }
        });
        jPopupMenuFornecedor.add(jMenuItemEndereco);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Fornecedores");
        setResizable(false);

        jLabel2.setText("Código do Fornecedor");

        jTextFieldCdFornecedor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldCdFornecedorFocusLost(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(0, 102, 204));
        jLabel3.setText("Nome");

        jTextFieldNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNomeKeyTyped(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(0, 102, 204));
        jLabel4.setText("CPF/CNPJ");

        jLabel5.setText("Tipo de Pessoa");

        buttonGroupTipoPessoa.add(jRadioButtonPfisica);
        jRadioButtonPfisica.setSelected(true);
        jRadioButtonPfisica.setText("Pessoa Física");
        jRadioButtonPfisica.setToolTipText("Física (Ctrl + F)");
        jRadioButtonPfisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPfisicaActionPerformed(evt);
            }
        });

        buttonGroupTipoPessoa.add(jRadioButtonPJuridica);
        jRadioButtonPJuridica.setText("Pessoa Jurídica");
        jRadioButtonPJuridica.setToolTipText("Jurídica (Ctrl + J)");
        jRadioButtonPJuridica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPJuridicaActionPerformed(evt);
            }
        });

        jLabel6.setText("Sexo");

        jComboBoxSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MASCULINO", "FEMININO" }));

        jLabel7.setText("Data de Cadastro");

        jLabel8.setText("Razão Social");

        jTextFieldRazao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldRazaoKeyTyped(evt);
            }
        });

        jLabel9.setText("RG");

        jTextFieldRG.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldRGKeyTyped(evt);
            }
        });

        jLabel10.setText("Cidade");

        jBtCidades.setText("Cidades...");
        jBtCidades.setToolTipText("Cidades (F4)");
        jBtCidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtCidadesActionPerformed(evt);
            }
        });

        jLabel11.setText("CEP");

        jLabel12.setText("Nr Endereço");

        jTextFieldNrEndereco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNrEnderecoKeyTyped(evt);
            }
        });

        jTextFieldRua.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldRuaKeyTyped(evt);
            }
        });

        jLabel13.setText("Rua Avenida");

        jTextFieldBairro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldBairroKeyTyped(evt);
            }
        });

        jLabel14.setText("Bairro");

        jLabel15.setText("Complemento");

        jTextFieldComplemento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldComplementoKeyTyped(evt);
            }
        });

        jLabel16.setText("Email");

        jTextFieldEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldEmailKeyTyped(evt);
            }
        });

        jLabel17.setText("Fone Residencial");

        jLabel18.setText("Fone Comercial");

        jLabel19.setText("Fone Celular");

        jComboBoxSituacao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ATIVO", "INATIVO" }));

        jLabel20.setText("Situação");

        jBtIncluir.setText("Incluir");
        jBtIncluir.setToolTipText("Incluir (F1)");
        jBtIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtIncluirActionPerformed(evt);
            }
        });

        jBtExcluir.setText("Excluir");
        jBtExcluir.setToolTipText("Excluir (F3)");
        jBtExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtExcluirActionPerformed(evt);
            }
        });

        jBtAlterar.setText("Alterar");
        jBtAlterar.setToolTipText("Alterar (F2)");
        jBtAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtAlterarActionPerformed(evt);
            }
        });

        jBtGravar.setText("Gravar");
        jBtGravar.setToolTipText("Gravar (Enter)");
        jBtGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtGravarActionPerformed(evt);
            }
        });

        jBtCancelar.setText("Cancelar");
        jBtCancelar.setToolTipText("Cancelar (Esc)");
        jBtCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBotoesLayout = new javax.swing.GroupLayout(jPanelBotoes);
        jPanelBotoes.setLayout(jPanelBotoesLayout);
        jPanelBotoesLayout.setHorizontalGroup(
            jPanelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelBotoesLayout.setVerticalGroup(
            jPanelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBotoesLayout.createSequentialGroup()
                .addGap(0, 27, Short.MAX_VALUE)
                .addGroup(jPanelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtIncluir)
                    .addComponent(jBtExcluir)
                    .addComponent(jBtAlterar)
                    .addComponent(jBtGravar)
                    .addComponent(jBtCancelar)))
        );

        jBtContatos.setText("Contatos...");
        jBtContatos.setToolTipText("Contatos (F7)");
        jBtContatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtContatosActionPerformed(evt);
            }
        });

        jBtEndereco.setText("Endereços...");
        jBtEndereco.setToolTipText("Endereços (F8)");
        jBtEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtEnderecoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCadastroLayout = new javax.swing.GroupLayout(jPanelCadastro);
        jPanelCadastro.setLayout(jPanelCadastroLayout);
        jPanelCadastroLayout.setHorizontalGroup(
            jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelCadastroLayout.createSequentialGroup()
                            .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jTextFieldCdFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(72, 72, 72)
                            .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addGroup(jPanelCadastroLayout.createSequentialGroup()
                                    .addComponent(jRadioButtonPfisica)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jRadioButtonPJuridica))))
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextFieldNome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelCadastroLayout.createSequentialGroup()
                            .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jFormattedTextFieldCpfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldRG, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelCadastroLayout.createSequentialGroup()
                            .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldNrEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12))
                            .addGap(18, 18, 18)
                            .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanelCadastroLayout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addComponent(jTextFieldRua))))
                    .addComponent(jLabel15)
                    .addComponent(jTextFieldComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelCadastroLayout.createSequentialGroup()
                        .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldFoneRes, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addGap(28, 28, 28)
                        .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldFoneCom, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addGap(28, 28, 28)
                        .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jTextFieldFoneCel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(33, 33, 33)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastroLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelCadastroLayout.createSequentialGroup()
                        .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel14)
                            .addComponent(jLabel20))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadastroLayout.createSequentialGroup()
                        .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                                .addComponent(jComboBoxSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addComponent(jBtContatos)
                                .addGap(18, 18, 18)
                                .addComponent(jBtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldEmail, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldBairro, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldRazao, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jFormattedTextFieldDataCadastro)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelCadastroLayout.createSequentialGroup()
                                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelCadastroLayout.createSequentialGroup()
                                        .addComponent(jComboBoxCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jBtCidades, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel10))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelCadastroLayout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jTextFieldCEP))))
                        .addGap(40, 40, 40))))
            .addComponent(jPanelBotoes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelCadastroLayout.setVerticalGroup(
            jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastroLayout.createSequentialGroup()
                        .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCdFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanelCadastroLayout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(26, 26, 26))
                        .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonPfisica)
                            .addComponent(jRadioButtonPJuridica)))
                    .addGroup(jPanelCadastroLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextFieldDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldRazao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtCidades)
                    .addComponent(jTextFieldCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldCpfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNrEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldFoneRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldFoneCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldFoneCel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtContatos)
                    .addComponent(jBtEndereco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jPanelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPaneFornecedor.addTab("Cadastro", jPanelCadastro);

        jTableConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Pessoa", "CPF/CNPJ", "Cidade", "Email", "Data Cadastro", "Situação"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableConsulta.setComponentPopupMenu(jPopupMenuFornecedor);
        jScrollPane1.setViewportView(jTableConsulta);

        jLabel1.setText("Filtro da Consulta");

        jComboBoxConsulta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Geral", "Código", "Nome" }));
        jComboBoxConsulta.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBoxConsultaPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jBtPesquisar.setText("Pesquisar");
        jBtPesquisar.setToolTipText("Pesquisar (F5)");
        jBtPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtPesquisarActionPerformed(evt);
            }
        });

        jBtRelatorio.setText("Relatório");
        jBtRelatorio.setToolTipText("Relatório (F6)");
        jBtRelatorio.setEnabled(false);
        jBtRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtRelatorioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelConsultaLayout = new javax.swing.GroupLayout(jPanelConsulta);
        jPanelConsulta.setLayout(jPanelConsultaLayout);
        jPanelConsultaLayout.setHorizontalGroup(
            jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanelConsultaLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelConsultaLayout.createSequentialGroup()
                        .addComponent(jComboBoxConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(jBtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBtRelatorio)))
                .addContainerGap())
        );
        jPanelConsultaLayout.setVerticalGroup(
            jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(8, 8, 8)
                .addGroup(jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtPesquisar)
                    .addComponent(jTextFieldConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtRelatorio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPaneFornecedor.addTab("Consulta", jPanelConsulta);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jTabbedPaneFornecedor))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jTabbedPaneFornecedor))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtIncluirActionPerformed
        limpar.limparCampos(jPanelCadastro);
        jTextFieldNome.grabFocus();
        rotina = Rotinas.incluir;
        botoes.validaBotoes(jPanelBotoes, rotina);
        jFormattedTextFieldDataCadastro.setText(dataAtual.retornaDataAtual());
        jComboBoxCidade.setSelectedIndex(0);
        jRadioButtonPfisica.setSelected(true);
        jRadioButtonPfisicaActionPerformed(null);
        jComboBoxSexo.setSelectedIndex(0);
        jComboBoxSituacao.setSelectedIndex(0);
    }//GEN-LAST:event_jBtIncluirActionPerformed

    private void jRadioButtonPfisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPfisicaActionPerformed
        jComboBoxSexo.setEnabled(true);
        jTextFieldRG.setEnabled(true);
        jTextFieldRazao.setEnabled(false);

        jFormattedTextFieldCpfCnpj.setFormatterFactory(null);
        MaskFormatter formato = null;
        try {
            formato = new MaskFormatter("###.###.###-##");
        } catch (ParseException ex) {
            Logger.getLogger(CadastroCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        jFormattedTextFieldCpfCnpj.setFormatterFactory(new DefaultFormatterFactory(formato));
        jFormattedTextFieldCpfCnpj.setValue(null);
    }//GEN-LAST:event_jRadioButtonPfisicaActionPerformed

    private void jRadioButtonPJuridicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPJuridicaActionPerformed
        jComboBoxSexo.setEnabled(false);
        jTextFieldRG.setEnabled(false);
        jTextFieldRazao.setEnabled(true);

        jFormattedTextFieldCpfCnpj.setFormatterFactory(null);
        MaskFormatter formato = null;
        try {
            formato = new MaskFormatter("##.###.###/####-##");
        } catch (ParseException ex) {
            Logger.getLogger(CadastroCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        jFormattedTextFieldCpfCnpj.setFormatterFactory(new DefaultFormatterFactory(formato));
        jFormattedTextFieldCpfCnpj.setValue(null);
    }//GEN-LAST:event_jRadioButtonPJuridicaActionPerformed

    private void jBtCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtCancelarActionPerformed
        rotina = Rotinas.padrao;
        botoes.validaBotoes(jPanelBotoes, rotina);
        limpar.limparCampos(jPanelCadastro);
        jTextFieldCdFornecedor.grabFocus();
        jComboBoxCidade.setSelectedIndex(0);
        jRadioButtonPfisica.setSelected(true);
        jRadioButtonPfisicaActionPerformed(null);
        jComboBoxSexo.setSelectedIndex(0);
        jComboBoxSituacao.setSelectedIndex(0);
    }//GEN-LAST:event_jBtCancelarActionPerformed

    private void jBtAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtAlterarActionPerformed
        rotina = Rotinas.alterar;
        jTextFieldNome.grabFocus();
        botoes.validaBotoes(jPanelBotoes, rotina);
    }//GEN-LAST:event_jBtAlterarActionPerformed

    private void jBtGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtGravarActionPerformed
        if (jTextFieldNome.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "O nome do fornecedor é obrigatório!");
            jTextFieldNome.grabFocus();
        } 
        else if (jFormattedTextFieldCpfCnpj.getText().equals("   .   .   -  ")||
                jFormattedTextFieldCpfCnpj.getText().equals("  .   .   /    -  ")) {
            JOptionPane.showMessageDialog(null, "O CPF/CNPJ do fornecedor é obrigatório!");
            jFormattedTextFieldCpfCnpj.grabFocus();
        } 
        else if (rotina == Rotinas.incluir && !doc.validaCPFCNPJ(jFormattedTextFieldCpfCnpj.getText())){
            JOptionPane.showMessageDialog(null, "CPF/CNPJ inválido!");
            jFormattedTextFieldCpfCnpj.grabFocus();
        }
        else if (rotina == Rotinas.alterar && jRadioButtonPfisica.isSelected() 
                && !doc.validaCPF(doc.removeMascara(jFormattedTextFieldCpfCnpj.getText()))){
            JOptionPane.showMessageDialog(null, "CPF inválido!");
            jFormattedTextFieldCpfCnpj.grabFocus();
        }
        else if (rotina == Rotinas.alterar && jRadioButtonPJuridica.isSelected()
                && !doc.validaCNPJ(doc.removeMascara(jFormattedTextFieldCpfCnpj.getText()))){
            JOptionPane.showMessageDialog(null, "CNPJ inválido!");
            jFormattedTextFieldCpfCnpj.grabFocus();
        }
        else {
            carregarFornecedor();
            carregarEndereco();
            carregarContato();

            if (rotina == Rotinas.incluir) {
                fornecedor.incluir(fornecedor);
                JOptionPane.showMessageDialog(null, "Fornecedor gravado com sucesso!");
                jTextFieldCdFornecedor.setText(fornecedor.getCdFornecedor().toString());
            } else if (rotina == Rotinas.alterar) {
                if (jTextFieldCdFornecedor.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "É preciso informar o código do fornecedor que deseja alterar!");
                    jTextFieldCdFornecedor.grabFocus();
                } else {
                    try {
                        fornecedor.setCdFornecedor(Integer.parseInt(jTextFieldCdFornecedor.getText()));
                        fornecedor.alterar(fornecedor);
                        JOptionPane.showMessageDialog(null, "Fornecedor alterado com sucesso!");
                    } catch (NumberFormatException ex) {

                    }
                }
            }
            rotina = Rotinas.padrao;
            botoes.validaBotoes(jPanelBotoes, rotina);
        }
    }//GEN-LAST:event_jBtGravarActionPerformed

    private void jTextFieldCdFornecedorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCdFornecedorFocusLost
        if (!jTextFieldCdFornecedor.getText().equals("")) {
            try {
                fornecedor.setCdFornecedor(Integer.parseInt(jTextFieldCdFornecedor.getText()));
                fornecedor.retornaFornecedor(fornecedor);

                if (fornecedor.getPessoa().getNome().equals("")) {
                    jBtCancelarActionPerformed(null);
                } else {
                    limpar.limparCampos(jPanelCadastro);
                    preencherCampos();
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Por favor informe um código!");
                jBtCancelarActionPerformed(null);
            }
        }
    }//GEN-LAST:event_jTextFieldCdFornecedorFocusLost

    private void jBtPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtPesquisarActionPerformed
        PreencherTabela preencher = new PreencherTabela();
        preencher.FormatarJtable(jTableConsulta, new int[]{40, 180, 45, 100, 120, 180, 60, 40});
        
        switch (jComboBoxConsulta.getSelectedIndex()){
            case 0:
                preencher.PreencherJtableGenerico(jTableConsulta, fornecedor.consultarGeral(true));
                report.setConsulta(preencher.getConsulta());
                editaBotao(preencher.Vazia());
            break;
                
            case 1:
                try{
                    fornecedor.setCdFornecedor(Integer.parseInt(jTextFieldConsulta.getText()));
                    preencher.PreencherJtableGenerico(jTableConsulta, fornecedor.consultarCdFornecedor(fornecedor, true));
                    report.setConsulta(preencher.getConsulta());
                    editaBotao(preencher.Vazia());
                }
                catch(NumberFormatException ex){
                    JOptionPane.showMessageDialog(null, "Por favor informe um código para pesquisar!");
                    editaBotao(true);
                }
            break;
                
            default:
                fornecedor.getPessoa().setNome(jTextFieldConsulta.getText().toUpperCase());
                preencher.PreencherJtableGenerico(jTableConsulta, fornecedor.consultarNomeFornecedor(fornecedor, true));
                report.setConsulta(preencher.getConsulta());
                editaBotao(preencher.Vazia());
            break;    
        }
    }//GEN-LAST:event_jBtPesquisarActionPerformed

    private void jBtExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtExcluirActionPerformed
        if (jTextFieldCdFornecedor.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "É preciso informar o código do fornecedor que deseja excluir!");
            jTextFieldCdFornecedor.grabFocus();
        } else {
            try {
                fornecedor.setCdFornecedor(Integer.parseInt(jTextFieldCdFornecedor.getText()));

                int delete = JOptionPane.showConfirmDialog(null, "Deseja realmente inativar este fornecedor ?",
                        "Inativar Fornecedor", JOptionPane.YES_NO_OPTION);

                if (delete == JOptionPane.YES_OPTION) {
                    fornecedor.excluir(fornecedor);
                    JOptionPane.showMessageDialog(null, "Fornecedor inativado com sucesso!");
                    limpar.limparCampos(jPanelCadastro);
                }
            } catch (NumberFormatException ex) {

            }
        }
        rotina = Rotinas.excluir;
        botoes.validaBotoes(jPanelBotoes, rotina);
    }//GEN-LAST:event_jBtExcluirActionPerformed

    private void jTextFieldNrEnderecoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNrEnderecoKeyTyped
        campos.validaCamposLimite(evt, jTextFieldNrEndereco, 6);
    }//GEN-LAST:event_jTextFieldNrEnderecoKeyTyped

    private void jMenuItemCarregaDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCarregaDadosActionPerformed
        int linha = jTableConsulta.getSelectedRow();

        if (linha >= 0) {
            int cd = Integer.parseInt(jTableConsulta.getValueAt(linha, 0).toString());
            fornecedor.setCdFornecedor(cd);
            fornecedor.retornaFornecedor(fornecedor);

            limpar.limparCampos(jPanelCadastro);
            preencherCampos();
            jTabbedPaneFornecedor.setSelectedIndex(0);

            rotina = Rotinas.padrao;
            botoes.validaBotoes(jPanelBotoes, rotina);
        }
    }//GEN-LAST:event_jMenuItemCarregaDadosActionPerformed

    private void jTextFieldNomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNomeKeyTyped
        campos.validaCamposLimite(evt, jTextFieldNome, 60);
    }//GEN-LAST:event_jTextFieldNomeKeyTyped

    private void jTextFieldRazaoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldRazaoKeyTyped
        campos.validaCamposLimite(evt, jTextFieldRazao, 60);
    }//GEN-LAST:event_jTextFieldRazaoKeyTyped

    private void jTextFieldRuaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldRuaKeyTyped
        campos.validaCamposLimite(evt, jTextFieldRua, 50);
    }//GEN-LAST:event_jTextFieldRuaKeyTyped

    private void jTextFieldBairroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBairroKeyTyped
        campos.validaCamposLimite(evt, jTextFieldBairro, 50);
    }//GEN-LAST:event_jTextFieldBairroKeyTyped

    private void jTextFieldComplementoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldComplementoKeyTyped
        campos.validaCamposLimite(evt, jTextFieldComplemento, 50);
    }//GEN-LAST:event_jTextFieldComplementoKeyTyped

    private void jTextFieldEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEmailKeyTyped
        campos.validaCamposLimite(evt, jTextFieldEmail, 40);
    }//GEN-LAST:event_jTextFieldEmailKeyTyped

    private void jBtCidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtCidadesActionPerformed
        CadastroCidade cadCidade = new CadastroCidade();
        cadCidade.setVisible(true);
        cadCidade.addWindowListener(new WindowAdapter() {
            public void windowClosed(WindowEvent evento) {
                fornecedor.getPessoa().getEndereco().retornaComboCidade(jComboBoxCidade);
            }
        });
    }//GEN-LAST:event_jBtCidadesActionPerformed

    private void jBtContatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtContatosActionPerformed
        CadastroContato cadContato = new CadastroContato();
        cadContato.setVisible(true);
        try {
            fornecedor.getPessoa().setCdPessoa(Integer.parseInt(jTextFieldCdFornecedor.getText()));
            cadContato.getValores();
        } catch (NumberFormatException ex) {

        }
    }//GEN-LAST:event_jBtContatosActionPerformed

    private void jBtEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtEnderecoActionPerformed
        CadastroEndereco cadEndereco = new CadastroEndereco();
        cadEndereco.setVisible(true);
        try {
            fornecedor.getPessoa().setCdPessoa(Integer.parseInt(jTextFieldCdFornecedor.getText()));
            cadEndereco.getValores();
        } catch (NumberFormatException ex) {

        }
    }//GEN-LAST:event_jBtEnderecoActionPerformed

    private void jMenuItemEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEnderecoActionPerformed
        int linha = jTableConsulta.getSelectedRow();
        if (linha >= 0) {

            int cd = Integer.parseInt(jTableConsulta.getValueAt(linha, 0).toString());
            fornecedor.getPessoa().setCdPessoa(cd);
            CadastroEndereco cadEndereco = new CadastroEndereco();
            cadEndereco.setVisible(true);

            cadEndereco.chamaConsulta();
        }
    }//GEN-LAST:event_jMenuItemEnderecoActionPerformed

    private void jMenuItemContatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemContatosActionPerformed
        int linha = jTableConsulta.getSelectedRow();
        if (linha >= 0) {

            int cd = Integer.parseInt(jTableConsulta.getValueAt(linha, 0).toString());
            fornecedor.getPessoa().setCdPessoa(cd);
            CadastroContato cadContato = new CadastroContato();
            cadContato.setVisible(true);

            cadContato.chamaConsulta();
        }
    }//GEN-LAST:event_jMenuItemContatosActionPerformed

    private void jBtRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtRelatorioActionPerformed
                report.setSubreport(true);
                report.setTabela("FORNECEDOR");
                report.gerarRelatorio(report);
    }//GEN-LAST:event_jBtRelatorioActionPerformed

    private void jTextFieldRGKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldRGKeyTyped
        campos.validaCamposLimite(evt, jTextFieldRG, 12);
    }//GEN-LAST:event_jTextFieldRGKeyTyped

    private void jComboBoxConsultaPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBoxConsultaPopupMenuWillBecomeInvisible
        switch (jComboBoxConsulta.getSelectedIndex()){
            case 0:
                jTextFieldConsulta.setText("");
                jTextFieldConsulta.setEnabled(false);
            break;    
                
            default:
                jTextFieldConsulta.setEnabled(true);
                jTextFieldConsulta.setText("");
                jTextFieldConsulta.grabFocus();
            break;    
        }
    }//GEN-LAST:event_jComboBoxConsultaPopupMenuWillBecomeInvisible

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroFornecedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupTipoPessoa;
    private javax.swing.JButton jBtAlterar;
    private javax.swing.JButton jBtCancelar;
    private javax.swing.JButton jBtCidades;
    private javax.swing.JButton jBtContatos;
    private javax.swing.JButton jBtEndereco;
    private javax.swing.JButton jBtExcluir;
    private javax.swing.JButton jBtGravar;
    private javax.swing.JButton jBtIncluir;
    private javax.swing.JButton jBtPesquisar;
    private javax.swing.JButton jBtRelatorio;
    private javax.swing.JComboBox jComboBoxCidade;
    private javax.swing.JComboBox jComboBoxConsulta;
    private javax.swing.JComboBox jComboBoxSexo;
    private javax.swing.JComboBox jComboBoxSituacao;
    private javax.swing.JFormattedTextField jFormattedTextFieldCpfCnpj;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataCadastro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItemCarregaDados;
    private javax.swing.JMenuItem jMenuItemContatos;
    private javax.swing.JMenuItem jMenuItemEndereco;
    private javax.swing.JPanel jPanelBotoes;
    private javax.swing.JPanel jPanelCadastro;
    private javax.swing.JPanel jPanelConsulta;
    private javax.swing.JPopupMenu jPopupMenuFornecedor;
    private javax.swing.JRadioButton jRadioButtonPJuridica;
    private javax.swing.JRadioButton jRadioButtonPfisica;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPaneFornecedor;
    private javax.swing.JTable jTableConsulta;
    private javax.swing.JTextField jTextFieldBairro;
    private javax.swing.JTextField jTextFieldCEP;
    private javax.swing.JTextField jTextFieldCdFornecedor;
    private javax.swing.JTextField jTextFieldComplemento;
    private javax.swing.JTextField jTextFieldConsulta;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldFoneCel;
    private javax.swing.JTextField jTextFieldFoneCom;
    private javax.swing.JTextField jTextFieldFoneRes;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldNrEndereco;
    private javax.swing.JTextField jTextFieldRG;
    private javax.swing.JTextField jTextFieldRazao;
    private javax.swing.JTextField jTextFieldRua;
    // End of variables declaration//GEN-END:variables

    public void carregarFornecedor() {
        fornecedor.getPessoa().setNome(jTextFieldNome.getText().toUpperCase());

        fornecedor.setDtCadastro(jFormattedTextFieldDataCadastro.getText());

        if (jComboBoxSituacao.getSelectedIndex() == 0) {
            fornecedor.setInAtivo("A");
        } else {
            fornecedor.setInAtivo("I");
        }
        if (jRadioButtonPfisica.isSelected()) {
            carregarFornecedorFisico();
        } else {
            carregarFornecedorJuridico();
        }
        fornecedor.getPessoa().setDtCadastro(fornecedor.getDtCadastro());
        fornecedor.getPessoa().setInAtivo(fornecedor.getInAtivo());
    }

    public void carregarFornecedorFisico() {
        fornecedor.getPessoa().setTpPessoa("F");
        fornecedor.getPessoa().getPfisica().setCPF(jFormattedTextFieldCpfCnpj.getText());
        fornecedor.getPessoa().getPfisica().setRG(jTextFieldRG.getText());

        if (jComboBoxSexo.getSelectedIndex() == 0) {
            fornecedor.getPessoa().getPfisica().setSexo("M");
        } else {
            fornecedor.getPessoa().getPfisica().setSexo("F");
        }
    }

    public void carregarFornecedorJuridico() {
        fornecedor.getPessoa().setTpPessoa("J");
        fornecedor.getPessoa().getPjuridica().setCNPJ(jFormattedTextFieldCpfCnpj.getText());
        fornecedor.getPessoa().getPjuridica().setRazao(jTextFieldRazao.getText());
    }

    public void carregarEndereco() {
        fornecedor.getPessoa().getEndereco().getCidade().setCdCidade(jComboBoxCidade.getSelectedIndex());
        fornecedor.getPessoa().getEndereco().setRuaAv(jTextFieldRua.getText().toUpperCase());
        fornecedor.getPessoa().getEndereco().setNrEndereco(jTextFieldNrEndereco.getText());
        fornecedor.getPessoa().getEndereco().setNrSequencia(1);
        fornecedor.getPessoa().getEndereco().setCEP(jTextFieldCEP.getText());
        fornecedor.getPessoa().getEndereco().setBairro(jTextFieldBairro.getText().toUpperCase());
        fornecedor.getPessoa().getEndereco().setComplemento(jTextFieldComplemento.getText().toUpperCase());
    }

    public void carregarContato() {
        fornecedor.getPessoa().getContato().setEmail(jTextFieldEmail.getText().toUpperCase());
        fornecedor.getPessoa().getContato().setNrSeq(1);
        fornecedor.getPessoa().getContato().setNomeContato(jTextFieldNome.getText().toUpperCase());
        preencheFones();
    }

    public void preencherCampos() {
        jTextFieldCdFornecedor.setText(fornecedor.getCdFornecedor().toString());
        jTextFieldNome.setText(fornecedor.getPessoa().getNome());
        jFormattedTextFieldDataCadastro.setText(fornecedor.getDtCadastro());
        jComboBoxSituacao.setSelectedItem(fornecedor.getInAtivo());

        jComboBoxCidade.setSelectedItem(fornecedor.getPessoa().getEndereco().getCidade().getDsCidade());

        jTextFieldCEP.setText(fornecedor.getPessoa().getEndereco().getCEP());
        jTextFieldNrEndereco.setText(fornecedor.getPessoa().getEndereco().getNrEndereco());
        jTextFieldRua.setText(fornecedor.getPessoa().getEndereco().getRuaAv());
        jTextFieldBairro.setText(fornecedor.getPessoa().getEndereco().getBairro());
        jTextFieldComplemento.setText(fornecedor.getPessoa().getEndereco().getComplemento());

        jTextFieldEmail.setText(fornecedor.getPessoa().getContato().getEmail());
        jTextFieldFoneRes.setText(fornecedor.getPessoa().getContato().getFoneRes());
        jTextFieldFoneCom.setText(fornecedor.getPessoa().getContato().getFoneCom());
        jTextFieldFoneCel.setText(fornecedor.getPessoa().getContato().getFoneCel());

        if (fornecedor.getPessoa().getTpPessoa().equals("F")) {
            jRadioButtonPfisica.setSelected(true);
            jRadioButtonPfisicaActionPerformed(null);
            jComboBoxSexo.setSelectedItem(fornecedor.getPessoa().getPfisica().getSexo());
            jFormattedTextFieldCpfCnpj.setText(fornecedor.getPessoa().getPfisica().getCPF());
            jTextFieldRG.setText(fornecedor.getPessoa().getPfisica().getRG());
        } else {
            jRadioButtonPJuridica.setSelected(true);
            jRadioButtonPJuridicaActionPerformed(null);
            jFormattedTextFieldCpfCnpj.setText(fornecedor.getPessoa().getPjuridica().getCNPJ());
            jTextFieldRazao.setText(fornecedor.getPessoa().getPjuridica().getRazao());
        }
    }

    public void preencheFones() {
        if (jTextFieldFoneRes.getText().equals("(  )-    -    ")) {
            fornecedor.getPessoa().getContato().setFoneRes("");
        } else {
            fornecedor.getPessoa().getContato().setFoneRes(jTextFieldFoneRes.getText());
        }

        if (jTextFieldFoneCom.getText().equals("(  )-    -    ")) {
            fornecedor.getPessoa().getContato().setFoneCom("");
        } else {
            fornecedor.getPessoa().getContato().setFoneCom(jTextFieldFoneCom.getText());
        }

        if (jTextFieldFoneCel.getText().equals("(  )-    -    ")) {
            fornecedor.getPessoa().getContato().setFoneCel("");
        } else {
            fornecedor.getPessoa().getContato().setFoneCel(jTextFieldFoneCel.getText());
        }
    }

    public void editaBotao(boolean vazia) {
        if (vazia) {
            jBtRelatorio.setEnabled(false);
            jTextFieldConsulta.setText("");
            jTextFieldConsulta.grabFocus();
        } else {
            jBtRelatorio.setEnabled(true);
        }
    }
}
