package Cadastros;

import Classes.Contato;
import Classes.Pessoa;
import Consultas.ConsultaPessoa;
import Validacoes.LimparCampos;
import Validacoes.PreencherTabela;
import Validacoes.Rotinas;
import Validacoes.TeclasdeAtalho;
import Validacoes.ValidaBotoes;
import Validacoes.ValidaCampos;
import java.awt.event.KeyEvent;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Leonardo
 */
public class CadastroContato extends javax.swing.JFrame {

    Contato contato = new Contato();
    Pessoa pessoa = new Pessoa();

    LimparCampos limpar = new LimparCampos();
    ValidaBotoes botoes = new ValidaBotoes();
    ValidaCampos campos = new ValidaCampos();
    int rotina;

    MaskFormatter fone;
    TeclasdeAtalho atalho = new TeclasdeAtalho();

    /**
     * Creates new form CadastroContato
     */
    public CadastroContato() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenuContato = new javax.swing.JPopupMenu();
        jMenuItemCarregar = new javax.swing.JMenuItem();
        jTabbedPaneContato = new javax.swing.JTabbedPane();
        atalho.adicionarAtalho(jTabbedPaneContato);
        jPanelCadastro = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldCdPessoa = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNrSeq = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        try{       fone = new MaskFormatter("(##)-####-####");   }   catch(Exception erro)   {   JOptionPane.showMessageDialog(null, "Não foi possivel localizar");   }
        jTextFieldFoneRes = new JFormattedTextField(fone);
        ;
        jLabel6 = new javax.swing.JLabel();
        try{       fone = new MaskFormatter("(##)-####-####");   }   catch(Exception erro)   {   JOptionPane.showMessageDialog(null, "Não foi possivel localizar");   }
        jTextFieldFoneCel = new JFormattedTextField(fone);
        ;
        try{       fone = new MaskFormatter("(##)-####-####");   }   catch(Exception erro)   {   JOptionPane.showMessageDialog(null, "Não foi possivel localizar");   }
        jTextFieldFoneCom = new JFormattedTextField(fone);
        ;
        jLabel7 = new javax.swing.JLabel();
        jPanelBotoes = new javax.swing.JPanel();
        jBtIncluir = new javax.swing.JButton();
        atalho.adicionarAtalho(jBtIncluir, KeyEvent.VK_F1, 0);
        jBtAlterar = new javax.swing.JButton();
        atalho.adicionarAtalho(jBtAlterar, KeyEvent.VK_F2, 0);
        jBtGravar = new javax.swing.JButton();
        atalho.adicionarAtalho(jBtGravar, KeyEvent.VK_ENTER, 0);
        jBtExcluir = new javax.swing.JButton();
        atalho. adicionarAtalho(jBtExcluir, KeyEvent.VK_F3, 0);
        jBtCancelar = new javax.swing.JButton();
        atalho.adicionarAtalho(jBtCancelar, KeyEvent.VK_ESCAPE, 0);
        jTextFieldNomePessoa = new javax.swing.JTextField();
        jBtPesquisaPessoa = new javax.swing.JButton();
        atalho.adicionarAtalho(jBtPesquisaPessoa, 
            KeyEvent.VK_F4, 0);
        jLabel8 = new javax.swing.JLabel();
        jPanelConsulta = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableConsulta = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxConsulta = new javax.swing.JComboBox();
        jBtPesquisar = new javax.swing.JButton();
        atalho.adicionarAtalho(jBtPesquisar, KeyEvent.VK_F5, 0);
        jTextFieldConsulta = new javax.swing.JTextField();

        jMenuItemCarregar.setText("Carregar Dados");
        jMenuItemCarregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCarregarActionPerformed(evt);
            }
        });
        jPopupMenuContato.add(jMenuItemCarregar);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Contatos");
        setResizable(false);

        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setText("Código Pessoa");

        jTextFieldCdPessoa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldCdPessoaFocusLost(evt);
            }
        });

        jLabel2.setText("Código Contato");

        jTextFieldNrSeq.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldNrSeqFocusLost(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(0, 102, 204));
        jLabel3.setText("Nome do Contato");

        jTextFieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeActionPerformed(evt);
            }
        });
        jTextFieldNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNomeKeyTyped(evt);
            }
        });

        jLabel4.setText("Email");

        jTextFieldEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldEmailKeyTyped(evt);
            }
        });

        jLabel5.setText("Fone Residencial");

        jTextFieldFoneRes.setName(""); // NOI18N

        jLabel6.setText("Fone Comercial");

        jTextFieldFoneCel.setName(""); // NOI18N

        jTextFieldFoneCom.setName(""); // NOI18N

        jLabel7.setText("Fone Celular");

        jBtIncluir.setText("Incluir");
        jBtIncluir.setToolTipText("Incluir (F1)");
        jBtIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtIncluirActionPerformed(evt);
            }
        });

        jBtAlterar.setText("Alterar");
        jBtAlterar.setToolTipText("Alterar (F2)");
        jBtAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtAlterarActionPerformed(evt);
            }
        });

        jBtGravar.setText("Gravar");
        jBtGravar.setToolTipText("Gravar (Enter)");
        jBtGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtGravarActionPerformed(evt);
            }
        });

        jBtExcluir.setText("Excluir");
        jBtExcluir.setToolTipText("Excluir (F3)");
        jBtExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtExcluirActionPerformed(evt);
            }
        });

        jBtCancelar.setText("Cancelar");
        jBtCancelar.setToolTipText("Cancelar (Esc)");
        jBtCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBotoesLayout = new javax.swing.GroupLayout(jPanelBotoes);
        jPanelBotoes.setLayout(jPanelBotoesLayout);
        jPanelBotoesLayout.setHorizontalGroup(
            jPanelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtCancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelBotoesLayout.setVerticalGroup(
            jPanelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBotoesLayout.createSequentialGroup()
                .addGap(0, 22, Short.MAX_VALUE)
                .addGroup(jPanelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtIncluir)
                    .addComponent(jBtAlterar)
                    .addComponent(jBtGravar)
                    .addComponent(jBtExcluir)
                    .addComponent(jBtCancelar)))
        );

        jTextFieldNomePessoa.setEditable(false);
        jTextFieldNomePessoa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNomePessoaKeyTyped(evt);
            }
        });

        jBtPesquisaPessoa.setText("Pesquisar");
        jBtPesquisaPessoa.setToolTipText("Pesquisar (F4)");
        jBtPesquisaPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtPesquisaPessoaActionPerformed(evt);
            }
        });

        jLabel8.setText("Nome");

        javax.swing.GroupLayout jPanelCadastroLayout = new javax.swing.GroupLayout(jPanelCadastro);
        jPanelCadastro.setLayout(jPanelCadastroLayout);
        jPanelCadastroLayout.setHorizontalGroup(
            jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastroLayout.createSequentialGroup()
                        .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNrSeq, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelCadastroLayout.createSequentialGroup()
                        .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelCadastroLayout.createSequentialGroup()
                                        .addComponent(jTextFieldCdPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jBtPesquisaPessoa))
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jTextFieldNomePessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldFoneRes, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldFoneCom, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jTextFieldFoneCel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextFieldEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                                .addComponent(jTextFieldNome, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(0, 194, Short.MAX_VALUE))))
        );
        jPanelCadastroLayout.setVerticalGroup(
            jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCdPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNomePessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtPesquisaPessoa))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNrSeq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastroLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldFoneRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldFoneCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldFoneCel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jPanelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPaneContato.addTab("Cadastro", jPanelCadastro);

        jTableConsulta.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jTableConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Nr Seq", "Nome Contato", "Email", "Fone Res", "Fone Com", "Fone Cel"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableConsulta.setComponentPopupMenu(jPopupMenuContato);
        jScrollPane1.setViewportView(jTableConsulta);

        jLabel9.setText("Filtro da Consulta");

        jComboBoxConsulta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Geral", "Código", "Nome" }));
        jComboBoxConsulta.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBoxConsultaPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jBtPesquisar.setText("Pesquisar");
        jBtPesquisar.setToolTipText("Pesquisar (F5)");
        jBtPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelConsultaLayout = new javax.swing.GroupLayout(jPanelConsulta);
        jPanelConsulta.setLayout(jPanelConsultaLayout);
        jPanelConsultaLayout.setHorizontalGroup(
            jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 805, Short.MAX_VALUE)
                    .addGroup(jPanelConsultaLayout.createSequentialGroup()
                        .addGroup(jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxConsulta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldConsulta)
                        .addGap(18, 18, 18)
                        .addComponent(jBtPesquisar)))
                .addContainerGap())
        );
        jPanelConsultaLayout.setVerticalGroup(
            jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBtPesquisar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPaneContato.addTab("Consulta", jPanelConsulta);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneContato, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneContato, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtIncluirActionPerformed
        if (jTextFieldCdPessoa.getText().equals("")) {
            limpar.limparCampos(jPanelCadastro);
            jTextFieldCdPessoa.grabFocus();
        } else {
            limparApenasContato();
            jTextFieldNome.grabFocus();
        }

        rotina = Rotinas.incluir;
        botoes.validaBotoes(jPanelBotoes, rotina);
    }//GEN-LAST:event_jBtIncluirActionPerformed

    private void jBtAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtAlterarActionPerformed
        rotina = Rotinas.alterar;
        jTextFieldNome.grabFocus();
        botoes.validaBotoes(jPanelBotoes, rotina);
    }//GEN-LAST:event_jBtAlterarActionPerformed

    private void jBtGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtGravarActionPerformed
        if (jTextFieldCdPessoa.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "O código da pessoa é obrigatório!");
            jTextFieldCdPessoa.grabFocus();
        }
        else if (jTextFieldNome.getText().equals("")){
            JOptionPane.showMessageDialog(null, "O nome do contato é obrigatório!");
            jTextFieldNome.grabFocus();
        }
        
        else {
            carregarContato();

            if (rotina == Rotinas.incluir) {
                contato.incluir(contato);
                //JOptionPane.showMessageDialog(null, "Contato gravado com sucesso!");
                jTextFieldNrSeq.setText(contato.getNrSeq().toString());
            } else if (rotina == Rotinas.alterar) {

                if (jTextFieldNrSeq.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "Informe o código do contato que deseja alterar!");
                    jTextFieldNrSeq.grabFocus();
                } else {
                    try {
                        contato.setNrSeq(Integer.parseInt(jTextFieldNrSeq.getText()));
                        contato.alterar(contato);
                        //JOptionPane.showMessageDialog(null, "Contato alterado com sucesso!");
                    } catch (NumberFormatException ex) {
                    }
                }
            }
            rotina = Rotinas.padrao;
            botoes.validaBotoes(jPanelBotoes, rotina);
        }
    }//GEN-LAST:event_jBtGravarActionPerformed

    private void jBtCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtCancelarActionPerformed
        rotina = Rotinas.padrao;
        botoes.validaBotoes(jPanelBotoes, rotina);
        limpar.limparCampos(jPanelCadastro);
        jTextFieldCdPessoa.grabFocus();
    }//GEN-LAST:event_jBtCancelarActionPerformed

    private void jBtExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtExcluirActionPerformed
        if (jTextFieldCdPessoa.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "É preciso informar o código da pessoa que deseja excluir os contatos!");
            jTextFieldCdPessoa.grabFocus();
        } else if (jTextFieldNrSeq.getText().equals("")) {
            try {
                contato.setCdPessoa(Integer.parseInt(jTextFieldCdPessoa.getText()));

                int opcao = JOptionPane.showConfirmDialog(null, "Não foi selecionado nenhum código de contato.\nDeseja "
                        + "excluir todos os contatos desta pessoa ?", "Excluir Contatos", JOptionPane.YES_NO_OPTION);

                if (opcao == JOptionPane.YES_OPTION) {
                    int delete = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir todos os contatos da pessoa ?",
                            "Excluir Todos os Contatos", JOptionPane.YES_NO_OPTION);
                    if (delete == JOptionPane.YES_OPTION) {
                        contato.excluirTodos(contato);
                        //JOptionPane.showMessageDialog(null, "Contatos excluídos com sucesso!");
                        limpar.limparCampos(jPanelCadastro);
                    }
                } else {
                    jTextFieldNrSeq.grabFocus();
                }
            } catch (NumberFormatException ex) {
            }
        } else {
            try {
                contato.setCdPessoa(Integer.parseInt(jTextFieldCdPessoa.getText()));
                contato.setNrSeq(Integer.parseInt(jTextFieldNrSeq.getText()));

                int excluir = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir este contato ?",
                        "Excluir Contato", JOptionPane.YES_NO_OPTION);

                if (excluir == JOptionPane.YES_OPTION) {
                    contato.excluir(contato);
                    //JOptionPane.showMessageDialog(null, "Contato excluído com sucesso!");
                    limpar.limparCampos(jPanelCadastro);
                }

            } catch (NumberFormatException ex) {
            }
        }
        rotina = Rotinas.excluir;
        botoes.validaBotoes(jPanelBotoes, rotina);
    }//GEN-LAST:event_jBtExcluirActionPerformed

    private void jBtPesquisaPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtPesquisaPessoaActionPerformed
        final ConsultaPessoa csPessoa = new ConsultaPessoa(this, true);
        csPessoa.setVisible(true);

        csPessoa.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {

                if (pessoa.getCdPessoa() == 0) {
                    jTextFieldNomePessoa.setText("");
                    jTextFieldCdPessoa.setText("");
                } else {
                    jTextFieldCdPessoa.setText(pessoa.getCdPessoa().toString());
                    pessoa.retornaPessoa(pessoa);
                    jTextFieldNomePessoa.setText(pessoa.getNome());
                }
            }
        });
    }//GEN-LAST:event_jBtPesquisaPessoaActionPerformed

    private void jTextFieldCdPessoaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCdPessoaFocusLost
        if (!jTextFieldCdPessoa.getText().equals("")) {

            try {
                contato.setCdPessoa(Integer.parseInt(jTextFieldCdPessoa.getText()));
                pessoa.setCdPessoa(contato.getCdPessoa());

                pessoa.retornaPessoa(pessoa);
                if (pessoa.getNome().equals("")) {
                    jBtCancelarActionPerformed(null);
                } else {
                    jTextFieldNomePessoa.setText(pessoa.getNome());
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Por favor informe um código!");
                jBtCancelarActionPerformed(null);
            }

            jTextFieldNrSeqFocusLost(null);
        }
    }//GEN-LAST:event_jTextFieldCdPessoaFocusLost

    private void jTextFieldNrSeqFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNrSeqFocusLost
        if (!jTextFieldCdPessoa.getText().equals("") && (!jTextFieldNrSeq.getText().equals(""))) {

            try {
                contato.setCdPessoa(Integer.parseInt(jTextFieldCdPessoa.getText()));
                contato.setNrSeq(Integer.parseInt(jTextFieldNrSeq.getText()));
                contato.retornaContato(contato);

                if (contato.getNomeContato().equals("")) {
                    limparApenasContato();
                } else {
                    preencherCampos();
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Por favor informe um código!");
                limparApenasContato();
                jTextFieldNrSeq.grabFocus();
            }
        }
    }//GEN-LAST:event_jTextFieldNrSeqFocusLost

    private void jBtPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtPesquisarActionPerformed
        PreencherTabela preencher = new PreencherTabela();
        preencher.FormatarJtable(jTableConsulta, new int[]{40, 140, 40, 140, 180, 80, 80, 80});

        switch (jComboBoxConsulta.getSelectedIndex()){
            case 0:
                preencher.PreencherJtableGenerico(jTableConsulta, contato.consultarGeral());
            break;    
                
            case 1:
                try {
                   contato.setCdPessoa(Integer.parseInt(jTextFieldConsulta.getText()));
                   preencher.PreencherJtableGenerico(jTableConsulta, contato.consultarCdContato(contato));
                } 
                catch (NumberFormatException ex) {
                   JOptionPane.showMessageDialog(null, "Por favor informe um código!");
                   jTextFieldConsulta.setText("");
                   jTextFieldConsulta.grabFocus();
                }
            break;
                
            default:
                pessoa.setNome(jTextFieldConsulta.getText().toUpperCase());
                preencher.PreencherJtableGenerico(jTableConsulta, contato.consultarNome(pessoa));
            break;       
        }
    }//GEN-LAST:event_jBtPesquisarActionPerformed

    private void jMenuItemCarregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCarregarActionPerformed
        int linha = jTableConsulta.getSelectedRow();

        if (linha >= 0) {
            int cd = Integer.parseInt(jTableConsulta.getValueAt(linha, 0).toString());
            int nr = Integer.parseInt(jTableConsulta.getValueAt(linha, 2).toString());
            contato.setCdPessoa(cd);
            contato.setNrSeq(nr);

            contato.retornaContato(contato);
            pessoa.setCdPessoa(cd);
            pessoa.retornaPessoa(pessoa);

            preencherCampos();
            jTabbedPaneContato.setSelectedIndex(0);

            rotina = Rotinas.padrao;
            botoes.validaBotoes(jPanelBotoes, rotina);
        }
    }//GEN-LAST:event_jMenuItemCarregarActionPerformed

    private void jTextFieldNomePessoaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNomePessoaKeyTyped

    }//GEN-LAST:event_jTextFieldNomePessoaKeyTyped

    private void jTextFieldNomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNomeKeyTyped
        campos.validaCamposLimite(evt, jTextFieldNome, 60);
    }//GEN-LAST:event_jTextFieldNomeKeyTyped

    private void jTextFieldEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEmailKeyTyped
        campos.validaCamposLimite(evt, jTextFieldEmail, 40);
    }//GEN-LAST:event_jTextFieldEmailKeyTyped

    private void jTextFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeActionPerformed

    private void jComboBoxConsultaPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBoxConsultaPopupMenuWillBecomeInvisible
        switch (jComboBoxConsulta.getSelectedIndex()){
            case 0:
                jTextFieldConsulta.setText("");
                jTextFieldConsulta.setEnabled(false);
            break;    
                
            default:
                jTextFieldConsulta.setEnabled(true);
                jTextFieldConsulta.setText("");
                jTextFieldConsulta.grabFocus();
            break;    
        }
    }//GEN-LAST:event_jComboBoxConsultaPopupMenuWillBecomeInvisible

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroContato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroContato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroContato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroContato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroContato().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtAlterar;
    private javax.swing.JButton jBtCancelar;
    private javax.swing.JButton jBtExcluir;
    private javax.swing.JButton jBtGravar;
    private javax.swing.JButton jBtIncluir;
    private javax.swing.JButton jBtPesquisaPessoa;
    private javax.swing.JButton jBtPesquisar;
    private javax.swing.JComboBox jComboBoxConsulta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItemCarregar;
    private javax.swing.JPanel jPanelBotoes;
    private javax.swing.JPanel jPanelCadastro;
    private javax.swing.JPanel jPanelConsulta;
    private javax.swing.JPopupMenu jPopupMenuContato;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPaneContato;
    private javax.swing.JTable jTableConsulta;
    private javax.swing.JTextField jTextFieldCdPessoa;
    private javax.swing.JTextField jTextFieldConsulta;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldFoneCel;
    private javax.swing.JTextField jTextFieldFoneCom;
    private javax.swing.JTextField jTextFieldFoneRes;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldNomePessoa;
    private javax.swing.JTextField jTextFieldNrSeq;
    // End of variables declaration//GEN-END:variables

    public void carregarContato() {
        contato.setCdPessoa(Integer.parseInt(jTextFieldCdPessoa.getText()));
        contato.setNomeContato(jTextFieldNome.getText().toUpperCase());
        contato.setEmail(jTextFieldEmail.getText().toUpperCase());
        if (jTextFieldFoneRes.getText().equals("(  )-    -    ")) {
            contato.setFoneRes("");
        } else {
            contato.setFoneRes(jTextFieldFoneRes.getText());
        }
        if (jTextFieldFoneCom.getText().equals("(  )-    -    ")) {
            contato.setFoneCom("");
        } else {
            contato.setFoneCom(jTextFieldFoneCom.getText());
        }
        if (jTextFieldFoneCel.getText().equals("(  )-    -    ")) {
            contato.setFoneCel("");
        } else {
            contato.setFoneCel(jTextFieldFoneCel.getText());
        }
    }

    public void preencherCampos() {
        limpar.limparCampos(jPanelCadastro);
        jTextFieldCdPessoa.setText(contato.getCdPessoa().toString());
        jTextFieldNomePessoa.setText(pessoa.getNome());
        jTextFieldNrSeq.setText(contato.getNrSeq().toString());
        jTextFieldNome.setText(contato.getNomeContato());
        jTextFieldEmail.setText(contato.getEmail());
        jTextFieldFoneRes.setText(contato.getFoneRes());
        jTextFieldFoneCom.setText(contato.getFoneCom());
        jTextFieldFoneCel.setText(contato.getFoneCel());
    }

    public void limparApenasContato() {
        jTextFieldNrSeq.setText("");
        jTextFieldNome.setText("");
        jTextFieldEmail.setText("");
        jTextFieldFoneRes.setText("");
        jTextFieldFoneCom.setText("");
        jTextFieldFoneCel.setText("");
    }

    public void getValores() {
        jTextFieldCdPessoa.setText(pessoa.getCdPessoa().toString());
        jTextFieldNrSeq.setText("1");
        jTextFieldCdPessoaFocusLost(null);
    }

    public void chamaConsulta() {
        jTabbedPaneContato.setSelectedIndex(1);

        PreencherTabela preencher = new PreencherTabela();
        contato.setCdPessoa(pessoa.getCdPessoa());
        preencher.FormatarJtable(jTableConsulta, new int[]{40, 140, 40, 140, 180, 80, 80, 80});
        preencher.PreencherJtableGenerico(jTableConsulta, contato.consultarCdContato(contato));

    }

}
