package Servicos;

import Cadastros.CadastroContas;
import Classes.AtendimentoMesa;
import Classes.Contas;
import Classes.MovEstoque;
import Classes.VendaCompra;
import Consultas.ConsultaClienteFornecedor;
import Consultas.ConsultaForma;
import Consultas.ConsultaOperacao;
import Consultas.ConsultaParcelas;
import Consultas.ConsultaProduto;
import Relatorios.Relatorios;
import Validacoes.EditarComponentes;
import Validacoes.FormataMoeda;
import Validacoes.LimparCampos;
import Validacoes.PreencherTabela;
import Validacoes.RetornaData;
import Validacoes.RetornaDecimal;
import Validacoes.Rotinas;
import Validacoes.TeclasdeAtalho;
import Validacoes.ValidaBotoes;
import Validacoes.ValidaCampos;
import Validacoes.ValidaNivelUsuario;
import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.SpinnerNumberModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Leonardo
 */
public class TelaVendaCompra extends javax.swing.JFrame {

    VendaCompra venda = new VendaCompra();
    Relatorios report = new Relatorios();
    int rotina;
    int linhasAtendimento = 0;
    String tipo;

    RetornaData rdata = new RetornaData();
    RetornaDecimal decimal = new RetornaDecimal();
    LimparCampos limpar = new LimparCampos();
    EditarComponentes edit = new EditarComponentes();
    MaskFormatter data;
    
    TeclasdeAtalho atalho = new TeclasdeAtalho();
    ValidaNivelUsuario valida = new ValidaNivelUsuario();

    /**
     * Creates new form TelaVenda
     */
    public TelaVendaCompra() {
        initComponents();
        jRadioButtonVendaActionPerformed(null);
        rotina = Rotinas.padrao;
        validaEstadoCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTipo = new javax.swing.ButtonGroup();
        jPopupMenuVendaCompra = new javax.swing.JPopupMenu();
        jMenuItemCarregarDados = new javax.swing.JMenuItem();
        jMenuItemExcluir = new javax.swing.JMenuItem();
        jPopupMenuConta = new javax.swing.JPopupMenu();
        jMenuItemExibirParcelas = new javax.swing.JMenuItem();
        buttonGroupSituacao = new javax.swing.ButtonGroup();
        buttonGroupTicket = new javax.swing.ButtonGroup();
        jTabbedPaneVendaCompra = new javax.swing.JTabbedPane();
        atalho.adicionarAtalho(jTabbedPaneVendaCompra);
        jPanelGravar = new javax.swing.JPanel();
        jTextFieldCdVendaCompra = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNrAtendimento = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jRadioButtonVenda = new javax.swing.JRadioButton();
        atalho.adicionarAtalho(jRadioButtonVenda, 
            KeyEvent.VK_V, InputEvent.CTRL_DOWN_MASK);
        jRadioButtonCompra = new javax.swing.JRadioButton();
        atalho.adicionarAtalho(jRadioButtonCompra, KeyEvent.VK_C, InputEvent.CTRL_DOWN_MASK);
        try{       data = new MaskFormatter("##/##/####");   }   catch(Exception erro)   {   JOptionPane.showMessageDialog(null, "Não foi possivel localizar");   }
        jTextFieldData = new JFormattedTextField(data);
        jLabel4 = new javax.swing.JLabel();
        jTextFieldCdCliente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButtonPesquisarCliente = new javax.swing.JButton();
        atalho.adicionarAtalho(jButtonPesquisarCliente, KeyEvent.VK_F4, 0);
        jTextFieldNomeCliente = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldCdForma = new javax.swing.JTextField();
        jButtonPesquisarForma = new javax.swing.JButton();
        atalho.adicionarAtalho(jButtonPesquisarForma, KeyEvent.VK_F7, 0);
        jTextFieldForma = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldCdProduto = new javax.swing.JTextField();
        jButtonPesquisarProduto = new javax.swing.JButton();
        atalho.adicionarAtalho(jButtonPesquisarProduto, KeyEvent.VK_F9, 0);
        jTextFieldProduto = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jSpnQuantidade = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldTotalProduto = new javax.swing.JTextField();
        jBtAdicionar = new javax.swing.JButton();
        atalho.adicionarAtalho(jBtAdicionar, KeyEvent.VK_F2, 0);
        jBtRemover = new javax.swing.JButton();
        atalho.adicionarAtalho(jBtRemover, KeyEvent.VK_F3, 0);
        jLabel12 = new javax.swing.JLabel();
        jTextFieldTotal = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProdutos = new javax.swing.JTable();
        jTableProdutos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jLabel6 = new javax.swing.JLabel();
        jTextFieldCdOperacao = new javax.swing.JTextField();
        jBtPesquisaOperacao = new javax.swing.JButton();
        atalho.adicionarAtalho(jBtPesquisaOperacao, KeyEvent.VK_F8, 0);
        jTextFieldDsOperacao = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldVlAtendimento = new javax.swing.JTextField();
        jTextFieldVlUnitario = new javax.swing.JTextField();
        jPanelBotoes = new javax.swing.JPanel();
        jBtIncluir = new javax.swing.JButton();
        atalho.adicionarAtalho(jBtIncluir, KeyEvent.VK_F1, 0);
        jBtGravar = new javax.swing.JButton();
        atalho.adicionarAtalho(jBtGravar, KeyEvent.VK_ENTER, InputEvent.CTRL_DOWN_MASK);
        jBtCancelar = new javax.swing.JButton();
        atalho.adicionarAtalho(jBtCancelar, KeyEvent.VK_ESCAPE, 0);
        jPanelConsulta = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableVendaCompra = new javax.swing.JTable();
        jTableVendaCompra.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        jTableVendaCompra.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent e) {
                preencherTabela();
            }
        });
        jLabel13 = new javax.swing.JLabel();
        jComboBoxConsulta = new javax.swing.JComboBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableConta = new javax.swing.JTable();
        jTableConta.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableProdutosVenda = new javax.swing.JTable();
        jTableProdutosVenda.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jBtPesquisar = new javax.swing.JButton();
        atalho.adicionarAtalho(jBtPesquisar, KeyEvent.VK_F5, 0);
        jLabel14 = new javax.swing.JLabel();
        jComboBoxTipo = new javax.swing.JComboBox();
        jTextFieldConsulta = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jRadioBtSim = new javax.swing.JRadioButton();
        atalho.adicionarAtalho(jRadioBtSim, KeyEvent.VK_S, InputEvent.CTRL_DOWN_MASK);
        jRadioButtonNao = new javax.swing.JRadioButton();
        atalho.adicionarAtalho(jRadioButtonNao, KeyEvent.VK_N, InputEvent.CTRL_DOWN_MASK);
        jBtRelatorio = new javax.swing.JButton();
        atalho.adicionarAtalho(jBtRelatorio,   KeyEvent.VK_F6, 0);

        jPopupMenuVendaCompra.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                jPopupMenuVendaCompraPopupMenuWillBecomeVisible(evt);
            }
        });

        jMenuItemCarregarDados.setText("Carregar Dados");
        jMenuItemCarregarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCarregarDadosActionPerformed(evt);
            }
        });
        jPopupMenuVendaCompra.add(jMenuItemCarregarDados);

        jMenuItemExcluir.setText("Excluir");
        jMenuItemExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExcluirActionPerformed(evt);
            }
        });
        jPopupMenuVendaCompra.add(jMenuItemExcluir);

        jMenuItemExibirParcelas.setText("Exibir Parcelas");
        jMenuItemExibirParcelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExibirParcelasActionPerformed(evt);
            }
        });
        jPopupMenuConta.add(jMenuItemExibirParcelas);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Realizar Venda/Compra");
        setName("REALIZAR VENDA/COMPRA"); // NOI18N
        setResizable(false);

        jTextFieldCdVendaCompra.setName(""); // NOI18N
        jTextFieldCdVendaCompra.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldCdVendaCompraFocusLost(evt);
            }
        });

        jLabel1.setText("Código Venda/Compra");

        jLabel2.setText("Nr Atendimento");

        jTextFieldNrAtendimento.setEnabled(false);
        jTextFieldNrAtendimento.setName(""); // NOI18N
        jTextFieldNrAtendimento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldNrAtendimentoFocusLost(evt);
            }
        });

        jLabel3.setText("Tipo");

        buttonGroupTipo.add(jRadioButtonVenda);
        jRadioButtonVenda.setSelected(true);
        jRadioButtonVenda.setText("Venda");
        jRadioButtonVenda.setToolTipText("Venda (Ctrl + V)");
        jRadioButtonVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonVendaActionPerformed(evt);
            }
        });

        buttonGroupTipo.add(jRadioButtonCompra);
        jRadioButtonCompra.setText("Compra");
        jRadioButtonCompra.setToolTipText("Compra (Ctrl + C)");
        jRadioButtonCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCompraActionPerformed(evt);
            }
        });

        jTextFieldData.setEnabled(false);

        jLabel4.setText("Data");

        jTextFieldCdCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldCdClienteFocusLost(evt);
            }
        });

        jLabel5.setText("Cliente/Fornecedor");

        jButtonPesquisarCliente.setText("Pesquisar");
        jButtonPesquisarCliente.setToolTipText("Pesquisar (F4)");
        jButtonPesquisarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarClienteActionPerformed(evt);
            }
        });

        jTextFieldNomeCliente.setEnabled(false);

        jLabel7.setText("Forma de Pagamento");

        jTextFieldCdForma.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldCdFormaFocusLost(evt);
            }
        });

        jButtonPesquisarForma.setText("Pesquisar");
        jButtonPesquisarForma.setToolTipText("Pesquisar (F7)");
        jButtonPesquisarForma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarFormaActionPerformed(evt);
            }
        });

        jTextFieldForma.setEnabled(false);

        jLabel8.setText("Produto");

        jTextFieldCdProduto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldCdProdutoFocusLost(evt);
            }
        });

        jButtonPesquisarProduto.setText("Pesquisar");
        jButtonPesquisarProduto.setToolTipText("Pesquisar (F9)");
        jButtonPesquisarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarProdutoActionPerformed(evt);
            }
        });

        jTextFieldProduto.setEnabled(false);

        jLabel9.setText("Quantidade");

        jSpnQuantidade.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));
        jSpnQuantidade.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpnQuantidadeStateChanged(evt);
            }
        });
        jSpnQuantidade.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jSpnQuantidadePropertyChange(evt);
            }
        });

        jLabel10.setText("Valor Unitário (R$)");

        jLabel11.setText("Total (R$)");

        jTextFieldTotalProduto.setDocument(new FormataMoeda());
        jTextFieldTotalProduto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldTotalProduto.setEnabled(false);

        jBtAdicionar.setText("Adicionar");
        jBtAdicionar.setToolTipText("Adicionar (F2)");
        jBtAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtAdicionarActionPerformed(evt);
            }
        });

        jBtRemover.setText("Remover");
        jBtRemover.setToolTipText("Remover (F3)");
        jBtRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtRemoverActionPerformed(evt);
            }
        });

        jLabel12.setText("Valor Total");

        jTextFieldTotal.setDocument(new FormataMoeda());
        jTextFieldTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTableProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Produto", "Valor", "Quantidade", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableProdutos.getTableHeader().setReorderingAllowed(false);
        jTableProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProdutosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableProdutos);

        jLabel6.setText("Operação");

        jTextFieldCdOperacao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldCdOperacaoFocusLost(evt);
            }
        });

        jBtPesquisaOperacao.setText("Pesquisar");
        jBtPesquisaOperacao.setToolTipText("Pesquisar (F8)");
        jBtPesquisaOperacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtPesquisaOperacaoActionPerformed(evt);
            }
        });

        jTextFieldDsOperacao.setEnabled(false);

        jLabel15.setText("Valor Atendimento");

        jTextFieldVlAtendimento.setDocument(new FormataMoeda());
        jTextFieldVlAtendimento.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldVlAtendimento.setEnabled(false);
        jTextFieldVlAtendimento.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTextFieldVlAtendimentoPropertyChange(evt);
            }
        });

        jTextFieldVlUnitario.setDocument(new FormataMoeda());
        jTextFieldVlUnitario.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldVlUnitario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldVlUnitarioKeyTyped(evt);
            }
        });

        jBtIncluir.setText("Incluir Venda/Compra");
        jBtIncluir.setToolTipText("Incluir Venda/Compra (F1)");
        jBtIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtIncluirActionPerformed(evt);
            }
        });

        jBtGravar.setText("Gravar");
        jBtGravar.setToolTipText("Gravar (Enter)");
        jBtGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtGravarActionPerformed(evt);
            }
        });

        jBtCancelar.setText("Cancelar");
        jBtCancelar.setToolTipText("Cancelar (Esc)");
        jBtCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBotoesLayout = new javax.swing.GroupLayout(jPanelBotoes);
        jPanelBotoes.setLayout(jPanelBotoesLayout);
        jPanelBotoesLayout.setHorizontalGroup(
            jPanelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtIncluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jBtCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelBotoesLayout.setVerticalGroup(
            jPanelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBotoesLayout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addGroup(jPanelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtIncluir)
                    .addComponent(jBtGravar)
                    .addComponent(jBtCancelar)))
        );

        javax.swing.GroupLayout jPanelGravarLayout = new javax.swing.GroupLayout(jPanelGravar);
        jPanelGravar.setLayout(jPanelGravarLayout);
        jPanelGravarLayout.setHorizontalGroup(
            jPanelGravarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGravarLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanelGravarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelGravarLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(78, 78, 78)
                        .addComponent(jLabel2)
                        .addGap(110, 110, 110)
                        .addComponent(jLabel15)
                        .addGap(59, 59, 59)
                        .addComponent(jLabel3)
                        .addGap(188, 188, 188)
                        .addComponent(jLabel4))
                    .addGroup(jPanelGravarLayout.createSequentialGroup()
                        .addComponent(jTextFieldCdVendaCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(115, 115, 115)
                        .addComponent(jTextFieldNrAtendimento, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(115, 115, 115)
                        .addComponent(jTextFieldVlAtendimento, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(jRadioButtonVenda)
                        .addGap(2, 2, 2)
                        .addComponent(jRadioButtonCompra)
                        .addGap(88, 88, 88)
                        .addComponent(jTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5)
                    .addGroup(jPanelGravarLayout.createSequentialGroup()
                        .addComponent(jTextFieldCdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonPesquisarCliente)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7)
                    .addGroup(jPanelGravarLayout.createSequentialGroup()
                        .addComponent(jTextFieldCdForma, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonPesquisarForma)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldForma, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6)
                    .addGroup(jPanelGravarLayout.createSequentialGroup()
                        .addComponent(jTextFieldCdOperacao, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBtPesquisaOperacao)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldDsOperacao, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8)
                    .addGroup(jPanelGravarLayout.createSequentialGroup()
                        .addComponent(jTextFieldCdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonPesquisarProduto)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelGravarLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addGap(470, 470, 470)
                        .addComponent(jLabel12))
                    .addGroup(jPanelGravarLayout.createSequentialGroup()
                        .addComponent(jSpnQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldVlUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jTextFieldTotalProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(186, 186, 186)
                        .addComponent(jBtAdicionar)
                        .addGap(18, 18, 18)
                        .addComponent(jBtRemover)
                        .addGap(82, 82, 82)
                        .addComponent(jTextFieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelGravarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addComponent(jPanelBotoes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelGravarLayout.setVerticalGroup(
            jPanelGravarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelGravarLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanelGravarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel15)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(2, 2, 2)
                .addGroup(jPanelGravarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonVenda)
                    .addComponent(jRadioButtonCompra)
                    .addGroup(jPanelGravarLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanelGravarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCdVendaCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNrAtendimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldVlAtendimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20)
                .addComponent(jLabel5)
                .addGap(6, 6, 6)
                .addGroup(jPanelGravarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonPesquisarCliente)
                    .addGroup(jPanelGravarLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanelGravarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(6, 6, 6)
                .addGroup(jPanelGravarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelGravarLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jTextFieldCdForma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonPesquisarForma)
                    .addGroup(jPanelGravarLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jTextFieldForma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(6, 6, 6)
                .addGroup(jPanelGravarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtPesquisaOperacao)
                    .addGroup(jPanelGravarLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanelGravarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCdOperacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldDsOperacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(14, 14, 14)
                .addComponent(jLabel8)
                .addGap(6, 6, 6)
                .addGroup(jPanelGravarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonPesquisarProduto)
                    .addGroup(jPanelGravarLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanelGravarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanelGravarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(3, 3, 3)
                .addGroup(jPanelGravarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtAdicionar)
                    .addComponent(jBtRemover)
                    .addGroup(jPanelGravarLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanelGravarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSpnQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldVlUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldTotalProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jPanelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPaneVendaCompra.addTab("Gravar Venda/Compra", jPanelGravar);

        jTableVendaCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cd VendaCompra", "Nr Atendimento", "Código", "Cliente/Fornecedor", "Cd Forma", "Data", "Valor Total", "Operação"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableVendaCompra.setComponentPopupMenu(jPopupMenuVendaCompra);
        jTableVendaCompra.getTableHeader().setReorderingAllowed(false);
        jTableVendaCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableVendaCompraMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableVendaCompra);

        jLabel13.setText("Filtro da Consulta");

        jComboBoxConsulta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Geral", "Código", "Cliente", "Fornecedor", "Tipo" }));
        jComboBoxConsulta.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBoxConsultaPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jTableConta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cd Conta", "Cd Venda Compra", "Forma de Pagamento", "Tipo", "Valor", "Data Vencimento", "Data Pago", "Pago"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableConta.setComponentPopupMenu(jPopupMenuConta);
        jTableConta.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(jTableConta);

        jTableProdutosVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código do Produto", "Produto", "Valor Unitário", "Quantidade", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableProdutosVenda.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(jTableProdutosVenda);

        jBtPesquisar.setText("Pesquisar");
        jBtPesquisar.setToolTipText("Pesquisar (F5)");
        jBtPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtPesquisarActionPerformed(evt);
            }
        });

        jLabel14.setText("Tipo");

        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Venda", "Compra" }));
        jComboBoxTipo.setEnabled(false);

        jLabel16.setText("Ocultar registros inativos ?");

        buttonGroupSituacao.add(jRadioBtSim);
        jRadioBtSim.setSelected(true);
        jRadioBtSim.setText("Sim");
        jRadioBtSim.setToolTipText("Sim (Ctrl + S)");

        buttonGroupSituacao.add(jRadioButtonNao);
        jRadioButtonNao.setText("Não");
        jRadioButtonNao.setToolTipText("Não (Ctrl + N)");

        jBtRelatorio.setText("Relatório");
        jBtRelatorio.setToolTipText("Relatório (F6)");
        jBtRelatorio.setEnabled(false);
        jBtRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtRelatorioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelConsultaLayout = new javax.swing.GroupLayout(jPanelConsulta);
        jPanelConsulta.setLayout(jPanelConsultaLayout);
        jPanelConsultaLayout.setHorizontalGroup(
            jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelConsultaLayout.createSequentialGroup()
                        .addGroup(jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jComboBoxConsulta, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelConsultaLayout.createSequentialGroup()
                                .addComponent(jRadioBtSim)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonNao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBtPesquisar)
                                .addGap(18, 18, 18)
                                .addComponent(jBtRelatorio))
                            .addGroup(jPanelConsultaLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        jPanelConsultaLayout.setVerticalGroup(
            jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtPesquisar)
                    .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioBtSim)
                    .addComponent(jRadioButtonNao)
                    .addComponent(jBtRelatorio))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPaneVendaCompra.addTab("Consulta", jPanelConsulta);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneVendaCompra, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneVendaCompra)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtAdicionarActionPerformed
        if (jTextFieldCdProduto.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor informe o produto que deseja adicionar!");
            jTextFieldCdProduto.grabFocus();
        } else {
            adicionarProdutos();
            edit.setLinhas(linhasAtendimento);
            edit.setTipo("VENDA_COMPRA");
            edit.editarTabela(jTableProdutos);
            preencherTotal();
        }
    }//GEN-LAST:event_jBtAdicionarActionPerformed

    private void jBtRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtRemoverActionPerformed
        int linha = jTableProdutos.getSelectedRow();
        if (linha >= 0) {
            if (jTableProdutos.getSelectedRow() < linhasAtendimento) {
                JOptionPane.showMessageDialog(null, "Este produto pertence ao atendimento e não pode ser removido!");
            } else {
                int opcao = JOptionPane.showConfirmDialog(null, "Deseja realmente remover este produto ?",
                        "Remover Produto", JOptionPane.YES_NO_OPTION);
                if (opcao == JOptionPane.YES_OPTION) {
                    DefaultTableModel tabela = (DefaultTableModel) jTableProdutos.getModel();
                    tabela.removeRow(linha);
                    preencherTotal();
                }
            }
        }
    }//GEN-LAST:event_jBtRemoverActionPerformed

    private void jComboBoxConsultaPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBoxConsultaPopupMenuWillBecomeInvisible
        if (jComboBoxConsulta.getSelectedIndex() == 4) {
            jComboBoxTipo.setEnabled(true);
        } else {
            jComboBoxTipo.setEnabled(false);
        }
    }//GEN-LAST:event_jComboBoxConsultaPopupMenuWillBecomeInvisible

    private void jButtonPesquisarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarClienteActionPerformed
        ConsultaClienteFornecedor consulta = new ConsultaClienteFornecedor(this, true, jRadioButtonVenda.isSelected());
        consulta.setVisible(true);

        consulta.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {

                if (jRadioButtonVenda.isSelected()) {
                    try {
                        jTextFieldCdCliente.setText(venda.getCliente().getCdCliente().toString());
                        jTextFieldNomeCliente.setText(venda.getCliente().getPessoa().getNome());
                    } catch (NullPointerException ex) {
                        jTextFieldCdCliente.setText("");
                        jTextFieldNomeCliente.setText("");
                    }
                } else {
                    try {
                        jTextFieldCdCliente.setText(venda.getFornecedor().getCdFornecedor().toString());
                        jTextFieldNomeCliente.setText(venda.getFornecedor().getPessoa().getNome());
                    } catch (NullPointerException ex) {
                        jTextFieldCdCliente.setText("");
                        jTextFieldNomeCliente.setText("");
                    }
                }
            }
        });
    }//GEN-LAST:event_jButtonPesquisarClienteActionPerformed

    private void jButtonPesquisarFormaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarFormaActionPerformed
        ConsultaForma csForma = new ConsultaForma(this, true);
        csForma.setVisible(true);

        csForma.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {

                if (venda.getForma().getCdForma() == 0) {
                    jTextFieldCdForma.setText("");
                    jTextFieldForma.setText("");
                } else {
                    jTextFieldCdForma.setText(venda.getForma().getCdForma().toString());
                    jTextFieldForma.setText(venda.getForma().getDsForma());
                }
            }
        });
    }//GEN-LAST:event_jButtonPesquisarFormaActionPerformed

    private void jBtIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtIncluirActionPerformed
        limparCampos();
        jTextFieldData.setText(rdata.retornaDataAtual());
        jTextFieldCdCliente.grabFocus();
        rotina = Rotinas.incluir;
        validaEstadoCampos();
        jRadioButtonVendaActionPerformed(null);
    }//GEN-LAST:event_jBtIncluirActionPerformed

    private void jTextFieldCdClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCdClienteFocusLost
        if (!jTextFieldCdCliente.getText().equals("")) {
            try {
                int cd = Integer.parseInt(jTextFieldCdCliente.getText());
                if (jRadioButtonVenda.isSelected()) {
                    retornaCliente(cd);
                } else {
                    retornaFornecedor(cd);
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Informe um código válido para consultar!");
                limparCamposClienteFornecedor();
            }
        }
    }//GEN-LAST:event_jTextFieldCdClienteFocusLost

    private void jTextFieldNrAtendimentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNrAtendimentoFocusLost

    }//GEN-LAST:event_jTextFieldNrAtendimentoFocusLost

    private void jTextFieldCdFormaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCdFormaFocusLost
        if (!jTextFieldCdForma.getText().equals("")) {
            try {
                venda.getForma().setCdForma(Integer.parseInt(jTextFieldCdForma.getText()));
                venda.getForma().retornaForma(venda.getForma());

                if (venda.getForma().getDsForma().equals("")) {
                    jTextFieldCdForma.setText("");
                    jTextFieldForma.setText("");
                    jTextFieldCdForma.grabFocus();
                } else {
                    jTextFieldForma.setText(venda.getForma().getDsForma());
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Informe um código para pesquisar!");
                jTextFieldCdForma.setText("");
                jTextFieldForma.setText("");
            }
        }
    }//GEN-LAST:event_jTextFieldCdFormaFocusLost

    private void jBtPesquisaOperacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtPesquisaOperacaoActionPerformed
        ConsultaOperacao csOperacao = new ConsultaOperacao(this, true);
        csOperacao.setVisible(true);

        csOperacao.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                if (venda.getOperacao().getCdOperacao() == 0) {
                    jTextFieldCdOperacao.setText("");
                    jTextFieldDsOperacao.setText("");
                } else {
                    jTextFieldCdOperacao.setText(venda.getOperacao().getCdOperacao().toString());
                    jTextFieldDsOperacao.setText(venda.getOperacao().getDsOperacao());
                }
            }
        });
    }//GEN-LAST:event_jBtPesquisaOperacaoActionPerformed

    private void jTextFieldCdProdutoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCdProdutoFocusLost
        if (!jTextFieldCdProduto.getText().equals("")) {
            try {
                venda.getVendaAtendimento().getAtendimento().getAtdProdutos().getProduto()
                        .setCdProduto(Integer.parseInt(jTextFieldCdProduto.getText()));
                // se for uma venda retorna apenas os produtos disponíveis
                if (tipo.equals("venda")) {
                    venda.getVendaAtendimento().getAtendimento().getAtdProdutos().getProduto().
                            retornaProduto(venda.getVendaAtendimento().getAtendimento().getAtdProdutos().getProduto(), false);
                } // senão retorna todos os produtos
                else {
                    venda.getVendaAtendimento().getAtendimento().getAtdProdutos().getProduto().
                            retornaProduto(venda.getVendaAtendimento().getAtendimento().getAtdProdutos().getProduto(), true);
                }

                if (venda.getVendaAtendimento().getAtendimento().getAtdProdutos().getProduto()
                        .getDsProduto().equals("")) {
                    jTextFieldCdProduto.setText("");
                    jTextFieldProduto.setText("");
                    jTextFieldCdProduto.grabFocus();
                } else {
                    preencherProduto();
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Por favor informe um código!");
                jTextFieldCdProduto.setText("");
                jTextFieldProduto.setText("");
                jTextFieldCdProduto.grabFocus();
            }
        }
    }//GEN-LAST:event_jTextFieldCdProdutoFocusLost

    private void jSpnQuantidadePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jSpnQuantidadePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jSpnQuantidadePropertyChange

    private void jSpnQuantidadeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpnQuantidadeStateChanged
        try {
            double preco = Double.parseDouble(jTextFieldVlUnitario.getText()
                    .replace(".", "").replace(",", "."));
            if (preco > 0) {
                preencherTotalProduto();
            }
        } catch (NumberFormatException ex) {
            jTextFieldTotalProduto.setText("");
        }
    }//GEN-LAST:event_jSpnQuantidadeStateChanged

    private void jButtonPesquisarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarProdutoActionPerformed
        ConsultaProduto csProd = new ConsultaProduto(this, true, jRadioButtonCompra.isSelected());
        csProd.setVisible(true);

        csProd.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {

                if (venda.getVendaAtendimento().getAtendimento()
                        .getAtdProdutos().getProduto().getCdProduto() == 0) {
                    jTextFieldProduto.setText("");
                    jTextFieldCdProduto.setText("");
                } else {
                    jTextFieldCdProduto.setText(venda.getVendaAtendimento().getAtendimento()
                            .getAtdProdutos().getProduto().getCdProduto().toString());
                    venda.getVendaAtendimento().getAtendimento().getAtdProdutos().getProduto()
                            .retornaProduto(venda.getVendaAtendimento().getAtendimento().getAtdProdutos().getProduto(), jRadioButtonCompra.isSelected());
                    preencherProduto();
                }
            }
        });
    }//GEN-LAST:event_jButtonPesquisarProdutoActionPerformed

    private void jTextFieldVlAtendimentoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTextFieldVlAtendimentoPropertyChange
        preencherTotal();
    }//GEN-LAST:event_jTextFieldVlAtendimentoPropertyChange

    private void jBtGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtGravarActionPerformed
        int linhas = jTableProdutos.getRowCount();
        if (jTextFieldCdCliente.getText().equals("")) {
            if (jRadioButtonVenda.isSelected()) {
                JOptionPane.showMessageDialog(null, "O cliente é obrigatório!");
            } else {
                JOptionPane.showMessageDialog(null, "O fornecedor é obrigatório!");
            }
            jTextFieldCdCliente.grabFocus();
        } 
        
        else if (jTextFieldCdForma.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "A forma de pagamento é obrigatória!");
            jTextFieldCdForma.grabFocus();
        } 
        
        else if (jTextFieldCdOperacao.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "A operação é obrigatória!");
            jTextFieldCdOperacao.grabFocus();
        }
        
        else if (linhas == 0) {
            JOptionPane.showMessageDialog(null, "Por favor adicione produtos na tabela!");
        } 
        
        else {
            gravarVendaCompra();
            //JOptionPane.showMessageDialog(null, "A " + tipo + " foi gravada com sucesso!");
            
            rotina = Rotinas.padrao;
            validaEstadoCampos();
        }
    }//GEN-LAST:event_jBtGravarActionPerformed

    private void jBtCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtCancelarActionPerformed
        if (jTableProdutos.getRowCount() > 0) {
            int escolha = JOptionPane.showConfirmDialog(null, "Deseja realmente cancelar a " + tipo + " ?",
                    "Cancelar " + tipo, JOptionPane.YES_NO_OPTION);
            if (escolha == JOptionPane.YES_OPTION) {
                rotina = Rotinas.padrao;
                validaEstadoCampos();
                limparCampos();
            }
        } else {
            rotina = Rotinas.padrao;
            validaEstadoCampos();
            limparCampos();
        }
    }//GEN-LAST:event_jBtCancelarActionPerformed

    private void jTextFieldCdOperacaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCdOperacaoFocusLost
        if (!jTextFieldCdOperacao.getText().equals("")) {
            try {
                venda.getOperacao().setCdOperacao(Integer.parseInt(jTextFieldCdOperacao.getText()));
                venda.getOperacao().retornaOperacao(venda.getOperacao());
                if (venda.getOperacao().getDsOperacao().equals("")) {
                    jTextFieldCdOperacao.setText("");
                    jTextFieldCdOperacao.setText("");
                    jTextFieldCdOperacao.grabFocus();
                } else {
                    jTextFieldDsOperacao.setText(venda.getOperacao().getDsOperacao());
                }

            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Por favor informe um código!");
                jTextFieldCdOperacao.setText("");
                jTextFieldCdOperacao.setText("");
                jTextFieldCdOperacao.grabFocus();
            }
        }
    }//GEN-LAST:event_jTextFieldCdOperacaoFocusLost

    private void jRadioButtonVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonVendaActionPerformed
        jTextFieldCdOperacao.setText("1");
        tipo = "venda";
        jTextFieldCdOperacaoFocusLost(null);
        if (!jTextFieldCdProduto.getText().equals("")) {
            venda.getVendaAtendimento().getAtendimento().getAtdProdutos().getProduto().
                    retornaProduto(venda.getVendaAtendimento().getAtendimento().getAtdProdutos().getProduto(), false);
            preencherProduto();
        }
    }//GEN-LAST:event_jRadioButtonVendaActionPerformed

    private void jRadioButtonCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCompraActionPerformed
        jTextFieldCdOperacao.setText("2");
        tipo = "compra";
        jTextFieldCdOperacaoFocusLost(null);
        if (!jTextFieldCdProduto.getText().equals("")) {
            venda.getVendaAtendimento().getAtendimento().getAtdProdutos().getProduto().
                    retornaProduto(venda.getVendaAtendimento().getAtendimento().getAtdProdutos().getProduto(), false);
            preencherProduto();
        }
    }//GEN-LAST:event_jRadioButtonCompraActionPerformed

    private void jTableProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProdutosMouseClicked
    }//GEN-LAST:event_jTableProdutosMouseClicked

    private void jBtPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtPesquisarActionPerformed
        PreencherTabela preencher = new PreencherTabela();
        preencher.FormatarJtable(jTableVendaCompra, new int[]{110, 90, 50, 280, 60, 70, 70, 150});
        switch (jComboBoxConsulta.getSelectedIndex()) {
            case 0:
                preencher.PreencherJtableGenerico(jTableVendaCompra, venda.consultarGeral(jRadioBtSim.isSelected()));
                report.setConsulta(preencher.getConsulta());
                editaBotao(preencher.Vazia());
            break;

            case 1:
                try {
                    venda.setCdVendaCompra(Integer.parseInt(jTextFieldConsulta.getText()));
                    preencher.PreencherJtableGenerico(jTableVendaCompra, venda.consultarCdVendaCompra(venda, jRadioBtSim.isSelected()));
                    report.setConsulta(preencher.getConsulta());
                    editaBotao(preencher.Vazia());
                } 
                catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(null, "Informe um código para pesquisar!");
                    editaBotao(true);
                }
            break;

            case 2:
                venda.getCliente().getPessoa().setNome(jTextFieldConsulta.getText().toUpperCase());
                preencher.PreencherJtableGenerico(jTableVendaCompra, venda.consultarCliente(venda, jRadioBtSim.isSelected()));
                report.setConsulta(preencher.getConsulta());
                editaBotao(preencher.Vazia());
            break;

            case 3:
                venda.getFornecedor().getPessoa().setNome(jTextFieldConsulta.getText().toUpperCase());
                preencher.PreencherJtableGenerico(jTableVendaCompra, venda.consultarFornecedor(venda, jRadioBtSim.isSelected()));
                report.setConsulta(preencher.getConsulta());
                editaBotao(preencher.Vazia());
            break;

            default:
                String operacao = jComboBoxTipo.getSelectedItem().toString().toUpperCase();
                venda.getOperacao().setDsOperacao(operacao);
                preencher.PreencherJtableGenerico(jTableVendaCompra, venda.consultarPorTipo(venda, jRadioBtSim.isSelected()));
                report.setConsulta(preencher.getConsulta());
                editaBotao(preencher.Vazia());
        }
    }//GEN-LAST:event_jBtPesquisarActionPerformed

    private void jTableVendaCompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableVendaCompraMouseClicked
        preencherTabela();
    }//GEN-LAST:event_jTableVendaCompraMouseClicked

    private void jTextFieldCdVendaCompraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCdVendaCompraFocusLost
        if (!jTextFieldCdVendaCompra.getText().equals("")) {
            try {
                venda.setCdVendaCompra(Integer.parseInt(jTextFieldCdVendaCompra.getText()));
                venda.retornaVendaCompra(venda);
                if (venda.getCdVendaCompra() == 0) {
                    jBtCancelarActionPerformed(null);
                } else {
                    switch (venda.getVendaAtendimento().getAtendimento().getNrAtendimento()) {
                        case 0:
                            jTextFieldNrAtendimento.setText("");
                            jTextFieldVlAtendimento.setText("");
                            break;

                        default:
                            jTextFieldNrAtendimento.setText(venda.getVendaAtendimento().getAtendimento().getNrAtendimento().toString());
                            venda.getVendaAtendimento().getAtendimento().retornaAtendimento(venda.getVendaAtendimento().getAtendimento());
                            jTextFieldVlAtendimento.setText(decimal.retornaDecimal(venda.getVendaAtendimento().
                                    getAtendimento().getVlTotal(), 6));
                    }
                    // preenche os campos retornados
                    switch (venda.getOperacao().getDsOperacao()) {
                        case "VENDA":
                            tipo = "Venda";
                            jRadioButtonVenda.setSelected(true);
                            jTextFieldCdOperacao.setText("1");
                            jTextFieldCdOperacaoFocusLost(null);
                            break;

                        default:
                            tipo = "Compra";
                            jRadioButtonCompra.setSelected(true);
                            jTextFieldCdOperacao.setText("2");
                            jTextFieldCdOperacaoFocusLost(null);
                    }
                    jTextFieldData.setText(venda.getDtVenda());
                    jTextFieldCdCliente.setText(venda.getCliente().getPessoa().getCdPessoa().toString());
                    jTextFieldNomeCliente.setText(venda.getCliente().getPessoa().getNome());
                    jTextFieldCdForma.setText(venda.getForma().getCdForma().toString());
                    jTextFieldCdFormaFocusLost(null);
                    jTextFieldTotal.setText(decimal.retornaDecimal(venda.getVlTotal(), 6));

                    PreencherTabela preencher = new PreencherTabela();
                    preencher.FormatarJtable(jTableProdutos, new int[]{150, 280, 150, 150, 150});
                    venda.getVcProdutos().setCdVendaCompra(venda.getCdVendaCompra());
                    preencher.PreencherJtableGenerico(jTableProdutos, venda.getVcProdutos().consultarProdutos(venda.getVcProdutos()));
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Por favor informe um código!");
                jBtCancelarActionPerformed(null);
            }
        }
    }//GEN-LAST:event_jTextFieldCdVendaCompraFocusLost

    private void jMenuItemCarregarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCarregarDadosActionPerformed
        int linha = jTableVendaCompra.getSelectedRow();
        if (linha >= 0){
            String cd = jTableVendaCompra.getValueAt(linha, 0).toString();
            jBtIncluirActionPerformed(evt);
            jTextFieldCdVendaCompra.setText(cd);
            jTextFieldCdVendaCompraFocusLost(null);
            jTabbedPaneVendaCompra.setSelectedIndex(0);
        }
    }//GEN-LAST:event_jMenuItemCarregarDadosActionPerformed

    private void jMenuItemExibirParcelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExibirParcelasActionPerformed
        int linha = jTableConta.getSelectedRow();
        if (linha >=0){
            int cd = Integer.parseInt(jTableConta.getValueAt(linha, 0).toString());
        CadastroContas cadConta = new CadastroContas();
        cadConta.setVisible(true);
        cadConta.exibirConta(cd);
        }
        
    }//GEN-LAST:event_jMenuItemExibirParcelasActionPerformed

    private void jBtRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtRelatorioActionPerformed
        report.setSubreport(true);
        report.setTabela("VENDA_COMPRA");
        report.gerarRelatorio(report);     
        jBtPesquisarActionPerformed(null);
    }//GEN-LAST:event_jBtRelatorioActionPerformed

    private void jTextFieldVlUnitarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldVlUnitarioKeyTyped
        new ValidaCampos().validaCamposApenasNumeros(evt);
    }//GEN-LAST:event_jTextFieldVlUnitarioKeyTyped

    private void jPopupMenuVendaCompraPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jPopupMenuVendaCompraPopupMenuWillBecomeVisible
        int linha = jTableVendaCompra.getSelectedRow();
        if (linha >= 0){
            venda.setCdVendaCompra(Integer.parseInt(jTableVendaCompra.getValueAt(linha, 0).toString()));
            jMenuItemExcluir.setEnabled(venda.permiteExclusao(venda));
            if (jMenuItemExcluir.isEnabled()){
                jMenuItemExcluir.setEnabled(valida.pExclusao.equals("S"));
            }
        }
    }//GEN-LAST:event_jPopupMenuVendaCompraPopupMenuWillBecomeVisible

    private void jMenuItemExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExcluirActionPerformed
        int linha = jTableVendaCompra.getSelectedRow();
        if (linha >=0){
            tipo = jTableVendaCompra.getValueAt(linha, 7).toString();
            int opcao = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir esta " + tipo + " ?",
                    "Excluir " + tipo, JOptionPane.YES_NO_OPTION);
            if (opcao == JOptionPane.YES_OPTION){
                venda.setCdVendaCompra(Integer.parseInt(jTableVendaCompra.getValueAt(linha, 0).toString()));
                venda.excluir(venda);
                jBtPesquisarActionPerformed(null);
            }
        }
    }//GEN-LAST:event_jMenuItemExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVendaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVendaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVendaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVendaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaVendaCompra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupSituacao;
    private javax.swing.ButtonGroup buttonGroupTicket;
    private javax.swing.ButtonGroup buttonGroupTipo;
    private javax.swing.JButton jBtAdicionar;
    private javax.swing.JButton jBtCancelar;
    private javax.swing.JButton jBtGravar;
    private javax.swing.JButton jBtIncluir;
    private javax.swing.JButton jBtPesquisaOperacao;
    private javax.swing.JButton jBtPesquisar;
    private javax.swing.JButton jBtRelatorio;
    private javax.swing.JButton jBtRemover;
    private javax.swing.JButton jButtonPesquisarCliente;
    private javax.swing.JButton jButtonPesquisarForma;
    private javax.swing.JButton jButtonPesquisarProduto;
    private javax.swing.JComboBox jComboBoxConsulta;
    private javax.swing.JComboBox jComboBoxTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItemCarregarDados;
    private javax.swing.JMenuItem jMenuItemExcluir;
    private javax.swing.JMenuItem jMenuItemExibirParcelas;
    private javax.swing.JPanel jPanelBotoes;
    private javax.swing.JPanel jPanelConsulta;
    private javax.swing.JPanel jPanelGravar;
    private javax.swing.JPopupMenu jPopupMenuConta;
    private javax.swing.JPopupMenu jPopupMenuVendaCompra;
    private javax.swing.JRadioButton jRadioBtSim;
    private javax.swing.JRadioButton jRadioButtonCompra;
    private javax.swing.JRadioButton jRadioButtonNao;
    private javax.swing.JRadioButton jRadioButtonVenda;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSpinner jSpnQuantidade;
    private javax.swing.JTabbedPane jTabbedPaneVendaCompra;
    private javax.swing.JTable jTableConta;
    private javax.swing.JTable jTableProdutos;
    private javax.swing.JTable jTableProdutosVenda;
    private javax.swing.JTable jTableVendaCompra;
    private javax.swing.JTextField jTextFieldCdCliente;
    private javax.swing.JTextField jTextFieldCdForma;
    private javax.swing.JTextField jTextFieldCdOperacao;
    private javax.swing.JTextField jTextFieldCdProduto;
    private javax.swing.JTextField jTextFieldCdVendaCompra;
    private javax.swing.JTextField jTextFieldConsulta;
    private javax.swing.JTextField jTextFieldData;
    private javax.swing.JTextField jTextFieldDsOperacao;
    private javax.swing.JTextField jTextFieldForma;
    private javax.swing.JTextField jTextFieldNomeCliente;
    private javax.swing.JTextField jTextFieldNrAtendimento;
    private javax.swing.JTextField jTextFieldProduto;
    private javax.swing.JTextField jTextFieldTotal;
    private javax.swing.JTextField jTextFieldTotalProduto;
    private javax.swing.JTextField jTextFieldVlAtendimento;
    private javax.swing.JTextField jTextFieldVlUnitario;
    // End of variables declaration//GEN-END:variables

    private void preencherProduto() {
        jTextFieldProduto.setText(venda.getVendaAtendimento().getAtendimento().getAtdProdutos()
                .getProduto().getDsProduto());
        int max;
        if (jRadioButtonVenda.isSelected()) {
            max = venda.getVendaAtendimento().getAtendimento().getAtdProdutos()
                    .getProduto().getQtAtual();
        } else {
            max = 500;
        }

        SpinnerNumberModel model = new SpinnerNumberModel(1, 1, max, 1);
        jSpnQuantidade.setModel(model);
        jTextFieldVlUnitario.setText(decimal.retornaDecimal(venda.getVendaAtendimento().getAtendimento()
                .getAtdProdutos().getProduto().getVlProduto(), 6));
        preencherTotalProduto();
    }

    private void preencherTotalProduto() {
        double preco = Double.parseDouble(jTextFieldVlUnitario.getText()
                .replace(".", "").replace(",", "."));

        int qt = Integer.parseInt(jSpnQuantidade.getValue().toString());
        jTextFieldTotalProduto.setText(decimal.retornaDecimal(qt * preco, 6));

    }

    private void adicionarProdutos() {
        DefaultTableModel tabela = (DefaultTableModel) jTableProdutos.getModel();
        SpinnerNumberModel spn = (SpinnerNumberModel) jSpnQuantidade.getModel();

        String cd = jTextFieldCdProduto.getText();
        double valor = Double.parseDouble(jTextFieldVlUnitario.getText()
                .replace(".", "").replace(",", "."));
        int quantidade = Integer.parseInt(jSpnQuantidade.getValue().toString());
        int max = (int) spn.getMaximum();
        int linhas = jTableProdutos.getRowCount();

        boolean repetido = false;

        int posicao = linhas;

        if (linhas < 0) {
            tabela.setNumRows(linhas + 1);
        } else {
            for (int i = 0; i < linhas; i++) {
                if (jTableProdutos.getValueAt(i, 0).toString().equals(cd) && i >= linhasAtendimento) {
                    repetido = true;
                    posicao = i;
                }
            }

            if (repetido) {
                int qtTabela = Integer.parseInt(jTableProdutos.getValueAt(posicao, 3).toString());

                if (quantidade + qtTabela > max) {
                    JOptionPane.showMessageDialog(null, "Quantidade indisponível para este produto!");
                    quantidade = qtTabela;
                } else {
                    quantidade = quantidade + qtTabela;
                }
            } else {
                tabela.setNumRows(linhas + 1);
            }
        }
        tabela.setValueAt(cd, posicao, 0);
        tabela.setValueAt(jTextFieldProduto.getText(), posicao, 1);
        tabela.setValueAt(decimal.retornaDecimal(valor), posicao, 2);
        tabela.setValueAt(quantidade, posicao, 3);
        double total = quantidade * valor;
        tabela.setValueAt(decimal.retornaDecimal(total), posicao, 4);
    }

    public void CarregarAtendimento(JTable tabela, AtendimentoMesa atd) {
        jBtIncluirActionPerformed(null);
        DefaultTableModel model = (DefaultTableModel) tabela.getModel();
        jTableProdutos.setModel(model);
        jTextFieldNrAtendimento.setText(atd.getNrAtendimento().toString());
        jTextFieldData.setText(atd.getDtAtendimento());
        jTextFieldTotal.setText(decimal.retornaDecimal(atd.getVlTotal(), 6));
        jTextFieldVlAtendimento.setText(decimal.retornaDecimal(atd.getVlTotal(), 6));

        linhasAtendimento = model.getRowCount();
        jRadioButtonCompra.setEnabled(false);
        edit.editarTabela(jTableProdutos);
        edit.setTipo("VENDA_COMPRA");
        edit.setLinhas(linhasAtendimento);
    }

    public void CarregarAtendimento(AtendimentoMesa atd) {
        jBtIncluirActionPerformed(null);
        atd.getAtdProdutos().setNrAtendimento(atd.getNrAtendimento());
        jTextFieldNrAtendimento.setText(atd.getNrAtendimento().toString());
        jTextFieldData.setText(atd.getDtAtendimento());
        jTextFieldTotal.setText(decimal.retornaDecimal(atd.getVlTotal(), 6));
        jTextFieldVlAtendimento.setText(decimal.retornaDecimal(atd.getVlTotal(), 6));

        PreencherTabela preencher = new PreencherTabela();
        preencher.FormatarJtable(jTableProdutos, new int[]{150, 280, 150, 150, 150});

        preencher.PreencherJtableGenerico(jTableProdutos, atd.getAtdProdutos().consultarProdutos(atd.getAtdProdutos()));

        linhasAtendimento = jTableProdutos.getRowCount();
        jRadioButtonCompra.setEnabled(false);
        edit.editarTabela(jTableProdutos);
        edit.setTipo("VENDA_COMPRA");
        edit.setLinhas(linhasAtendimento);
    }

    private void retornaCliente(int cd) {
        venda.getCliente().setCdCliente(cd);
        venda.getCliente().retornaCliente(venda.getCliente());
        if (venda.getCliente().getPessoa().getNome().equals("")) {
            limparCamposClienteFornecedor();
        } else {
            jTextFieldNomeCliente.setText(venda.getCliente().getPessoa().getNome());
        }
    }

    private void limparCamposClienteFornecedor() {
        jTextFieldCdCliente.setText("");
        jTextFieldNomeCliente.setText("");
        jTextFieldCdCliente.grabFocus();
    }

    private void retornaFornecedor(int cd) {
        venda.getFornecedor().setCdFornecedor(cd);
        venda.getFornecedor().retornaFornecedor(venda.getFornecedor());
        if (venda.getFornecedor().getPessoa().getNome().equals("")) {
            limparCamposClienteFornecedor();
        } else {
            jTextFieldNomeCliente.setText(venda.getFornecedor().getPessoa().getNome());
        }
    }

    private void preencherTotal() {
        double vlTotal = venda.retornaTotalVendaCompra(jTableProdutos);
        jTextFieldTotal.setText(decimal.retornaDecimal(vlTotal, 6));
    }

    private void gravarVendaCompra() {
        if (jRadioButtonVenda.isSelected()) {
            venda.getCliente().setCdCliente(Integer.parseInt(jTextFieldCdCliente.getText()));
        } else {
            venda.getFornecedor().setCdFornecedor(Integer.parseInt(jTextFieldCdCliente.getText()));
        }

        venda.getForma().setCdForma(Integer.parseInt(jTextFieldCdForma.getText()));
        venda.getOperacao().setCdOperacao(Integer.parseInt(jTextFieldCdOperacao.getText()));
        venda.getOperacao().setDsOperacao(jTextFieldDsOperacao.getText());
        venda.setDtVenda(jTextFieldData.getText());
        venda.setVlTotal(Double.parseDouble(jTextFieldTotal.getText().replace(".", "").replace(",", ".")));
        //venda.setPago("N");

        venda.incluir(venda);
        jTextFieldCdVendaCompra.setText(venda.getCdVendaCompra().toString());

        // grava os produtos da venda/compra
        int linhas = jTableProdutos.getRowCount();

        venda.getVcProdutos().setCdVendaCompra(venda.getCdVendaCompra());

        for (int i = 0; i < linhas; i++) {

            int cd = Integer.parseInt(jTableProdutos.getValueAt(i, 0).toString());
            double vl = Double.parseDouble(jTableProdutos.getValueAt(i, 2).toString());
            int qt = Integer.parseInt(jTableProdutos.getValueAt(i, 3).toString());

            venda.getVcProdutos().getProduto().setCdProduto(cd);
            venda.getVcProdutos().setValor(vl);
            venda.getVcProdutos().setQuantidade(qt);

            venda.getVcProdutos().incluir(venda.getVcProdutos());

            // atualiza a quantidade atual dos produtos 
            venda.getVcProdutos().getProduto().retornaProduto(venda.getVcProdutos().getProduto(), true);
            int qtAnterior = venda.getVcProdutos().getProduto().getQtAtual();

            if (i < linhasAtendimento) { // se for um produto do atendimento
                qtAnterior = qtAnterior + Integer.parseInt(jTableProdutos.getValueAt(i, 3).toString());
            } else {  // se for um produto apenas da venda compra
                if (jRadioButtonVenda.isSelected()) {
                    venda.getVcProdutos().getProduto().setQtAtual(qtAnterior - qt);
                } else {
                    venda.getVcProdutos().getProduto().setQtAtual(qtAnterior + qt);
                }
                venda.getVcProdutos().getProduto().alteraQtAtual(venda.getVcProdutos().getProduto());
            }

            // se a operacao gera movimentação de estoque
            venda.getOperacao().retornaOperacao(venda.getOperacao());
            if (venda.getOperacao().getMovEstoque().equals("SIM")) {
                gravarMovEstoque(qtAnterior);
            }
        }

        //se possuir um atendimento grava a venda com atendimento
        if (!jTextFieldNrAtendimento.getText().equals("")) {
            try {
                venda.getVendaAtendimento().getAtendimento().setNrAtendimento(Integer.parseInt(jTextFieldNrAtendimento.getText()));
                venda.getVendaAtendimento().setCdVenda(venda.getCdVendaCompra());
                venda.getVendaAtendimento().incluir(venda.getVendaAtendimento());
            } catch (NumberFormatException ex) {

            }
        }
        
        // se a operação gera movimento financeiro
        if (venda.getOperacao().getMovFinanceiro().equals("SIM")) {
            gerarContas();

            // mostra as parcelas
            ConsultaParcelas consulta = new ConsultaParcelas();
            consulta.setVisible(true);
            consulta.rotina = 1;
            consulta.exibirParcelas();
            
            consulta.addWindowListener(new java.awt.event.WindowAdapter() {
                
                @Override
                public void windowClosed(WindowEvent evt) {
                    limparCampos();
                    
                    report.setConsulta(venda.consultarTicket(venda));
                    report.setSubreport(false);
                    report.setTabela("TICKET_VENDA_COMPRA");
                    report.iniciarSplash(report);
                }
            });
        }
    }

    private void gravarMovEstoque(int anterior) {
        MovEstoque mov = new MovEstoque();

        mov.setCdVendaCompra(venda.getCdVendaCompra());
        mov.setCdProduto(venda.getVcProdutos().getProduto().getCdProduto());
        mov.setQtAnterior(anterior);
        mov.setQtAtual(venda.getVcProdutos().getProduto().getQtAtual());
        mov.setVlProduto(venda.getVcProdutos().getProduto().getVlProduto());
        mov.setVlCusto(venda.getVcProdutos().getProduto().getVlCusto());
        mov.setDtMov(venda.getDtVenda());
        if (tipo.equals("venda")) {
            mov.setEntrada("S"); // saída
        } else {
            mov.setEntrada("E"); // entrada
        }

        mov.incluir(mov, true);
    }

    private void gerarContas() {
        String tipoConta;
        if (jRadioButtonVenda.isSelected()) {
            tipoConta = "R"; // conta a receber
        } else {
            tipoConta = "P"; // conta a pagar
        }
        Contas contas = new Contas();
        //contas.setCdVendaCompra(venda.getCdVendaCompra());
        contas.setVendaCompra(venda);
        contas.setForma(venda.getForma());
        contas.setDsConta(tipo.toUpperCase() + " " + venda.getCdVendaCompra().toString());
        contas.setVlConta(venda.getVlTotal());
        contas.setTpConta(tipoConta);
        contas.setPago("N");
        contas.incluir(contas, true);
    }

    private void limparCampos() {
        jRadioButtonCompra.setEnabled(false);
        jRadioButtonVenda.setEnabled(false);
        limpar.limparCampos(jPanelGravar);
        limpar.limparJtable(jTableProdutos);
        jSpnQuantidade.setValue(1);
    }

    private void validaEstadoCampos() {
        ValidaBotoes botoes = new ValidaBotoes();
        botoes.validaEstadoCampos(jPanelGravar, rotina);
        valida.validaNivel(this.getName());
        valida.validaBotoesUsuario(jPanelBotoes);
        
        jTextFieldNrAtendimento.setEnabled(false);
        jTextFieldVlAtendimento.setEnabled(false);
        jTextFieldDsOperacao.setEnabled(false);
        jTextFieldNomeCliente.setEnabled(false);
        jTextFieldForma.setEnabled(false);
        jTextFieldProduto.setEnabled(false);
        jTextFieldTotalProduto.setEnabled(false);
    }
    
    private void editaBotao(boolean vazia) {
        if (vazia) {
            JOptionPane.showMessageDialog(null, "A consulta não encontrou resultados!");
            jBtRelatorio.setEnabled(false);
            jTextFieldConsulta.setText("");
            jTextFieldConsulta.grabFocus();
        } else {
            jBtRelatorio.setEnabled(valida.pRelatorio.equals("S"));
        }
    }
    
    private void preencherTabela(){
        PreencherTabela tabela = new PreencherTabela();
        int linha = jTableVendaCompra.getSelectedRow();
        if (linha >= 0) {
            venda.setCdVendaCompra(Integer.parseInt(jTableVendaCompra.getValueAt(linha, 0).toString()));
            venda.getVcProdutos().setCdVendaCompra(venda.getCdVendaCompra());

            tabela.FormatarJtable(jTableProdutosVenda, new int[]{170, 200, 170, 170, 170});
            tabela.PreencherJtableGenerico(jTableProdutosVenda,
                    venda.getVcProdutos().consultarProdutos(venda.getVcProdutos()));
            tabela.FormatarJtable(jTableConta, new int[]{80, 100, 200, 100, 100, 100, 100, 100});
            Contas c = new Contas();
            c.setVendaCompra(venda);
//            c.setCdVendaCompra(venda.getCdVendaCompra());
            tabela.PreencherJtableGenerico(jTableConta, c.consultarCdVendaCompra(c));

        } else {
            limpar.limparJtable(jTableProdutosVenda);
            limpar.limparJtable(jTableConta);
        }
    }
}
