
package Servicos;

import Classes.AtendimentoMesa;
import Classes.Mesa;
import Classes.Produto;
import Consultas.ConsultaFuncionario;
import Consultas.ConsultaMesa;
import Consultas.ConsultaProduto;
import Validacoes.FormataMoeda;
import Validacoes.PreencherTabela;
import Validacoes.RetornaData;
import Validacoes.RetornaDecimal;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Leonardo
 */
public class TelaAtendimentoMesa extends javax.swing.JFrame {

    AtendimentoMesa atd = new AtendimentoMesa();
    Produto produto = new Produto();

    RetornaData dataHora = new RetornaData();
    RetornaDecimal decimal = new RetornaDecimal();

    MaskFormatter data;
    MaskFormatter hora;

    /**
     * Creates new form AtendimentoMesa
     */
    public TelaAtendimentoMesa() {
        initComponents();
        jTextFieldVlUnitario.setDocument(new FormataMoeda());
        jTextFieldTotalProduto.setDocument(new FormataMoeda());
        jTextFieldTotal.setDocument(new FormataMoeda());
        formatarTabela();
        jTextFieldHoraAbre.setText(dataHora.retornaHoraAtual());
        jFormattedTextFieldData.setText(dataHora.retornaDataAtual(false));
//        iniciarAtendimento();
//        this.setTitle("Atendimento Nr."+atd.getNrAtendimento());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelAtendimento = new javax.swing.JPanel();
        jTextFieldNomeProduto = new javax.swing.JTextField();
        jBtAdicionar = new javax.swing.JButton();
        jBtFechaAtendimento = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldCdProduto = new javax.swing.JTextField();
        jButtonPesquisa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProdutos = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        try{       data = new MaskFormatter("##/##/####");   }   catch(Exception erro)   {   JOptionPane.showMessageDialog(null, "Não foi possivel localizar");   }
        jFormattedTextFieldData = new JFormattedTextField(data);
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldNomeFunc = new javax.swing.JTextField();
        jTextFieldNrMesa = new javax.swing.JTextField();
        jButtonPesquisar = new javax.swing.JButton();
        jTextFieldNrAtendimento = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jBtMesa = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldTotal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldCdFunc = new javax.swing.JTextField();
        jSpnQuantidade = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        jBtCancelar = new javax.swing.JButton();
        try{       hora = new MaskFormatter("##:##:##");   }   catch(Exception erro)   {   JOptionPane.showMessageDialog(null, "Não foi possivel localizar");   }
        jTextFieldHoraAbre = new JFormattedTextField(hora);
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldTotalProduto = new javax.swing.JTextField();
        try{       hora = new MaskFormatter("##:##:##");   }   catch(Exception erro)   {   JOptionPane.showMessageDialog(null, "Não foi possivel localizar");   }
        jTextFieldHoraFecha = new JFormattedTextField(hora);
        jBtRemover = new javax.swing.JButton();
        jTextFieldVlUnitario = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableAtendimento = new javax.swing.JTable();
        jComboBoxConsulta = new javax.swing.JComboBox();
        jBtPesquisar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableAtendimentoProdutos = new javax.swing.JTable();
        jTextFieldConsulta = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Realizar Atendimento");
        setResizable(false);

        jTextFieldNomeProduto.setEnabled(false);

        jBtAdicionar.setText("Adicionar");
        jBtAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtAdicionarActionPerformed(evt);
            }
        });

        jBtFechaAtendimento.setText("Fechar Atendimento");
        jBtFechaAtendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtFechaAtendimentoActionPerformed(evt);
            }
        });

        jLabel4.setText("Produto");

        jTextFieldCdProduto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldCdProdutoFocusLost(evt);
            }
        });

        jButtonPesquisa.setText("Pesquisar");
        jButtonPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisaActionPerformed(evt);
            }
        });

        jTableProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Produto", "Valor", "Quantidade", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProdutosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableProdutos);

        jLabel3.setText("Data Atendimento");

        jFormattedTextFieldData.setEnabled(false);

        jLabel5.setText("Quantidade");

        jLabel9.setText("Hora Fechamento");

        jTextFieldNomeFunc.setEnabled(false);

        jTextFieldNrMesa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldNrMesaFocusLost(evt);
            }
        });

        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        jTextFieldNrAtendimento.setEnabled(false);

        jLabel2.setText("Nr Mesa");

        jBtMesa.setText("Mesa...");
        jBtMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtMesaActionPerformed(evt);
            }
        });

        jLabel6.setText("Valor Unitário (R$)");

        jTextFieldTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldTotal.setEnabled(false);

        jLabel1.setText("Nr Atendimento");

        jLabel7.setText("Total (R$)");

        jTextFieldCdFunc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldCdFuncFocusLost(evt);
            }
        });

        jSpnQuantidade.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));
        jSpnQuantidade.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpnQuantidadeStateChanged(evt);
            }
        });

        jLabel11.setText("Funcionário");

        jBtCancelar.setText("Cancelar Atendimento");
        jBtCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtCancelarActionPerformed(evt);
            }
        });

        jTextFieldHoraAbre.setEnabled(false);

        jLabel8.setText("Hora Abertura");

        jLabel10.setText("Valor Total");

        jTextFieldTotalProduto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldTotalProduto.setEnabled(false);

        jTextFieldHoraFecha.setEnabled(false);

        jBtRemover.setText("Remover");
        jBtRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtRemoverActionPerformed(evt);
            }
        });

        jTextFieldVlUnitario.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout jPanelAtendimentoLayout = new javax.swing.GroupLayout(jPanelAtendimento);
        jPanelAtendimento.setLayout(jPanelAtendimentoLayout);
        jPanelAtendimentoLayout.setHorizontalGroup(
            jPanelAtendimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAtendimentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAtendimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAtendimentoLayout.createSequentialGroup()
                        .addGroup(jPanelAtendimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAtendimentoLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jBtFechaAtendimento)
                                .addGap(18, 18, 18)
                                .addComponent(jBtCancelar)))
                        .addContainerGap())
                    .addGroup(jPanelAtendimentoLayout.createSequentialGroup()
                        .addGroup(jPanelAtendimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNrAtendimento, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelAtendimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanelAtendimentoLayout.createSequentialGroup()
                                .addComponent(jTextFieldNrMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBtMesa)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelAtendimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelAtendimentoLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(29, 29, 29)
                                .addComponent(jLabel9))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAtendimentoLayout.createSequentialGroup()
                                .addComponent(jTextFieldHoraAbre, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldHoraFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)))
                        .addGap(55, 55, 55)
                        .addGroup(jPanelAtendimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jFormattedTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33))
                    .addGroup(jPanelAtendimentoLayout.createSequentialGroup()
                        .addGroup(jPanelAtendimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel11))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelAtendimentoLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelAtendimentoLayout.createSequentialGroup()
                        .addGroup(jPanelAtendimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelAtendimentoLayout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(jLabel6))
                            .addGroup(jPanelAtendimentoLayout.createSequentialGroup()
                                .addComponent(jSpnQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldVlUnitario)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelAtendimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelAtendimentoLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanelAtendimentoLayout.createSequentialGroup()
                                .addComponent(jTextFieldTotalProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                                .addComponent(jBtAdicionar)
                                .addGap(18, 18, 18)
                                .addComponent(jBtRemover)
                                .addGap(45, 45, 45)))
                        .addGroup(jPanelAtendimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jTextFieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAtendimentoLayout.createSequentialGroup()
                        .addGroup(jPanelAtendimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelAtendimentoLayout.createSequentialGroup()
                                .addComponent(jTextFieldCdFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonPesquisar))
                            .addGroup(jPanelAtendimentoLayout.createSequentialGroup()
                                .addComponent(jTextFieldCdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonPesquisa)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelAtendimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNomeFunc)
                            .addComponent(jTextFieldNomeProduto))
                        .addGap(40, 40, 40))))
        );
        jPanelAtendimentoLayout.setVerticalGroup(
            jPanelAtendimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAtendimentoLayout.createSequentialGroup()
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanelAtendimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAtendimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNrAtendimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNrMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtMesa)
                    .addComponent(jTextFieldHoraAbre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldHoraFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAtendimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCdFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPesquisar)
                    .addComponent(jTextFieldNomeFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAtendimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPesquisa)
                    .addComponent(jTextFieldNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelAtendimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAtendimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelAtendimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jSpnQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldTotalProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtRemover)
                        .addComponent(jBtAdicionar)
                        .addComponent(jTextFieldVlUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelAtendimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtCancelar)
                    .addComponent(jBtFechaAtendimento))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Realizar Atendimento", jPanelAtendimento);

        jLabel12.setText("Filtro da Consulta");

        jTableAtendimento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nr Atendimento", "Mesa", "Cd Funcionário", "Funcionário", "Hora Início", "Hora Fim", "Data", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableAtendimento);

        jComboBoxConsulta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Geral", "Nr Atendimento", "Nr Mesa", "Funcionário" }));

        jBtPesquisar.setText("Pesquisar");

        jTableAtendimentoProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nr Atendimento", "Cd Produto", "Produto", "Quantidade", "Valor Unitário", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTableAtendimentoProdutos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxConsulta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldConsulta)
                        .addGap(18, 18, 18)
                        .addComponent(jBtPesquisar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtPesquisar)
                    .addComponent(jTextFieldConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Consulta", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jTabbedPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 497, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jTabbedPane1))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        ConsultaFuncionario csFunc = new ConsultaFuncionario(this, true);
        csFunc.setVisible(true);
        
        csFunc.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {

                if (atd.getFuncionario().getCd_funcionario() == 0) {
                    jTextFieldCdFunc.setText("");
                    jTextFieldNomeFunc.setText("");
                } else {
                    jTextFieldCdFunc.setText(atd.getFuncionario().getCd_funcionario().toString());
                    atd.getFuncionario().retornaFuncionario(atd.getFuncionario(),false);
                    jTextFieldNomeFunc.setText(atd.getFuncionario().getPessoa().getNome());
                }
            }
        });
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jButtonPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisaActionPerformed
        ConsultaProduto csProd = new ConsultaProduto(this, true);
        csProd.setVisible(true);

        csProd.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {

                if (produto.getCdProduto() == 0) {
                    jTextFieldNomeProduto.setText("");
                    jTextFieldCdProduto.setText("");
                } else {
                    jTextFieldCdProduto.setText(produto.getCdProduto().toString());
                    produto.retornaProduto(produto, false);

                    preencherProduto();
                }
            }
        });
    }//GEN-LAST:event_jButtonPesquisaActionPerformed

    private void jBtMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtMesaActionPerformed
         ConsultaMesa csMesa = new ConsultaMesa(this, true);
        csMesa.setVisible(true);

        csMesa.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {

                if (atd.getMesa().getNrMesa() == 0) {
                    jTextFieldNrMesa.setText("");
                } else {
                    jTextFieldNrMesa.setText(atd.getMesa().getNrMesa().toString());
                }
            }
        });
    }//GEN-LAST:event_jBtMesaActionPerformed

    private void jTextFieldCdFuncFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCdFuncFocusLost
         if(!jTextFieldCdFunc.getText().equals("")){
            try{
                atd.getFuncionario().setCd_funcionario(Integer.parseInt(jTextFieldCdFunc.getText()));
                atd.getFuncionario().retornaFuncionario(atd.getFuncionario(), false);
                if(atd.getFuncionario().getPessoa().getNome().equals("")){
                    jTextFieldCdFunc.setText("");
                    jTextFieldNomeFunc.setText("");
                    jTextFieldCdFunc.grabFocus();
                }
                else{
                    jTextFieldNomeFunc.setText(atd.getFuncionario().getPessoa().getNome());
                }
            }
            catch(NumberFormatException ex){
                JOptionPane.showMessageDialog(null, "Por favor informe um código!");
                jTextFieldCdFunc.setText("");
                jTextFieldNomeFunc.setText("");
                jTextFieldCdFunc.grabFocus();
            }
        }
    }//GEN-LAST:event_jTextFieldCdFuncFocusLost

    private void jBtRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtRemoverActionPerformed
        int linha = jTableProdutos.getSelectedRow();
        if (linha>=0){
            int opcao = JOptionPane.showConfirmDialog(null, "Deseja realmente remover este produto do atendimento ?",
                    "Remover Produto", JOptionPane.YES_NO_OPTION);
            if(opcao == JOptionPane.YES_OPTION){
                
                DefaultTableModel tabela = (DefaultTableModel) jTableProdutos.getModel();
                // devolve os produtos ao estoque
                
                produto.alteraQtAtual(produto);
                // 
                tabela.removeRow(linha);
                jTextFieldTotal.setText(decimal.retornaDecimal(atd.retornaTotalAtendimento(jTableProdutos),6));
                
            }
        }
    }//GEN-LAST:event_jBtRemoverActionPerformed

    private void jBtAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtAdicionarActionPerformed
         if (jTextFieldCdProduto.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor informe o produto que deseja adicionar!");
            jTextFieldCdProduto.grabFocus();
        } else {
            adicionarProdutos();
            jTextFieldTotal.setText(decimal.retornaDecimal(atd.retornaTotalAtendimento(jTableProdutos),6));
            produto.setQtAtual(produto.getQtAtual() - Integer.parseInt(jSpnQuantidade.getValue().toString()));
            produto.alteraQtAtual(produto);
        }
    }//GEN-LAST:event_jBtAdicionarActionPerformed

    private void jTextFieldNrMesaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNrMesaFocusLost
         if (!jTextFieldNrMesa.getText().equals("")) {
            try {
                atd.getMesa().setNrMesa(Integer.parseInt(jTextFieldNrMesa.getText()));
                atd.getMesa().retornaMesa(atd.getMesa(), false);

                if (atd.getMesa().getDsMesa().equals("")) {
                    jTextFieldNrMesa.setText("");
                    jTextFieldNrMesa.grabFocus();
                }

            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Por favor informe um código!");
                jTextFieldNrMesa.setText("");
                jTextFieldNrMesa.grabFocus();
            }
        }
    }//GEN-LAST:event_jTextFieldNrMesaFocusLost

    private void jSpnQuantidadeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpnQuantidadeStateChanged
        try {
            double preco = Double.parseDouble(jTextFieldVlUnitario.getText()
            .replace(".", "").replace(",", "."));
            if (preco > 0) {
                preencherTotalProduto();
            }
        } catch (NumberFormatException ex) {
            jTextFieldTotalProduto.setText("");
        }
    }//GEN-LAST:event_jSpnQuantidadeStateChanged

    private void jBtCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtCancelarActionPerformed
        int opcao = JOptionPane.showConfirmDialog(null, "Os atendimentos cancelados não serão salvos no sistema.\n"
                + "Deseja cancelar este atendimento ?", "Cancelar Atendimento", JOptionPane.YES_NO_OPTION);

        if (opcao == JOptionPane.YES_OPTION) {
//            atd.setNrAtendimento(Integer.parseInt(jTextFieldNrAtendimento.getText()));
//            atd.excluir(atd);
            // devolve os produtos da jtable para o estoque
            int linhas = jTableProdutos.getRowCount();
            
            for (int i = 0; i< linhas; i++){
            
            int cd = Integer.parseInt(jTableProdutos.getValueAt(i, 0).toString());
            int qt = Integer.parseInt(jTableProdutos.getValueAt(i, 3).toString());
            
            produto.setCdProduto(cd);
            produto.retornaProduto(produto, false);
            produto.setQtAtual(produto.getQtAtual() + qt);
            produto.alteraQtAtual(produto);
        }
            dispose();
        }
    }//GEN-LAST:event_jBtCancelarActionPerformed

    private void jTextFieldCdProdutoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCdProdutoFocusLost
        if (!jTextFieldCdProduto.getText().equals("")) {
            try {
                produto.setCdProduto(Integer.parseInt(jTextFieldCdProduto.getText()));
                produto.retornaProduto(produto, false);

                if (produto.getDsProduto().equals("")) {
                    jTextFieldCdProduto.setText("");
                    jTextFieldNomeProduto.setText("");
                    jTextFieldCdProduto.grabFocus();
                } else {
                    preencherProduto();
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Por favor informe um código!");
                jTextFieldCdProduto.setText("");
                jTextFieldNomeProduto.setText("");
                jTextFieldCdProduto.grabFocus();
            }
        }
    }//GEN-LAST:event_jTextFieldCdProdutoFocusLost

    private void jBtFechaAtendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtFechaAtendimentoActionPerformed
        jTextFieldHoraFecha.setText(dataHora.retornaHoraAtual());
        fecharAtendimento();
    }//GEN-LAST:event_jBtFechaAtendimentoActionPerformed

    private void jTableProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProdutosMouseClicked
        int linha = jTableProdutos.getSelectedRow();
        if (linha >=0){
            produto.setCdProduto(Integer.parseInt(jTableProdutos.getValueAt(linha, 0).toString()));
            produto.retornaProduto(produto, false);
            produto.setQtAtual(produto.getQtAtual() + Integer.parseInt(jTableProdutos.getValueAt(linha, 3).toString()));
        }
    }//GEN-LAST:event_jTableProdutosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAtendimentoMesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAtendimentoMesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAtendimentoMesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAtendimentoMesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAtendimentoMesa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtAdicionar;
    private javax.swing.JButton jBtCancelar;
    private javax.swing.JButton jBtFechaAtendimento;
    private javax.swing.JButton jBtMesa;
    private javax.swing.JButton jBtPesquisar;
    private javax.swing.JButton jBtRemover;
    private javax.swing.JButton jButtonPesquisa;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JComboBox jComboBoxConsulta;
    private javax.swing.JFormattedTextField jFormattedTextFieldData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelAtendimento;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSpnQuantidade;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableAtendimento;
    private javax.swing.JTable jTableAtendimentoProdutos;
    private javax.swing.JTable jTableProdutos;
    private javax.swing.JTextField jTextFieldCdFunc;
    private javax.swing.JTextField jTextFieldCdProduto;
    private javax.swing.JTextField jTextFieldConsulta;
    private javax.swing.JTextField jTextFieldHoraAbre;
    private javax.swing.JTextField jTextFieldHoraFecha;
    private javax.swing.JTextField jTextFieldNomeFunc;
    private javax.swing.JTextField jTextFieldNomeProduto;
    private javax.swing.JTextField jTextFieldNrAtendimento;
    private javax.swing.JTextField jTextFieldNrMesa;
    private javax.swing.JTextField jTextFieldTotal;
    private javax.swing.JTextField jTextFieldTotalProduto;
    private javax.swing.JTextField jTextFieldVlUnitario;
    // End of variables declaration//GEN-END:variables

    public void preencherProduto() {
        jTextFieldNomeProduto.setText(produto.getDsProduto());
        int max = produto.getQtAtual();
        SpinnerNumberModel model = new SpinnerNumberModel(1, 1, max, 1);
        jSpnQuantidade.setModel(model);
        jTextFieldVlUnitario.setText(decimal.retornaDecimal(produto.getVlProduto(), 6));
        preencherTotalProduto();

    }

    public void preencherTotalProduto() {
        double preco = Double.parseDouble(jTextFieldVlUnitario.getText()
        .replace(".", "").replace(",", "."));
                  
        int qt = Integer.parseInt(jSpnQuantidade.getValue().toString());
        jTextFieldTotalProduto.setText(decimal.retornaDecimal(qt * preco, 6));
        
    }

    public void adicionarProdutos() {
        DefaultTableModel tabela = (DefaultTableModel) jTableProdutos.getModel();
        SpinnerNumberModel spn =  (SpinnerNumberModel) jSpnQuantidade.getModel();
        
        String cd = jTextFieldCdProduto.getText();
        double valor = Double.parseDouble(jTextFieldVlUnitario.getText()
        .replace(".", "").replace(",", "."));
        int quantidade = Integer.parseInt(jSpnQuantidade.getValue().toString());
        int max = (int) spn.getMaximum(); 
        int linhas = jTableProdutos.getRowCount();
        
        boolean repetido = false;

        int posicao = linhas;

        if(linhas<0){
            tabela.setNumRows(linhas+1);
        }
        
        else {

            for (int i = 0; i < linhas; i++) {
                if (jTableProdutos.getValueAt(i, 0).toString().equals(cd)) {
                    repetido = true;
                    posicao = i;
                }
            }

            if (repetido) {
                int qtTabela = Integer.parseInt(jTableProdutos.getValueAt(posicao,3).toString());
                
                if(quantidade + qtTabela > max){
                    JOptionPane.showMessageDialog(null, "Quantidade indisponível para este produto!");
                    quantidade = qtTabela;
                }
                else{
                    quantidade = quantidade + qtTabela;
                }
            } else {
                
                tabela.setNumRows(linhas + 1);
            }
        } 
        
        tabela.setValueAt(cd, posicao, 0);
        tabela.setValueAt(jTextFieldNomeProduto.getText(), posicao, 1);
        tabela.setValueAt(decimal.retornaDecimal(valor), posicao, 2);
        tabela.setValueAt(quantidade, posicao, 3);
        double total = quantidade * valor;
        tabela.setValueAt(decimal.retornaDecimal(total), posicao, 4);

    }
    
    public void formatarTabela(){
        PreencherTabela preencher = new PreencherTabela();
        preencher.FormatarJtable(jTableProdutos, new int [] {100,280,100,100,100});
    }
    
    public void iniciarAtendimento(){
        atd.setDtAtendimento(jFormattedTextFieldData.getText());
        atd.setHoraAbertura(jTextFieldHoraAbre.getText());
        atd.setAbertoFechado("A");
        atd.incluir(atd);
        jTextFieldNrAtendimento.setText(atd.getNrAtendimento().toString());
    }
    
    public void fecharAtendimento(){
        int linhas = jTableProdutos.getRowCount();
        if(jTextFieldNrMesa.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Por favor informe a mesa do atendimento!");
            jTextFieldNrMesa.grabFocus();
        }
        else if(jTextFieldCdFunc.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Por favor informe o funcionário do atendimento!");
            jTextFieldCdFunc.grabFocus();
        }
        else if(linhas < 1){
            JOptionPane.showMessageDialog(null, "Por favor adicione produtos no atendimento!");
            jTextFieldCdProduto.grabFocus();
        }
        else{
            atd.setAbertoFechado("F");
            atd.setNrAtendimento(Integer.parseInt(jTextFieldNrAtendimento.getText()));
            atd.getMesa().setNrMesa(Integer.parseInt(jTextFieldNrMesa.getText()));
            atd.getFuncionario().setCd_funcionario(Integer.parseInt(jTextFieldCdFunc.getText()));
            atd.setHoraAbertura(jTextFieldHoraAbre.getText());
            atd.setHoraFechamento(jTextFieldHoraFecha.getText());
            atd.setDtAtendimento(jFormattedTextFieldData.getText());
            atd.setVlTotal(Double.parseDouble(jTextFieldTotal.getText()));
            
            atd.alterar(atd);
        }
    }
}
